// Lint for the TypeScript endpoint project.
//
// This is the HAND-WRITTEN side. The IDM runtime bans (default params,
// `const` in a loop initializer, trailing comma in a parameter list) are
// checked against the GENERATED bundle instead, by `tools/idm-runtime-bans.mjs`
// — Babel rewrites the source so thoroughly that linting the TypeScript for
// them would be checking the wrong artifact.
//
// Two runtime hazards have to be caught in the SOURCE, because nothing
// downstream can see them.
//
// SUBCLASSING A NATIVE. `Reflect` is undefined on both engines, so Babel's
// `_wrapNativeSuper` cannot restore the subclass prototype and
// `instanceof YourError` is silently false (probed 2026-08-13). That was found
// for `Error` and banned for `Error`, but it is a property of the lowering,
// not of `Error`: the same is true of `Array`, `Map`, `Promise` and every
// other native constructor. The list is DERIVED from the pinned lib by
// `tools/engine-coverage.mjs`, so a lib change cannot leave a new one
// unbanned.
//
// ASYNC AND GENERATORS. An `async` function is assignable to a `() => void`
// handler, so it compiles -- and then nothing awaits it. A PingIDM endpoint's
// response body is the script's COMPLETION VALUE, and an AM scripted decision
// node's outcome is whatever `goTo` recorded by the time `main` returns; both
// would see a pending Promise instead of a result. Rhino has no event loop
// here either, so nothing would drain the microtask queue even if they did.
// Babel's `_asyncToGenerator` and regenerator helpers are also outside the
// probed corpus. There is no version of this that works, so it is banned
// rather than measured.
//
// Both bans apply to `framework/` and `src/` only. `tests/` runs under node,
// where `async` is ordinary and no downlevel happens.
//
// Managed file — regenerated by `fo upgrade`.

import js from "@eslint/js";
import tseslint from "typescript-eslint";

import { constructorGlobals, readTsconfig } from "./tools/engine-coverage.mjs";

const NATIVES = constructorGlobals(
  readTsconfig("tsconfig.json").compilerOptions.lib,
);

const engineHazards = [
  {
    selector:
      ":matches(ClassDeclaration, ClassExpression)" +
      `[superClass.name=/^(${NATIVES.join("|")})$/]`,
    message:
      "Never subclass a native: Reflect is undefined on both engines, so after Babel's downlevel `_wrapNativeSuper` cannot restore the prototype and `instanceof YourClass` is silently false. For errors, use the tagged fault objects in framework/errors.ts; otherwise compose rather than extend.",
  },
  {
    selector: "BinaryExpression[operator='instanceof'][right.name=/Error$/]",
    message:
      "instanceof against an Error type does not survive the ES5 downlevel. Use `isFault(value)` from framework/errors.ts.",
  },
  {
    selector: ":matches(FunctionDeclaration, FunctionExpression, ArrowFunctionExpression, ClassMethod, ObjectMethod)[async=true]",
    message:
      "No async on the script engines. An endpoint's response body is the script's completion value and an AM node's outcome is read when `main` returns, so an unawaited Promise is what the host would get; Rhino has no event loop here to settle it either. Write it synchronously.",
  },
  {
    selector: ":matches(FunctionDeclaration, FunctionExpression, ClassMethod, ObjectMethod)[generator=true]",
    message:
      "No generators on the script engines. Babel lowers them through regenerator helpers that are outside the probed corpus, and nothing here drives an iterator to completion for you.",
  },
  {
    selector: "AwaitExpression, ForOfStatement[await=true]",
    message:
      "No await on the script engines: nothing settles a Promise here. Write it synchronously.",
  },
];

export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "openapi/**",
      "node_modules/**",
      "src/generated/**",
      // Babel's ES5 output, committed on purpose so `fo doctor --engines` can
      // run the pipeline's real emit. Linting generated helpers says nothing.
      "framework/engine-emit-probe.js",
      ".aic-ts-manifest.json",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["framework/**/*.ts", "src/**/*.ts"],
    rules: {
      // Only here: `tests/` runs under node and is downlevelled by nothing.
      "no-restricted-syntax": ["error", ...engineHazards],
    },
  },
  {
    files: ["framework/**/*.ts", "src/**/*.ts", "tests/**/*.ts"],
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { fixStyle: "inline-type-imports" },
      ],
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      eqeqeq: ["error", "always"],
      curly: "error",
      "no-console": "error",
    },
  },
  {
    // Build tooling and .mjs tests run under node, not on PingIDM: none of the
    // above applies.
    files: ["tools/**/*.mjs", "tests/**/*.mjs"],
    languageOptions: {
      globals: {
        Buffer: "readonly",
        clearTimeout: "readonly",
        console: "readonly",
        process: "readonly",
        setTimeout: "readonly",
      },
    },
    rules: { "no-console": "off" },
  }
);
