// Lint for the TypeScript endpoint project.
//
// This is the HAND-WRITTEN side. The IDM runtime bans (default params,
// `const` in a loop initializer, trailing comma in a parameter list) are
// checked against the GENERATED bundle instead, by `tools/idm-runtime-bans.mjs`
// — Babel rewrites the source so thoroughly that linting the TypeScript for
// them would be checking the wrong artifact.
//
// The SYNTACTIC half of the engine rules.
//
// `async`, `await` and generators are banned on `framework/` and `src/`.
// An `async` function is assignable to a `() => void` handler, so it compiles
// -- and then nothing awaits it. A PingIDM endpoint's response body is the
// script's COMPLETION VALUE, and an AM scripted decision node's outcome is
// whatever `goTo` recorded by the time `main` returns; both would see a pending
// Promise instead of a result, and Rhino has no event loop here to settle one.
//
// The generator ban is CONSERVATIVE rather than forced: a local synchronous
// generator driven by `for...of` would have something driving it, and might
// well work. Babel lowers it through regenerator helpers that are not in the
// probed corpus, so the ban stands until they are -- but it stands as a support
// boundary, not as a measured impossibility. Add the case to
// `tools/emit-corpus.ts` and measure it if you want it.
//
// Not on `tests/`, which runs under node, where none of this applies and
// nothing is downlevelled.
//
// THE OTHER TWO ENGINE RULES USED TO LIVE HERE AND DO NOT ANY MORE. Banning a
// native superclass by AST selector had escapes (`const E = Error`,
// `globalThis.Error`) and false positives (a project class named `Map`), and
// banning `instanceof /Error$/` caught `instanceof DomainError` for no reason.
// Both are now `tools/engine-usage.mjs`, which resolves through the checker and
// runs on the build path -- and the `instanceof` rule is simply gone, because
// with native subclassing rejected outright there is nothing left for it to
// protect.
//
// The IDM runtime bans (default params, `const` in a loop initializer, trailing
// comma in a parameter list) are checked against the GENERATED bundle instead,
// by `tools/idm-runtime-bans.mjs` -- Babel rewrites the source so thoroughly
// that linting the TypeScript for them would be checking the wrong artifact.
//
// Managed file — regenerated by `fo upgrade`.

import js from "@eslint/js";
import tseslint from "typescript-eslint";

const engineHazards = [
  {
    selector: ":matches(FunctionDeclaration, FunctionExpression, ArrowFunctionExpression, ClassMethod, ObjectMethod)[async=true]",
    message:
      "No async on the script engines. An endpoint's response body is the script's completion value and an AM node's outcome is read when `main` returns, so an unawaited Promise is what the host would get; Rhino has no event loop here to settle it either. Write it synchronously.",
  },
  {
    selector: ":matches(FunctionDeclaration, FunctionExpression, ClassMethod, ObjectMethod)[generator=true]",
    message:
      "No generators on the script engines. Babel lowers them through regenerator helpers that are outside the probed corpus. This is a support boundary rather than a measured failure: add a case to tools/emit-corpus.ts and re-probe if you need them.",
  },
  {
    selector: "AwaitExpression, ForOfStatement[await=true]",
    message:
      "No await on the script engines: nothing settles a Promise here. Write it synchronously.",
  },
];

export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "openapi/**",
      "node_modules/**",
      "src/generated/**",
      // Babel's ES5 output, committed on purpose so `fo doctor --engines` can
      // run the pipeline's real emit. Linting generated helpers says nothing.
      "framework/engine-emit-probe.js",
      ".aic-ts-manifest.json",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["framework/**/*.ts", "src/**/*.ts"],
    rules: {
      // Only here: `tests/` runs under node and is downlevelled by nothing.
      "no-restricted-syntax": ["error", ...engineHazards],
    },
  },
  {
    files: ["framework/**/*.ts", "src/**/*.ts", "tests/**/*.ts"],
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { fixStyle: "inline-type-imports" },
      ],
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      eqeqeq: ["error", "always"],
      curly: "error",
      "no-console": "error",
    },
  },
  {
    // Build tooling and .mjs tests run under node, not on PingIDM: none of the
    // above applies.
    files: ["tools/**/*.mjs", "tests/**/*.mjs"],
    languageOptions: {
      globals: {
        Buffer: "readonly",
        clearTimeout: "readonly",
        console: "readonly",
        process: "readonly",
        setTimeout: "readonly",
      },
    },
    rules: { "no-console": "off" },
  }
);
