// Lint for the TypeScript endpoint project.
//
// This is the HAND-WRITTEN side. The IDM runtime bans (default params,
// `const` in a loop initializer, trailing comma in a parameter list) are
// checked against the GENERATED bundle instead, by `tools/idm-runtime-bans.mjs`
// — Babel rewrites the source so thoroughly that linting the TypeScript for
// them would be checking the wrong artifact.
//
// The one runtime hazard that must be caught in the source is subclassing
// `Error`: `Reflect` is undefined on IDM, so Babel's `_wrapNativeSuper` cannot
// restore the subclass prototype and `instanceof YourError` is silently false
// (probed 2026-08-13). Nothing downstream can detect that, so it is banned here.
//
// Managed file — regenerated by `aic workspace update`.

import js from "@eslint/js";
import tseslint from "typescript-eslint";

const noNativeErrorSubclass = [
  {
    selector:
      ":matches(ClassDeclaration, ClassExpression)[superClass.name='Error']",
    message:
      "Never subclass Error: Reflect is undefined on IDM, so after Babel's downlevel `instanceof YourError` is false while `instanceof Error` is true. Use the tagged fault objects in framework/errors.ts.",
  },
  {
    selector: "BinaryExpression[operator='instanceof'][right.name=/Error$/]",
    message:
      "instanceof against an Error type does not survive the ES5 downlevel. Use `isFault(value)` from framework/errors.ts.",
  },
];

export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "openapi/**",
      "node_modules/**",
      "src/generated/**",
      ".aic-ts-manifest.json",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["framework/**/*.ts", "src/**/*.ts", "tests/**/*.ts"],
    rules: {
      "no-restricted-syntax": ["error", ...noNativeErrorSubclass],
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { fixStyle: "inline-type-imports" },
      ],
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      eqeqeq: ["error", "always"],
      curly: "error",
      "no-console": "error",
    },
  },
  {
    // Build tooling and .mjs tests run under node, not on PingIDM: none of the
    // above applies.
    files: ["tools/**/*.mjs", "tests/**/*.mjs"],
    languageOptions: {
      globals: {
        Buffer: "readonly",
        clearTimeout: "readonly",
        console: "readonly",
        process: "readonly",
        setTimeout: "readonly",
      },
    },
    rules: { "no-console": "off" },
  }
);
