import type { ResolvedConfig } from "./config.ts";

/**
 * Tier 1 of the log story (PLAN.md section 9): VictoriaLogs plus a Vector
 * DaemonSet, deployed as plain Kubernetes objects rather than a third Helm
 * chart.
 *
 * Plain objects because `fo` already renders JSON for `helm --values` and
 * `kubectl apply -f -` accepts JSON just as happily. Adding a chart would mean
 * a second chart repository to pin, a second `helm upgrade` to sequence
 * against the platform's, and an upstream we do not control shaping the one
 * thing this tier exists to get right - which fields end up indexed.
 */

/** Pinned deliberately: an unpinned collector is a silent format change. */
export const VICTORIALOGS_IMAGE = "docker.io/victoriametrics/victoria-logs:v1.52.0";
export const VECTOR_IMAGE = "docker.io/timberio/vector:0.57.0-distroless-libc";

/** In-cluster name of the log store. Also the Service and Deployment name. */
export const LOGS_NAME = "fo-logs";
export const VECTOR_NAME = "fo-vector";
export const LOGS_PORT = 9428;

/**
 * The ingress path the console is served under.
 *
 * A path on the platform's own host rather than a `logs.<env>` hostname: the
 * chart's cert covers exactly `cfg.fqdn`, so a second hostname would need a
 * second Certificate and a second name to resolve, to gain nothing. `/logs` is
 * not a platform route - see the ingress table in commands/info.ts.
 */
export const LOGS_PATH = "/logs";

export function logsUrl(cfg: ResolvedConfig): string {
  return `https://${cfg.fqdn}${LOGS_PATH}/`;
}

type Manifest = Record<string, unknown>;

function labels(app: string, cfg: ResolvedConfig): Record<string, string> {
  return {
    app,
    "app.kubernetes.io/name": app,
    "app.kubernetes.io/part-of": "fo-logs",
    "fo.env": cfg.env,
  };
}

/**
 * Vector's pipeline, as VRL.
 *
 * The whole point of tier 1 is what this does: every component already writes
 * structured audit JSON to stdout (verified for AM, IDM and DS), so the
 * collector's job is to hoist those fields to the top level where the store
 * can index them, and to stamp the event's own timestamp as the time axis
 * rather than the moment Vector happened to read the line.
 */
export function vectorConfig(cfg: ResolvedConfig): string {
  // Namespace-scoped so N environments can share one cluster without N
  // collectors each shipping everyone's logs.
  const probeFilter = cfg.logs.includeHealthChecks
    ? ""
    : `
  # The kubelet's own liveness and readiness traffic. Measured at 96-99% of
  # the UI pods' output; keeping it means the console mostly shows Kubernetes
  # talking to itself.
  keep:
    type: filter
    inputs: [shape]
    # Negation does not compile here: VRL cannot prove a field's type, and
    # negation is boolean-only. Comparing to true needs no such proof.
    condition: '.probe != true'
`;
  const sinkInput = cfg.logs.includeHealthChecks ? "shape" : "keep";

  return `# Generated by fo. Edits are overwritten on the next \`fo up\`.
data_dir: /vector-data

api:
  enabled: false

sources:
  pods:
    type: kubernetes_logs
    extra_field_selector: metadata.namespace=${cfg.namespace}
    glob_minimum_cooldown_ms: 500
    # Start at the tail, not the head of every file on the node.
    #
    # Measured: with the default (beginning), enabling the console on a stack
    # that had been up 13 hours OOM-killed the collector inside one second -
    # it tries to ship the node's entire backlog while the store is still
    # starting, and the sink's retry queue grows faster than the limit allows.
    # Reading from the end means the console covers "from when you turned it
    # on", which is what a developer enabling it actually wants, and it keeps
    # the first day from being spent re-ingesting history nobody asked for.
    # Checkpoints still make restarts resume exactly where they left off.
    read_from: end

transforms:
  shape:
    type: remap
    inputs: [pods]
    source: |
      # Vector's own read time, kept before the merge below can shadow it.
      ingested = .timestamp

      k8s_component = to_string(.kubernetes.pod_labels.app) ?? "unknown"
      .pod = to_string(.kubernetes.pod_name) ?? ""
      .container = to_string(.kubernetes.container_name) ?? ""
      # The RAW line stays in _msg even for audit events, whose fields are
      # also promoted below. That duplicate is deliberate: VictoriaLogs
      # free-text search reads _msg only, so without it "fo logs search
      # amadmin" would silently miss every audit event - the one place the
      # username actually appears. It compresses to almost nothing.
      ._msg = to_string(.message) ?? ""
      # Dropped BEFORE the merge, not with the other deletions at the end:
      # PingAM's non-audit JSON logging has a "message" field of its own, and
      # deleting afterwards took that with it - leaving those lines with
      # nothing to show but their raw JSON body.
      del(.message)

      # Audit events are JSON objects on stdout; everything else is a plain
      # line and keeps only the fields above.
      parsed = parse_json(._msg) ?? null
      if is_object(parsed) {
        . = merge(., object!(parsed), deep: true)
        .audit = true
      } else {
        .audit = false
      }

      # AFTER the merge, deliberately. PingAM's audit events carry their own
      # component field - Authentication, Session, OAuth - and a deep merge
      # lets it overwrite the pod's app label, so a trace reads as if it came
      # from six services that do not exist. The payload's value is worth
      # keeping, just not under this name.
      if exists(.component) && .component != k8s_component {
        .auditComponent = .component
      }
      .component = k8s_component

      # Health-probe traffic, marked rather than dropped here so it is one
      # decision in one place - and so it stays queryable when it is kept.
      # Matched on the raw line because the components disagree about where
      # the evidence is: nginx puts the kube-probe user agent in the line,
      # PingAM logs a bare path with no agent at all, and PingIDM buries the
      # agent inside its audit JSON. The raw line has all three.
      msg = to_string(._msg) ?? ""
      .probe = contains(msg, "kube-probe") ||
        contains(msg, "/json/health/") ||
        contains(msg, "/info/ping") ||
        contains(msg, "/isAlive")

      # The event's own timestamp is the axis worth querying: a trace is only
      # useful in the order things actually happened, not the order Vector
      # read them.
      ._time = parse_timestamp(to_string(.timestamp) ?? "", "%+") ?? ingested

      # Copies we already promoted, or noise the store would index for nothing.
      del(.timestamp)
      del(.kubernetes)
      del(.file)
      del(.source_type)

      # The event is "." itself; a bare trailing reference says so explicitly.
      .
${probeFilter}
sinks:
  victorialogs:
    type: http
    inputs: [${sinkInput}]
    # jsonline rather than the Elasticsearch or Loki endpoints: it is the only
    # one that takes arbitrary JSON objects with the field names untouched,
    # which is the entire requirement.
    uri: http://${LOGS_NAME}:${LOGS_PORT}${LOGS_PATH}/insert/jsonline?_msg_field=_msg&_time_field=_time&_stream_fields=component,pod,container
    method: post
    # Explicit, because VictoriaLogs' jsonline endpoint answers 200 with an
    # empty body and ingests ZERO rows when the content type is one it does
    # not recognise - there is no error anywhere to find. Verified: 0 rows for
    # application/x-www-form-urlencoded, all rows for application/json.
    request:
      headers:
        Content-Type: application/json
    encoding:
      codec: json
    framing:
      method: newline_delimited
    healthcheck:
      enabled: false
    batch:
      max_events: 1000
      timeout_secs: 2
    buffer:
      type: memory
      max_events: 2000
      when_full: drop_newest
`;
}

/**
 * Every object the tier-1 stack needs, in apply order.
 *
 * Returned as a list rather than applied here so `fo up` can render it to
 * `.fo/<env>/logstack.json` first - the same "you can read exactly what was
 * deployed" property the generated Helm values have.
 */
export function logStackManifests(cfg: ResolvedConfig): Manifest[] {
  const ns = cfg.namespace;
  const vlLabels = labels(LOGS_NAME, cfg);
  const vecLabels = labels(VECTOR_NAME, cfg);
  // Cluster-scoped objects are shared by every env in the cluster, so their
  // names must carry the namespace or a second env silently rebinds the first.
  const rbacName = `${VECTOR_NAME}-${ns}`;

  return [
    {
      apiVersion: "v1",
      kind: "PersistentVolumeClaim",
      metadata: { name: LOGS_NAME, namespace: ns, labels: vlLabels },
      spec: {
        accessModes: ["ReadWriteOnce"],
        storageClassName: "fast",
        resources: { requests: { storage: cfg.logs.diskSize } },
      },
    },
    {
      apiVersion: "v1",
      kind: "Service",
      metadata: { name: LOGS_NAME, namespace: ns, labels: vlLabels },
      spec: {
        selector: { app: LOGS_NAME },
        ports: [{ name: "http", port: LOGS_PORT, targetPort: LOGS_PORT }],
      },
    },
    {
      apiVersion: "apps/v1",
      kind: "Deployment",
      metadata: { name: LOGS_NAME, namespace: ns, labels: vlLabels },
      spec: {
        replicas: 1,
        // The PVC is ReadWriteOnce and VictoriaLogs takes an exclusive lock on
        // its data directory, so the default rolling update would deadlock:
        // the new pod cannot start until the old one releases the volume.
        strategy: { type: "Recreate" },
        selector: { matchLabels: { app: LOGS_NAME } },
        template: {
          metadata: { labels: vlLabels },
          spec: {
            securityContext: { fsGroup: 1000, runAsUser: 1000, runAsNonRoot: true },
            containers: [
              {
                name: "victorialogs",
                image: VICTORIALOGS_IMAGE,
                imagePullPolicy: "IfNotPresent",
                args: [
                  `-storageDataPath=/vlogs`,
                  `-retentionPeriod=${cfg.logs.retention}`,
                  `-httpListenAddr=:${LOGS_PORT}`,
                  // Served behind the platform ingress on a path, so it must
                  // know its own prefix or every link in its UI 404s.
                  `-http.pathPrefix=${LOGS_PATH}`,
                  // Never let the store outgrow its volume: dropping the
                  // oldest day is a better failure than a full PVC, which
                  // wedges the pod and needs manual recovery.
                  `-retention.maxDiskUsagePercent=80`,
                  // Cache sizing is by percent of HOST memory by default,
                  // which on a laptop means VictoriaLogs plans around 16 GB it
                  // will never be allowed to touch.
                  `-memory.allowedBytes=128MB`,
                  `-loggerFormat=json`,
                ],
                ports: [{ name: "http", containerPort: LOGS_PORT }],
                volumeMounts: [{ name: "data", mountPath: "/vlogs" }],
                resources: {
                  requests: { cpu: "50m", memory: "64Mi" },
                  limits: { memory: "512Mi" },
                },
                readinessProbe: {
                  httpGet: { path: `${LOGS_PATH}/health`, port: LOGS_PORT },
                  initialDelaySeconds: 3,
                  periodSeconds: 10,
                },
              },
            ],
            volumes: [
              { name: "data", persistentVolumeClaim: { claimName: LOGS_NAME } },
            ],
          },
        },
      },
    },
    {
      apiVersion: "networking.k8s.io/v1",
      kind: "Ingress",
      metadata: { name: LOGS_NAME, namespace: ns, labels: vlLabels },
      spec: {
        ingressClassName: "traefik",
        // Reuses the platform's cert-manager secret; the host is the same.
        tls: [{ hosts: [cfg.fqdn], secretName: "platform-tls" }],
        rules: [
          {
            host: cfg.fqdn,
            http: {
              paths: [
                {
                  path: LOGS_PATH,
                  pathType: "Prefix",
                  backend: {
                    service: { name: LOGS_NAME, port: { number: LOGS_PORT } },
                  },
                },
              ],
            },
          },
        ],
      },
    },
    {
      apiVersion: "v1",
      kind: "ConfigMap",
      metadata: { name: VECTOR_NAME, namespace: ns, labels: vecLabels },
      data: { "vector.yaml": vectorConfig(cfg) },
    },
    {
      apiVersion: "v1",
      kind: "ServiceAccount",
      metadata: { name: VECTOR_NAME, namespace: ns, labels: vecLabels },
    },
    {
      apiVersion: "rbac.authorization.k8s.io/v1",
      kind: "ClusterRole",
      metadata: { name: rbacName, labels: vecLabels },
      rules: [
        {
          apiGroups: [""],
          resources: ["pods", "namespaces", "nodes"],
          verbs: ["get", "list", "watch"],
        },
      ],
    },
    {
      apiVersion: "rbac.authorization.k8s.io/v1",
      kind: "ClusterRoleBinding",
      metadata: { name: rbacName, labels: vecLabels },
      roleRef: {
        apiGroup: "rbac.authorization.k8s.io",
        kind: "ClusterRole",
        name: rbacName,
      },
      subjects: [
        { kind: "ServiceAccount", name: VECTOR_NAME, namespace: ns },
      ],
    },
    {
      apiVersion: "apps/v1",
      kind: "DaemonSet",
      metadata: { name: VECTOR_NAME, namespace: ns, labels: vecLabels },
      spec: {
        selector: { matchLabels: { app: VECTOR_NAME } },
        template: {
          metadata: {
            labels: vecLabels,
            // Restart the collector when its pipeline changes. Without this a
            // `fo up` that only edits the ConfigMap leaves the old config
            // running and the change looks like it did nothing.
            annotations: { "fo/config-hash": hashConfig(vectorConfig(cfg)) },
          },
          spec: {
            serviceAccountName: VECTOR_NAME,
            containers: [
              {
                name: "vector",
                image: VECTOR_IMAGE,
                imagePullPolicy: "IfNotPresent",
                args: ["--config", "/etc/vector/vector.yaml"],
                env: [
                  {
                    name: "VECTOR_SELF_NODE_NAME",
                    valueFrom: { fieldRef: { fieldPath: "spec.nodeName" } },
                  },
                ],
                volumeMounts: [
                  { name: "config", mountPath: "/etc/vector" },
                  { name: "data", mountPath: "/vector-data" },
                  { name: "pod-logs", mountPath: "/var/log/pods", readOnly: true },
                ],
                resources: {
                  requests: { cpu: "50m", memory: "96Mi" },
                  // Headroom over the steady state: a burst of pod restarts
                  // puts every component's startup output through at once.
                  limits: { memory: "384Mi" },
                },
              },
            ],
            volumes: [
              { name: "config", configMap: { name: VECTOR_NAME } },
              // hostPath, not emptyDir: Vector checkpoints how far it has read
              // here, and losing that on a pod restart re-ships every line the
              // node still has on disk.
              {
                name: "data",
                hostPath: { path: `/var/lib/fo-vector/${ns}`, type: "DirectoryOrCreate" },
              },
              { name: "pod-logs", hostPath: { path: "/var/log/pods" } },
            ],
          },
        },
      },
    },
  ];
}

/** A short stable digest of the pipeline, for the restart annotation. */
function hashConfig(text: string): string {
  // Cheap FNV-1a rather than node:crypto - this only has to change when the
  // config changes, and it keeps this module dependency-free and pure.
  let h = 0x811c9dc5;
  for (let i = 0; i < text.length; i++) {
    h ^= text.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h.toString(16).padStart(8, "0");
}

/** Names of the cluster-scoped objects, so `fo down` can clean them up. */
export function clusterScopedNames(cfg: ResolvedConfig): string[] {
  return [`${VECTOR_NAME}-${cfg.namespace}`];
}
