// PingAM's scripted-decision-node bindings, evaluatorVersion 2.0.
//
// Deliberately NARROW. Only what is declared here type-checks, so a binding
// this file does not describe is a compile error rather than a runtime one --
// which matters more in AM than in IDM, because an AM script's failure mode is
// a journey that dead-ends for a real user.
//
// These bindings are NOT the IDM ones: there is no `openidm`, no `request` and
// no `context`. That is why AM scripts live in src/scripts/ under their own
// tsconfig rather than alongside the endpoints.
//
// Managed file -- regenerated by `fo upgrade`.

/** The outcome builder. Calling it is how a node decides where to go next. */
declare const action: {
  goTo(outcome: string): AmActionBuilder;
};

interface AmActionBuilder {
  /** Carry a value forward to later nodes in the journey. */
  withHeader(header: string): AmActionBuilder;
  withErrorMessage(message: string): AmActionBuilder;
  withDescription(description: string): AmActionBuilder;
  withStage(stage: string): AmActionBuilder;
  replaceSharedState(state: Record<string, unknown>): AmActionBuilder;
  putSessionProperty(key: string, value: string): AmActionBuilder;
  build(): unknown;
}

/**
 * State accumulated by nodes that already ran. `get` returns AM's own value
 * wrapper, so read it through `asString`/`asBoolean` rather than using it
 * directly.
 */
declare const nodeState: {
  get(key: string): AmStateValue | null;
  isDefined(key: string): boolean;
  putShared(key: string, value: unknown): void;
  putTransient(key: string, value: unknown): void;
  remove(key: string): void;
};

interface AmStateValue {
  asString(): string;
  asBoolean(): boolean;
  asInteger(): number;
  isNull(): boolean;
}

/** The realm the journey is running in, e.g. `/` or `/alpha`. */
declare const realm: string;

declare const requestHeaders: {
  get(name: string): string[] | null;
};

declare const logger: {
  error(message: string): void;
  warning(message: string): void;
  message(message: string): void;
  debug(message: string): void;
};

/** Secrets from AM's secret stores. Never inline a credential in a script. */
declare const secrets: {
  getGenericSecret(name: string): { getAsUtf8(): string } | null;
};
