// PingAM's scripted-decision-node bindings, evaluatorVersion 2.0.
//
// DELIBERATELY NARROW, AND EVERY MEMBER HERE HAS BEEN EXERCISED against a
// running PingAM. Do not add one you have not seen work: a plausible-looking
// declaration is worse than no declaration at all, because it type-checks and
// then fails for a real user in the middle of a journey.
//
// That is not a hypothetical. Two earlier versions of this file were written
// from what the API looked like it should be, and both compiled cleanly and
// broke at runtime:
//
//   TypeError: Cannot find function isNull in object normaluser
//     -- `nodeState.get` returns the RAW value. The asString()/isNull()
//        wrapper is the Java NodeState API, not the JavaScript binding.
//
//   TypeError: Cannot find function message in object ScriptedLoggerWrapper
//     -- the next-gen logger is SLF4J-shaped. `message`/`warning` are the
//        LEGACY (evaluatorVersion 1.0) names.
//
// These bindings are NOT the PingIDM ones: there is no `openidm`, no `request`
// and no `context`. That is why AM scripts are a separate TypeScript program
// (tsconfig.am.json) rather than another directory in the endpoint one.
//
// Managed file -- regenerated by `fo upgrade`.

/**
 * The outcome builder: how a scripted decision node says where to go next.
 * The outcome must be one the node declares, or the journey dead-ends.
 */
declare const action: {
  goTo(outcome: string): void;
};

/**
 * State accumulated by nodes that already ran.
 *
 * `get` returns the RAW value -- possibly a Java String rather than a
 * JavaScript one, and null when absent -- so coerce it instead of calling
 * methods on it.
 */
declare const nodeState: {
  get(key: string): unknown;
  /** Carry a value to later nodes, and into the session. */
  putShared(key: string, value: unknown): void;
  /** Carry a value to later nodes only; never persisted. */
  putTransient(key: string, value: unknown): void;
};

/**
 * Verified against `ScriptedLoggerWrapper` in scripting-api-8.1.1.jar. This is
 * the SLF4J shape, not the legacy `message`/`warning` one.
 */
declare const logger: {
  error(message: string): void;
  warn(message: string): void;
  info(message: string): void;
  debug(message: string): void;
  trace(message: string): void;
  isErrorEnabled(): boolean;
  isWarnEnabled(): boolean;
  isInfoEnabled(): boolean;
  isDebugEnabled(): boolean;
  isTraceEnabled(): boolean;
};
