// The PingAM scripted-node authoring surface.
//
// Same build pipeline as the IDM endpoints -- esbuild to one bundle, Babel down
// to ES5, the same runtime bans -- but a different target and different
// globals. The emitted artefact is an amster `Scripts` entity under
// platform/amster/config/, so an AM script deploys through tier 2 (`fo
// amster`) rather than by syncing a file into a pod.
//
// Managed file -- regenerated by `fo upgrade`.

/**
 * Where in PingAM the script runs. Only the contexts we have a `.d.ts` for are
 * listed: widening this without also describing that context's bindings would
 * let code type-check against globals that are not actually there.
 */
export type AmScriptContext = "SCRIPTED_DECISION_NODE";

export interface AmScriptSpec {
  /** Display name in the AM console. Must match the source file name. */
  name: string;
  context: AmScriptContext;
  description?: string;
  /**
   * The declared outcomes of a scripted decision node. AM needs these to draw
   * the node's exits in the journey editor, and a `goTo` naming an outcome not
   * listed here dead-ends at runtime.
   */
  outcomes: readonly string[];
  main: () => void;
}

export interface AmScriptDefinition extends AmScriptSpec {
  readonly kind: "am-script";
}

export interface AmScriptMain {
  (): void;
  readonly definition: AmScriptDefinition;
}

/**
 * Declare a PingAM script. The default export of every file in
 * `src/scripts/` must be the value this returns.
 */
export function defineAmScript(spec: AmScriptSpec): AmScriptMain {
  if (spec.outcomes.length === 0) {
    throw new Error(spec.name + ": a scripted decision node needs an outcome");
  }
  const main = function (): void {
    spec.main();
  } as { (): void; definition: AmScriptDefinition };
  main.definition = { ...spec, kind: "am-script" };
  return main as AmScriptMain;
}
