// The PingAM scripted-node authoring surface.
//
// Same build pipeline as the IDM endpoints -- esbuild to one bundle, Babel down
// to ES5, the same runtime bans -- but a different target and different
// globals. The emitted artefact is an amster `Scripts` entity under
// platform/amster/config/, so an AM script deploys through tier 2 (`fo
// amster`) rather than by syncing a file into a pod.
//
// Managed file -- regenerated by `fo upgrade`.

/**
 * Where in PingAM the script runs. Only the contexts we have a `.d.ts` for are
 * listed: widening this without also describing that context's bindings would
 * let code type-check against globals that are not actually there.
 */
export type AmScriptContext = "SCRIPTED_DECISION_NODE";

/**
 * The declared exits of a scripted decision node -- at least one, and written
 * as a literal so the type system knows their names.
 *
 * Spreading an array in (`outcomes: [...names]`) is rejected on purpose: AM
 * needs the exits to draw the node in the journey editor, so they have to be
 * knowable without running anything.
 */
export type AmOutcomes = readonly [string, ...string[]];

/**
 * How a scripted decision node says where to go next, narrowed to the outcomes
 * the script declares.
 *
 * `main` is HANDED one of these. That is the whole point: `goTo` naming an
 * outcome the node does not declare dead-ends the journey in front of a real
 * user, and AM reports nothing at deploy time -- so the typo has to be a
 * compile error or it is a production incident.
 *
 * Assignability alone does not hold this. TypeScript compares METHOD parameters
 * bivariantly even under `strictFunctionTypes`, so an author who annotates the
 * callback parameter as `{ goTo(v: string): void }` gets the wide signature
 * back, and no variance trick on THIS interface refuses it -- the bivariance
 * comes from the annotation's own declaration. `MainMustNotWiden` below closes
 * it by inspecting the annotation instead of relying on assignability.
 */
export interface AmAction<Outcome extends string> {
  goTo(outcome: Outcome): void;
}

/**
 * What `outcomes` degrades to when the literal types are lost.
 *
 * `outcomes: ["high", ...names]` with `names: string[]` infers
 * `readonly ["high", ...string[]]`, whose member type is plain `string` -- and
 * then `goTo` accepts any string at all, silently, while looking exactly like
 * a checked call. The constraint cannot live on `outcomes` itself: a
 * conditional type there stops being an inference site, so `Outcomes` would
 * never be inferred. It is intersected onto the whole spec instead, which
 * leaves inference alone and fails assignability afterwards.
 */
export type OutcomesMustBeLiterals<Outcomes extends AmOutcomes> =
  string extends Outcomes[number]
    ? {
        /**
         * `outcomes` has to be a literal array. Spreading a `string[]` into it
         * loses the names, and `goTo` then accepts anything.
         */
        readonly __outcomesAreNotStringLiterals: never;
      }
    : unknown;

type FirstParameter<F> =
  F extends (value: infer A, ...rest: never[]) => unknown ? A : never;

type GoToOutcome<A> = A extends { goTo(outcome: infer O): void } ? O : never;

/** `any` absorbs everything, including a comparison meant to reject it. */
type IsAny<T> = 0 extends 1 & T ? true : false;

/**
 * What an ANNOTATED `main` parameter degrades to.
 *
 * Leaving `main`'s parameter to inference is the whole mechanism, and an
 * explicit annotation replaces it. Assignability cannot refuse a wider one --
 * `{ goTo(outcome: string): void }` is accepted because method parameters
 * compare bivariantly, and that bivariance is a property of the ANNOTATION, so
 * nothing done to `AmAction` reaches it.
 *
 * So `Main` is inferred separately and the outcome type the author's own
 * annotation admits is read back out of it. Anything it accepts beyond the
 * declared outcomes -- `string`, `any`, or one extra literal -- fails here. An
 * exact or narrower annotation still passes, because restricting yourself to
 * fewer exits is sound.
 */
export type MainMustNotWiden<Outcomes extends AmOutcomes, Main> =
  IsAny<GoToOutcome<FirstParameter<Main>>> extends true
    ? { readonly __mainAcceptsUndeclaredOutcome: never }
    : Exclude<GoToOutcome<FirstParameter<Main>>, Outcomes[number]> extends never
      ? unknown
      : { readonly __mainAcceptsUndeclaredOutcome: never };

export interface AmScriptSpec<Outcomes extends AmOutcomes, Main> {
  /** Display name in the AM console. Must match the source file name. */
  name: string;
  context: AmScriptContext;
  description?: string;
  /**
   * The declared outcomes of a scripted decision node. AM needs these to draw
   * the node's exits in the journey editor, and they are what `goTo` is
   * checked against.
   */
  outcomes: Outcomes;
  main: Main & ((action: AmAction<Outcomes[number]>) => void);
}

/**
 * What `fo build` writes into the amster entity: the spec's metadata, without
 * the closure. Deliberately not `AmScriptSpec` itself -- a definition that
 * carried `main` would have to name the outcome type to stay assignable, and
 * the build reads this generically.
 */
export interface AmScriptDefinition {
  readonly kind: "am-script";
  readonly name: string;
  readonly context: AmScriptContext;
  readonly description?: string;
  readonly outcomes: AmOutcomes;
}

export interface AmScriptMain {
  (): void;
  readonly definition: AmScriptDefinition;
}

/**
 * Declare a PingAM script. The default export of every file in
 * `src/scripts/` must be the value this returns.
 *
 * ```ts
 * export default defineAmScript({
 *   name: "risk-check",
 *   context: "SCRIPTED_DECISION_NODE",
 *   outcomes: ["high", "low"],
 *   main: (action) => {
 *     action.goTo("hihg"); // compile error: not a declared outcome
 *   },
 * });
 * ```
 */
export function defineAmScript<const Outcomes extends AmOutcomes, const Main>(
  spec: AmScriptSpec<Outcomes, Main> &
    OutcomesMustBeLiterals<Outcomes> &
    MainMustNotWiden<Outcomes, Main>,
): AmScriptMain {
  // `AmOutcomes` already rejects an empty literal, but the emitted JS has no
  // types and this is the check that would have caught it.
  if (spec.outcomes.length === 0) {
    throw new Error(spec.name + ": a scripted decision node needs an outcome");
  }
  const main = function (): void {
    // The one place the raw global is reached for. `action` is declared with
    // no usable outcome precisely so that every other reference to it fails to
    // compile and authors go through the parameter instead.
    (spec as AmScriptSpec<Outcomes, Main>).main(
      action as AmAction<Outcomes[number]>,
    );
  } as { (): void; definition: AmScriptDefinition };
  main.definition = {
    kind: "am-script",
    name: spec.name,
    context: spec.context,
    outcomes: spec.outcomes,
    ...(spec.description === undefined ? {} : { description: spec.description }),
  };
  return main as AmScriptMain;
}
