// Builtins the script engine HAS that the pinned `lib` does not declare.
//
// The tsconfigs pin `lib` to whole TypeScript lib entries, which is the right
// default: it is one line per feature era and it cannot drift member by
// member. But an entry is all-or-nothing, and two of them are a partial match
// for this engine - so declaring the verified members here is the only way to
// use them without also permitting the ones that are absent.
//
// EVERY MEMBER HERE WAS PROBED ON A RUNNING STACK, in both PingAM's
// scripted-decision-node engine and PingIDM's endpoint engine, which are the
// same Rhino build and agreed on all 95 probes. See spike/ENGINE-SURFACE.md
// for the method and the full result. Do not add a member you have not seen
// exist: `useBuiltIns: false` means Babel emits no polyfill, so a declaration
// that is wrong here type-checks and then throws in production.
//
// Managed file -- regenerated by `fo upgrade`.

interface ObjectConstructor {
  /**
   * ES2017. Present, but `lib: ["ES2017.Object"]` would also declare
   * `getOwnPropertyDescriptors`, which this engine does NOT have.
   */
  entries<T>(o: { [s: string]: T } | ArrayLike<T>): Array<[string, T]>;
  entries(o: object): Array<[string, unknown]>;
  /** ES2017. Same reason as `entries`. */
  values<T>(o: { [s: string]: T } | ArrayLike<T>): T[];
  values(o: object): unknown[];
}
