// CREST error mapping.
//
// *** NEVER SUBCLASS `Error` IN THIS PROJECT. ***
//
// The bundle is downlevelled to ES5 by Babel, and `Reflect` is `undefined` on
// the IDM script engine (probed 2026-08-13). Babel's `_wrapNativeSuper` helper
// falls back off `Reflect.construct`, so for `class Fault extends Error`:
//   new Fault("x") instanceof Error === true    // survives
//   new Fault("x") instanceof Fault === false   // DOES NOT
// `.name` and `.message` survive, but the subclass identity does not — so any
// `instanceof`-based error discrimination silently classifies every fault as
// "unknown" and returns 500. Plain class-to-class inheritance is unaffected;
// only native `Error` is broken.
//
// The framework therefore uses a TAGGED PLAIN OBJECT and duck-types it. The
// tag never crosses the IDM boundary: `toCrestResponse` projects the private
// fault onto the three caller-facing fields before the router throws it.
//
// Managed file — regenerated by `aic workspace update`.

/** Marker property that identifies a framework fault without `instanceof`. */
export const FAULT_TAG = "__aicCrestFault";

/** A CREST error: `{ code, reason, message, detail }`. */
export interface CrestFault {
  readonly __aicCrestFault: true;
  /** HTTP status code. */
  code: number;
  /** HTTP reason phrase, e.g. `Bad Request`. */
  reason: string;
  /** Safe, caller-facing message. Never put credentials or internals here. */
  message: string;
  /** Optional structured detail (validation issues, allowed methods, …). */
  detail?: unknown;
}

/** The exact object thrown to IDM and rendered as the HTTP error response. */
export interface CrestErrorResponse {
  code: number;
  message: string;
  detail: unknown;
}

const REASONS: Record<number, string> = {
  400: "Bad Request",
  401: "Unauthorized",
  403: "Forbidden",
  404: "Not Found",
  405: "Method Not Allowed",
  409: "Conflict",
  412: "Precondition Failed",
  500: "Internal Server Error",
  501: "Not Implemented",
  503: "Service Unavailable",
};

/** The HTTP reason phrase for `code`, falling back to a generic label. */
export function reasonFor(code: number): string {
  const reason = REASONS[code];
  if (reason !== undefined) {
    return reason;
  }
  return code >= 500 ? "Server Error" : "Client Error";
}

/** Build a fault. Throw it directly — IDM renders it as the error response. */
export function fault(
  code: number,
  message: string,
  detail?: unknown
): CrestFault {
  const built: CrestFault = {
    __aicCrestFault: true,
    code,
    reason: reasonFor(code),
    message,
  };
  if (detail !== undefined) {
    built.detail = detail;
  }
  return built;
}

export const badRequest = (message: string, detail?: unknown): CrestFault =>
  fault(400, message, detail);
export const unauthorized = (message: string, detail?: unknown): CrestFault =>
  fault(401, message, detail);
export const forbidden = (message: string, detail?: unknown): CrestFault =>
  fault(403, message, detail);
export const notFound = (message: string, detail?: unknown): CrestFault =>
  fault(404, message, detail);
export const methodNotAllowed = (
  message: string,
  detail?: unknown
): CrestFault => fault(405, message, detail);
export const conflict = (message: string, detail?: unknown): CrestFault =>
  fault(409, message, detail);
export const internalError = (message: string, detail?: unknown): CrestFault =>
  fault(500, message, detail);

/** Duck-typed fault check — deliberately not `instanceof` (see file header). */
export function isFault(value: unknown): value is CrestFault {
  return (
    typeof value === "object" &&
    value !== null &&
    (value as Record<string, unknown>)[FAULT_TAG] === true
  );
}

/**
 * What a non-fault throwable looked like, for the server-side log only. Never
 * returned to the caller: an arbitrary throw can carry a stack trace, an
 * upstream URL, or a credential.
 */
export function describeThrowable(value: unknown): string {
  if (typeof value === "string") {
    return value;
  }
  if (typeof value === "object" && value !== null) {
    const record = value as Record<string, unknown>;
    const name = typeof record["name"] === "string" ? record["name"] : "Error";
    const message =
      typeof record["message"] === "string" ? record["message"] : "";
    return message === "" ? name : name + ": " + message;
  }
  return String(value);
}

/**
 * Normalise anything thrown into a fault safe to send back.
 *
 * A framework fault passes through. A thrown `{ code, message }` from an
 * `openidm.*` call keeps its status (so a downstream 404 stays a 404) but not
 * its message. Anything else becomes an opaque 500 — the real detail goes to
 * the log, not to the caller.
 */
export function toCrestFault(value: unknown): CrestFault {
  if (isFault(value)) {
    return value;
  }
  if (typeof value === "object" && value !== null) {
    const code = (value as Record<string, unknown>)["code"];
    if (typeof code === "number" && code >= 400 && code < 600) {
      return fault(code, reasonFor(code));
    }
  }
  return fault(500, "Internal error");
}

/** Remove internal discrimination and reason fields before crossing the wire. */
export function toCrestResponse(fault: CrestFault): CrestErrorResponse {
  return { code: fault.code, message: fault.message, detail: fault.detail };
}
