// The IDM script-engine globals, declared for this module-based project.
//
// `request` / `context` / `logger` are read only by the emitted entry shim —
// framework and endpoint code takes them as parameters so it stays unit-testable
// in plain node. `openidm` and `identityServer` are different: nothing injects
// them, so endpoint code calls them as globals and they need full signatures.
//
// The managed-object machinery below mirrors the ambient `.cjs` workspace's
// `idm/types/common.d.ts` deliberately, so that one mental model covers both
// surfaces. It keys on `ManagedObjects`, which `src/generated/managed.ts`
// augments from the tenant's schema.
//
// Ground truth: docs/api/10-managed-objects.md (record shape, `fields` syntax,
// query parameters), docs/api/11-idm-endpoints.md, docs/typescript-endpoints.md.
//
// Managed file — regenerated by `aic workspace update`.

import type {
  CrestRequest,
  CrestResource,
  IdmCallContext,
  IdmLogger,
  PatchOperation,
} from "./types.ts";

declare global {
  const request: CrestRequest;
  const context: IdmCallContext;
  const logger: IdmLogger;

  /**
   * Collection path (`managed/alpha_user`) -> the object's interface, for this
   * tenant's managed schema.
   *
   * Declared EMPTY here and augmented by `src/generated/managed.ts`, which
   * `aic workspace update` writes from `GET /openidm/config/managed`. Ambient
   * `.d.ts` files are invisible inside a module graph, so that generated file
   * is a real module carrying a `declare global` block — the augmentation
   * applies because `tsconfig.json` includes `src/**\/*`, not because anything
   * imports it.
   *
   * When the file is absent — `aic workspace init` ran with no reachable agent,
   * so the schema fetch was skipped — this stays empty and every conditional
   * below resolves to `never`. That is a PARTIAL degradation, not a silent one,
   * and the difference is worth knowing before you go looking for the cause:
   *
   * - a call still compiles, handing back {@link CrestResource}, whose members
   *   are index-only — `record["userName"]`, never `record.userName`;
   * - a `fields` argument on a `managed/…` path is REJECTED, because there is no
   *   schema to check it against ({@link FieldsArg});
   * - `ManagedName` is `never`, so anything annotated with it fails.
   *
   * All three clear up the moment `aic workspace update` runs with the agent
   * unlocked. Code written against the tenant's types — the seeded
   * `example-managed-users.ts`, for one — does not type-check until it does.
   */
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type -- the augmentation seam; see above.
  interface ManagedObjects {}

  type ManagedName = keyof ManagedObjects & string;

  /**
   * A member of a `fields` argument: a schema property, `*`, or a relationship
   * / `_meta` path such as `manager/displayName` or `_meta/lastChanged` (the
   * path and `*` syntax are verified live — docs/api/10-managed-objects.md).
   */
  type ManagedField<T> =
    | (keyof T & string)
    | "*"
    | `${(keyof T & string) | "_meta"}/${string}`
    | "_meta";

  /** Collection path (`managed/<obj>`) -> object interface, else `never`. */
  type ManagedCollectionOf<R extends string> = R extends keyof ManagedObjects
    ? ManagedObjects[R]
    : never;

  /** Record path (`managed/<obj>/<id>`) -> object interface, else `never`. */
  type ManagedRecordOf<R extends string> =
    R extends `managed/${infer N}/${string}`
      ? `managed/${N}` extends keyof ManagedObjects
        ? ManagedObjects[`managed/${N}`]
        : never
      : never;

  /**
   * `fields`: checked against the schema for a known managed path, REJECTED
   * for an unknown `managed/…` path (there is nothing to check it against —
   * re-run `aic workspace update`), free-form for anything else.
   *
   * `readonly` so a `const` type parameter can capture the literal members —
   * that inference is what makes {@link Projected} possible.
   */
  type FieldsArg<T, R extends string> = [T] extends [never]
    ? R extends `managed/${string}`
      ? never
      : readonly string[]
    : readonly ManagedField<T>[];

  /**
   * What a `parent/child` selector hands back for `parent`: the relationship
   * REFERENCE envelope plus the requested members of the target (verified
   * 2026-08-17 with `_meta/lastChanged`, which returned `_ref`,
   * `_refResourceCollection`, `_refResourceId`, `_refResourceRev`, the target's
   * own `_id`/`_rev`, and `lastChanged`).
   *
   * The target's schema is not recorded anywhere these types can reach — a
   * generated interface says `manager?: RelationshipRef`, not which object it
   * points at — so requested members stay index-only. `expanded["lastChanged"]`
   * rather than `expanded.lastChanged` is the friction that says so.
   */
  interface RelationshipExpansion {
    _id?: string;
    _rev?: string;
    _ref?: string;
    _refResourceCollection?: string;
    _refResourceId?: string;
    _refResourceRev?: string;
    _refProperties?: { _id?: string; _rev?: string };
    [member: string]: unknown;
  }

  /** The `parent` of every requested `parent/child` path. */
  type PathParentOf<F extends string> = F extends `${infer P}/${string}`
    ? P
    : never;

  /**
   * `_meta` is a relationship in its own right (to `managed/<realm>usermeta`),
   * so asking for it adds an expansion rather than a declared property.
   */
  type MetaMemberOf<F extends string> = [
    Extract<F, "_meta" | `_meta/${string}`>,
  ] extends [never]
    ? unknown
    : { _meta: RelationshipExpansion | null };

  /**
   * A relationship's CARDINALITY decides the projected shape (verified
   * 2026-08-17): single-valued comes back as the expansion or `null` when unset,
   * multi-valued as an array — `[]` when unset, never `null`. Typing a
   * single-valued one as always present cost a live 500 on the first request
   * against a user with no manager, which every gate had passed.
   */
  type ExpansionOf<D> = NonNullable<D> extends readonly unknown[]
    ? RelationshipExpansion[]
    : RelationshipExpansion | null;

  /**
   * A requested member as the store actually returns it: the key is ALWAYS
   * PRESENT, holding `null` when the record has no value for it (verified
   * 2026-08-18 with a `fields` read of a user lacking `telephoneNumber`,
   * `description` and `manager` — all three came back `null`, not absent).
   *
   * So a projected member is a REQUIRED key with a NULLABLE value — but only where
   * the schema leaves the property optional, since a schema-required property
   * always has a value. `Pick` was wrong twice here: it kept the `?`, implying the
   * key might be missing, and it kept the value non-null, which is the shape that
   * cost a live 500 on `manager`.
   */
  type SelectedMembers<T, F extends string> = {
    [K in Extract<F, keyof T>]-?: undefined extends T[K]
      ? NonNullable<T[K]> | null
      : T[K];
  };

  /**
   * The record shape a `fields` selector actually yields.
   *
   * `_id` and `_rev` come back whatever you asked for — even `fields: ["_id"]`
   * returns both (verified 2026-08-17, docs/api/10-managed-objects.md) — so the
   * projection always keeps the {@link StoredRecord} guarantee. A relationship
   * path upgrades the parent key from its declared `RelationshipRef` to the
   * expansion above.
   *
   * A list that is not made of LITERAL types cannot be projected: a
   * `ManagedField<T>[]` variable widens to the whole record rather than
   * narrowing to nothing, so losing the inference costs precision and never
   * correctness. (A plain `string[]` is rejected outright — the constraint wants
   * schema members, whatever the projection could do with them.)
   */
  type Projected<T, F extends string> = string extends F
    ? StoredRecord<T>
    : StoredRecord<
        ("*" extends F ? T : SelectedMembers<T, F>) & {
          [K in Extract<PathParentOf<F>, keyof T>]: ExpansionOf<T[K]>;
        } & MetaMemberOf<F>
      >;

  /**
   * What `openidm.query` hands back.
   *
   * NOT the shape an endpoint may RETURN: `remainingPagedResults` was absent
   * from every observed `openidm.query` result (verified 2026-08-17) while IDM
   * REQUIRES it on a query handler's return value, rejecting anything else with
   * `Script returned unexpected query result structure`. So passing this
   * straight back out of a handler fails at runtime — build the response with
   * `queryResult(rows)`, which fills the envelope. The distinct type is what
   * makes that a compile error instead.
   */
  interface OpenIdmQueryResult<T> {
    result: T[];
    resultCount: number;
    pagedResultsCookie: string | null;
    totalPagedResults: number;
    totalPagedResultsPolicy: string;
    /** Never observed on a script-side query result; see above. */
    remainingPagedResults?: number;
  }

  /** Write payloads are partial: a patch-like update need not carry every key. */
  type ContentArg<T> = [T] extends [never]
    ? Record<string, unknown>
    : Partial<T>;

  /**
   * The result of a call whose path did not resolve to a managed object. The
   * ambient workspace widens to `any` here; this project stays strict, so an
   * unknown path hands back the generic CREST resource shape instead.
   */
  type RecordResult<T> = [T] extends [never] ? CrestResource : T;

  /**
   * A record the store hands back always carries `_id` and `_rev`: a managed
   * object instance is "`_id` and `_rev` plus its declared properties"
   * (docs/api/10-managed-objects.md). The generated interfaces still leave both
   * optional, because the same interface types an onCreate hook's draft object,
   * which has neither yet.
   */
  type StoredRecord<T> = T & { _id: string; _rev: string };

  /**
   * Parameters a managed-object query honours. `_queryFilter` stays required —
   * IDM rejects a query without one. `_fields`, `_sortKeys` and the paging
   * cursor are all exercised live in docs/api/10-managed-objects.md; offset
   * paging is deliberately not named, because deep offsets can skip or
   * duplicate records and the cursor is the supported walk.
   *
   * The index signature is deliberate: an exact object type here is precisely
   * why `_fields` was once a type error rather than a supported parameter. A
   * misspelled `_queryFilter` is still caught by the required key.
   */
  interface QueryParams {
    _queryFilter: string;
    /**
     * Comma-joined field list. Works, but PREFER the third `fields` argument:
     * this is one opaque string, so the result type cannot be projected from it
     * and every declared property stays possibly-absent. Naming it here is what
     * makes the row type `Partial<…>` on the two-argument overload.
     */
    _fields?: string;
    _sortKeys?: string;
    _pageSize?: number;
    /**
     * OMIT this key to start at the first page — do NOT pass `null`. IDM
     * rejects an explicit null with
     * `JsonValueException: /_pagedResultsCookie: Expecting a value`
     * (verified 2026-08-18), which surfaces as an opaque 500. That is why
     * neither this key nor the index signature admits `null`: the type used
     * to, and a `cursor ?? null` in a handler was a live 500.
     */
    _pagedResultsCookie?: string;
    [param: string]: string | number | undefined;
  }

  /**
   * IDM's CREST router binding.
   *
   * One generic signature per verb with conditional results, rather than a
   * per-object overload set: a field typo then reports against the offending
   * element, with spelling suggestions, instead of "no overload matches".
   */
  interface OpenIdm {
    read<R extends `${ManagedName}/${string}` | (string & {})>(
      path: R,
      params?: Record<string, string> | null
    ): [ManagedRecordOf<R>] extends [never]
      ? CrestResource | null
      : StoredRecord<ManagedRecordOf<R>> | null;
    /**
     * Restricting the fields narrows the RESULT TYPE to what you asked for, and
     * keeps `_id`/`_rev`, which come back regardless (verified 2026-08-17).
     */
    read<
      R extends `${ManagedName}/${string}` | (string & {}),
      const F extends FieldsArg<ManagedRecordOf<R>, R>,
    >(
      path: R,
      params: Record<string, string> | null | undefined,
      fields: F
    ): [ManagedRecordOf<R>] extends [never]
      ? CrestResource | null
      : Projected<ManagedRecordOf<R>, F[number] & string> | null;

    /**
     * Rows carry `_id`/`_rev` plus every declared property — unless `params`
     * names `_fields`, which trims them opaquely; see {@link QueryParams}.
     */
    query<R extends ManagedName | (string & {}), P extends QueryParams>(
      path: R,
      params: P
    ): OpenIdmQueryResult<
      [ManagedCollectionOf<R>] extends [never]
        ? CrestResource
        : P extends { _fields: string }
          ? StoredRecord<Partial<ManagedCollectionOf<R>>>
          : StoredRecord<ManagedCollectionOf<R>>
    >;
    /** Same projection as the three-argument `read`, applied to every row. */
    query<
      R extends ManagedName | (string & {}),
      const F extends FieldsArg<ManagedCollectionOf<R>, R>,
    >(
      path: R,
      params: QueryParams,
      fields: F
    ): OpenIdmQueryResult<
      [ManagedCollectionOf<R>] extends [never]
        ? CrestResource
        : Projected<ManagedCollectionOf<R>, F[number] & string>
    >;

    create<R extends ManagedName | (string & {})>(
      path: R,
      newResourceId: string | null,
      content: ContentArg<ManagedCollectionOf<R>>,
      params?: Record<string, string> | null
    ): RecordResult<ManagedCollectionOf<R>>;

    update<R extends `${ManagedName}/${string}` | (string & {})>(
      path: R,
      revision: string | null,
      content: ContentArg<ManagedRecordOf<R>>,
      params?: Record<string, string> | null
    ): RecordResult<ManagedRecordOf<R>>;

    patch<R extends `${ManagedName}/${string}` | (string & {})>(
      path: R,
      revision: string | null,
      operations: PatchOperation[],
      params?: Record<string, string> | null
    ): RecordResult<ManagedRecordOf<R>>;

    delete<R extends `${ManagedName}/${string}` | (string & {})>(
      path: R,
      revision: string | null,
      params?: Record<string, string> | null
    ): RecordResult<ManagedRecordOf<R>>;

    /** Named actions are untyped: the payload and result are per-action. */
    action(
      path: string,
      actionName: string,
      content?: Record<string, unknown> | null,
      params?: Record<string, string> | null
    ): unknown;
  }

  const openidm: OpenIdm;

  /** ESV / boot-property lookup. Returns `null` for a missing property. */
  const identityServer: {
    getProperty(
      name: string,
      defaultValue?: string,
      substitute?: boolean
    ): string | null;
  };
}
