// The endpoint-authoring surface. Endpoints import from here and nowhere else
// inside `framework/`.
//
// Managed file — regenerated by `aic workspace update`.

export {
  defineEndpoint,
  parsePath,
  queryRoute,
  route,
  routeLabel,
  splitResourcePath,
  type DispatchOptions,
  type EndpointDefinition,
  type EndpointMain,
  type EndpointSpec,
  type PathSegment,
  type ResultFor,
  type RouteDefinition,
  type RouteInput,
  type RouteSpec,
  type RouteSpecBase,
  type QueryRouteSpec,
} from "./router.ts";

export {
  badRequest,
  conflict,
  describeThrowable,
  fault,
  forbidden,
  internalError,
  isFault,
  methodNotAllowed,
  notFound,
  reasonFor,
  toCrestFault,
  toCrestResponse,
  unauthorized,
  FAULT_TAG,
  type CrestErrorResponse,
  type CrestFault,
} from "./errors.ts";

export {
  createRequestLogger,
  describeCaller,
  nullLogger,
  renderFields,
  type LogFields,
  type RequestLogger,
} from "./logging.ts";

export {
  assignPathKeys,
  operationId,
  queryResultSchema,
  routeUrl,
  toOpenApi,
  type OpenApiOptions,
} from "./openapi.ts";

export type {
  CrestMethod,
  QueryResultOptions,
  CrestQueryResult,
  CrestRequest,
  CrestRequestBase,
  CrestResource,
  IdmCallContext,
  IdmLogger,
  JavaSet,
  PatchOperation,
  QueryPage,
} from "./types.ts";

export { forwardQuery, queryResult } from "./types.ts";

export type {
  Infer,
  InferObject,
  InferShape,
  Issue,
  JsonSchema,
  ParseMode,
  Shape,
  Validator,
} from "./validate.ts";

/**
 * The validator combinators, namespaced so an endpoint reads
 * `v.integer({ min: 1, max: 100 })` rather than importing a dozen names.
 */
export * as v from "./validate.ts";
