// Structured logging over the IDM `logger` binding.
//
// The binding takes a message string, so "structured" here means a stable,
// greppable `key=value` rendering rather than a JSON sink. Every line carries
// the endpoint, the matched route and a correlation id, so one request's lines
// can be pulled out of `aic logs search` with a single term.
//
// SAFETY (docs/api/11-idm-endpoints.md): never log the whole `context`, never
// log `context.http.headers` (it carries the bearer `Authorization` header),
// and never log `context.oauth2.token` or `context.oauth2.rawInfo.sessionToken`.
// `describeCaller` below is an explicit allowlist projection, which is the only
// sanctioned way to get caller identity into a log line. `redact` is a second
// line of defence over field names, not a substitute for that allowlist.
//
// Managed file — regenerated by `aic workspace update`.

import type { IdmCallContext, IdmLogger } from "./types.ts";

export type LogFields = Record<string, unknown>;

export interface RequestLogger {
  debug(message: string, fields?: LogFields): void;
  info(message: string, fields?: LogFields): void;
  warn(message: string, fields?: LogFields): void;
  error(message: string, fields?: LogFields): void;
  /** A logger carrying extra fields on every line. */
  child(fields: LogFields): RequestLogger;
}

/**
 * Field names whose values are never rendered. Matched case-insensitively as a
 * substring, so `Authorization`, `x-auth-token` and `sessionToken` all hit.
 */
const REDACTED_KEY_PATTERN =
  /(authorization|password|secret|token|credential|cookie|assertion|bearer|jwk|private)/i;

/** Structures we refuse to render at all, however they were named. */
const BANNED_KEYS = /^(context|headers|http|oauth2|security|request)$/i;

const MAX_STRING = 200;
const MAX_DEPTH = 3;
const MAX_ITEMS = 20;

function quote(value: string): string {
  const clipped =
    value.length > MAX_STRING ? value.slice(0, MAX_STRING) + "…" : value;
  const escaped = clipped.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  return /[\s"=]/.test(escaped) ? '"' + escaped + '"' : escaped;
}

function renderValue(value: unknown, depth: number): string {
  if (value === null) {
    return "null";
  }
  if (value === undefined) {
    return "undefined";
  }
  if (typeof value === "string") {
    return quote(value);
  }
  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }
  if (depth >= MAX_DEPTH) {
    return "…";
  }
  if (Array.isArray(value)) {
    const shown = value.slice(0, MAX_ITEMS);
    const rest = value.length > shown.length ? ",…" : "";
    return (
      "[" +
      shown.map((item) => renderValue(item, depth + 1)).join(",") +
      rest +
      "]"
    );
  }
  if (typeof value === "object") {
    const source = value as Record<string, unknown>;
    const parts: string[] = [];
    for (const key of Object.keys(source).slice(0, MAX_ITEMS)) {
      parts.push(key + "=" + renderField(key, source[key], depth + 1));
    }
    return "{" + parts.join(" ") + "}";
  }
  return quote(String(value));
}

function renderField(key: string, value: unknown, depth: number): string {
  if (BANNED_KEYS.test(key) || REDACTED_KEY_PATTERN.test(key)) {
    return "[redacted]";
  }
  return renderValue(value, depth);
}

/** Render fields as `k=v` pairs, redacting by name. Exported for tests. */
export function renderFields(fields: LogFields): string {
  const parts: string[] = [];
  for (const key of Object.keys(fields)) {
    const value = fields[key];
    if (value === undefined) {
      continue;
    }
    parts.push(key + "=" + renderField(key, value, 0));
  }
  return parts.join(" ");
}

type Level = "debug" | "info" | "warn" | "error";

/**
 * Build a request logger. `base` fields are prepended to every line; the
 * message is rendered last as `msg=…` so the prefix stays column-stable.
 */
export function createRequestLogger(
  logger: IdmLogger,
  base: LogFields = {}
): RequestLogger {
  const emit = (level: Level, message: string, fields?: LogFields): void => {
    const merged: LogFields = { ...base, ...(fields ?? {}), msg: message };
    logger[level](renderFields(merged));
  };
  return {
    debug: (message, fields) => emit("debug", message, fields),
    info: (message, fields) => emit("info", message, fields),
    warn: (message, fields) => emit("warn", message, fields),
    error: (message, fields) => emit("error", message, fields),
    child: (fields) => createRequestLogger(logger, { ...base, ...fields }),
  };
}

/** A logger that discards everything — the default when none is supplied. */
export function nullLogger(): RequestLogger {
  const self: RequestLogger = {
    debug: () => undefined,
    info: () => undefined,
    warn: () => undefined,
    error: () => undefined,
    child: () => self,
  };
  return self;
}

/**
 * The ONLY sanctioned projection of `context` into a log line: an explicit
 * allowlist of non-credential fields. Serializing `context.security` directly
 * walks its inherited `parent` chain into `context.oauth2`, whose `token` and
 * `rawInfo.sessionToken` are credentials (docs/api/11-idm-endpoints.md).
 */
export function describeCaller(context: IdmCallContext): LogFields {
  const fields: LogFields = {};
  const security = context.security;
  if (security !== undefined) {
    fields["authId"] = security.authenticationId;
    if (security.authorization !== undefined) {
      fields["principal"] = security.authorization.id;
      fields["component"] = security.authorization.component;
    }
  }
  const http = context.http;
  if (http !== undefined) {
    fields["httpMethod"] = http.method;
    fields["httpPath"] = http.path;
  } else {
    // No HTTP request at the root of the chain — a scheduled job, recon, or
    // another internal trigger reached us (verified 2026-07-21).
    fields["origin"] = "internal";
  }
  return fields;
}
