// OpenAPI 3.1 generation from the route declarations.
//
// THE CREST WRINKLE. OpenAPI keys operations by (path, HTTP method), but CREST
// puts `create` and EVERY named action on `POST <path>?_action=<name>`, and
// `read` and `query` both on `GET <path>`. Several operations therefore
// collide on one (path, method) key, which OpenAPI cannot express.
//
// The approach taken here: keep ONE OpenAPI operation per declared route, and
// disambiguate with a `:<discriminator>` suffix (`/{widgetId}:retire`). Actions
// always use that stable RPC form; a colliding query moves to `:query`. Every
// synthetic operation carries the machine-readable truth:
//
//   x-crest-method  the CREST verb (`action`, `query`, …)
//   x-crest-action  the `?_action=` name, for action routes
//   x-crest-path    the REAL path to call, without the synthetic suffix
//
// plus a required `_action` (or `_queryFilter`) query parameter pinned by
// `enum`, so a generated client that ignores the extensions still sends the
// right query string. The alternative — one POST with a `oneOf` body and a
// free `_action` enum — type-checks nothing per action and loses the per-action
// scopes, which is the opposite of the point of this project.
//
// Managed file — regenerated by `aic workspace update`.

import {
  routeLabel,
  type EndpointDefinition,
  type RouteDefinition,
} from "./router.ts";
import type { JsonSchema, Shape } from "./validate.ts";

export interface OpenApiOptions {
  /** Server base URL, e.g. `https://tenant.forgeblocks.com`. */
  serverUrl?: string;
  title?: string;
}

const CREST_ERROR_SCHEMA: JsonSchema = {
  type: "object",
  description: "A CREST error response.",
  properties: {
    code: { type: "integer" },
    message: { type: "string" },
    detail: {},
  },
  required: ["code", "message", "detail"],
};

const HTTP_METHOD: Record<string, string> = {
  read: "get",
  query: "get",
  create: "post",
  action: "post",
  update: "put",
  patch: "patch",
  delete: "delete",
};

function parameterObjects(
  shape: Shape,
  location: "path" | "query" | "header"
): Record<string, unknown>[] {
  return Object.keys(shape).map((name) => {
    const validator = shape[name] as Shape[string];
    const parameter: Record<string, unknown> = {
      name,
      in: location,
      required: location === "path" ? true : !validator.isOptional,
      schema: validator.schema,
    };
    const encoding = validator.schema["x-aic-encoding"];
    if (encoding === "comma-separated") {
      parameter["style"] = "form";
      parameter["explode"] = false;
    }
    return parameter;
  });
}

/** The URL path of an endpoint's route, before any synthetic suffix. */
export function routeUrl(endpointName: string, route: RouteDefinition): string {
  const base = "/openidm/endpoint/" + endpointName;
  const suffix = route.path === "/" ? "" : route.path;
  return base + suffix;
}

/**
 * Assign a unique OpenAPI path key to every route.
 *
 * An `action` route ALWAYS gets the `:<action>` suffix, whether or not it
 * currently collides — otherwise adding a second action later would silently
 * move the first one's path key and break every generated client. A non-action
 * route keeps the real path unless it collides with another non-action route
 * on the same HTTP method, which only `read` + `query` on one path can do; the
 * `query` is the one that moves.
 */
export function assignPathKeys(
  definition: EndpointDefinition
): { route: RouteDefinition; key: string; synthetic: boolean }[] {
  const counts: Record<string, number> = {};
  for (const route of definition.routes) {
    if (route.action !== undefined) {
      continue;
    }
    const key =
      routeUrl(definition.name, route) + " " + HTTP_METHOD[route.method];
    counts[key] = (counts[key] ?? 0) + 1;
  }
  return definition.routes.map((route) => {
    const url = routeUrl(definition.name, route);
    if (route.action !== undefined) {
      return { route, key: url + ":" + route.action, synthetic: true };
    }
    const collides = (counts[url + " " + HTTP_METHOD[route.method]] ?? 0) > 1;
    if (collides && route.method === "query") {
      return { route, key: url + ":query", synthetic: true };
    }
    return { route, key: url, synthetic: false };
  });
}

function operationFor(
  definition: EndpointDefinition,
  route: RouteDefinition,
  synthetic: boolean
): Record<string, unknown> {
  const parameters: Record<string, unknown>[] = [
    ...parameterObjects(route.params, "path"),
    ...parameterObjects(route.query, "query"),
    ...parameterObjects({ ...definition.headers, ...route.headers }, "header"),
  ];
  if (route.method === "action" && route.action !== undefined) {
    parameters.push({
      name: "_action",
      in: "query",
      required: true,
      schema: { type: "string", enum: [route.action] },
    });
  }
  if (route.method === "create") {
    parameters.push({
      name: "_action",
      in: "query",
      required: true,
      schema: { type: "string", enum: ["create"] },
    });
  }
  if (route.method === "query") {
    parameters.push({
      name: "_queryFilter",
      in: "query",
      required: true,
      schema: { type: "string", default: "true" },
      description:
        "CREST requires a query predicate to route the call as a query.",
    });
  }

  const responses: Record<string, unknown> = {
    "200": {
      description: "Success",
      content: {
        "application/json": {
          // A query route declares ONE ROW; the envelope is added here so the
          // document and the handler's return type come from one declaration.
          schema: responseSchema(route),
        },
      },
    },
    "400": errorResponse("Request validation failed"),
    "401": errorResponse("Missing or invalid bearer token"),
    "403": errorResponse("Forbidden — IDM role or OAuth scope check failed"),
    "404": errorResponse("No such route or resource"),
    "405": errorResponse("Method not supported on this path"),
    "500": errorResponse("Unhandled failure"),
  };

  const operation: Record<string, unknown> = {
    operationId: operationId(definition.name, route),
    summary: route.summary ?? routeLabel(route),
    "x-crest-method": route.method,
    "x-crest-path": routeUrl(definition.name, route),
    responses,
  };
  if (route.description !== undefined) {
    operation["description"] = route.description;
  }
  if (synthetic) {
    operation["x-crest-synthetic-path-key"] = true;
  }
  if (route.action !== undefined) {
    operation["x-crest-action"] = route.action;
  }
  if (parameters.length > 0) {
    operation["parameters"] = parameters;
  }
  if (route.scopes.length > 0) {
    operation["x-required-scopes"] = route.scopes.slice();
    operation["security"] = [{ oauth2: route.scopes.slice() }];
  }
  const bodySchema =
    route.method === "patch" ? route.patches?.schema : route.body?.schema;
  if (bodySchema !== undefined) {
    operation["requestBody"] = {
      required: true,
      content: { "application/json": { schema: bodySchema } },
    };
  }
  return operation;
}

function errorResponse(description: string): Record<string, unknown> {
  return {
    description,
    content: {
      "application/json": {
        schema: { $ref: "#/components/schemas/CrestError" },
      },
    },
  };
}

/**
 * The 200 body schema for a route.
 *
 * The route carries the response VALIDATOR, so the schema is read off it here
 * rather than being declared separately — that is what keeps the document and
 * the handler's checked return type from drifting apart. A query route declares
 * one row and gets the envelope wrapped around it.
 */
function responseSchema(route: RouteDefinition): JsonSchema {
  if (route.response === undefined) {
    return {};
  }
  return route.method === "query"
    ? queryResultSchema(route.response.schema)
    : route.response.schema;
}

/** JSON Schema for the complete paging envelope IDM requires from queries. */
export function queryResultSchema(item: JsonSchema): JsonSchema {
  const paging: Record<string, JsonSchema> = {
    resultCount: { type: "integer" },
    pagedResultsCookie: { type: ["string", "null"] },
    totalPagedResults: { type: "integer" },
    remainingPagedResults: { type: "integer" },
    totalPagedResultsPolicy: { type: "string" },
  };
  return {
    type: "object",
    properties: { result: { type: "array", items: item }, ...paging },
    required: ["result", ...Object.keys(paging)],
  };
}

/** A stable, readable operation id: `widgets_action_retire`, `widgets_read_1`. */
export function operationId(
  endpointName: string,
  route: RouteDefinition
): string {
  const slug = endpointName.replace(/[^A-Za-z0-9]+/g, "_");
  const pathPart = route.path
    .replace(/[{}]/g, "")
    .replace(/[^A-Za-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  const parts = [slug, route.method];
  if (route.action !== undefined) {
    parts.push(route.action);
  }
  if (pathPart !== "") {
    parts.push(pathPart);
  }
  return parts.join("_");
}

/** Build the OpenAPI 3.1 document for one endpoint. */
export function toOpenApi(
  definition: EndpointDefinition,
  options: OpenApiOptions = {}
): Record<string, unknown> {
  const paths: Record<string, Record<string, unknown>> = {};
  for (const assigned of assignPathKeys(definition)) {
    const httpMethod = HTTP_METHOD[assigned.route.method] as string;
    const item = paths[assigned.key] ?? {};
    item[httpMethod] = operationFor(
      definition,
      assigned.route,
      assigned.synthetic
    );
    paths[assigned.key] = item;
  }

  const info: Record<string, unknown> = {
    title: options.title ?? definition.summary ?? definition.name,
    version: definition.version,
  };
  if (definition.description !== undefined) {
    info["description"] = definition.description;
  }

  const scopes: Record<string, string> = {};
  for (const route of definition.routes) {
    for (const scope of route.scopes) {
      scopes[scope] = "Required by one or more endpoint routes.";
    }
  }

  const document: Record<string, unknown> = {
    openapi: "3.1.0",
    jsonSchemaDialect: "https://json-schema.org/draft/2020-12/schema",
    info,
    paths,
    components: {
      schemas: { CrestError: CREST_ERROR_SCHEMA },
      securitySchemes: {
        oauth2: {
          type: "oauth2",
          flows: {
            clientCredentials: {
              tokenUrl: "/am/oauth2/access_token",
              scopes,
            },
          },
        },
      },
    },
    security: [{ oauth2: [] }],
  };
  if (options.serverUrl !== undefined) {
    document["servers"] = [{ url: options.serverUrl }];
  }
  return document;
}
