// Route declaration and dispatch.
//
// A route is keyed by (CREST method, sub-path pattern, action name). The
// sub-path is matched against `request.resourcePath` — the part of the URL
// below `/openidm/endpoint/<name>`, delivered verbatim and un-decoded (`""` at
// the root, `"a/b/c"` three levels down; probed 2026-08-13).
//
// Managed file — regenerated by `aic workspace update`.

import {
  badRequest,
  describeThrowable,
  forbidden,
  isFault,
  methodNotAllowed,
  notFound,
  toCrestFault,
  toCrestResponse,
  type CrestFault,
} from "./errors.ts";
import {
  createRequestLogger,
  describeCaller,
  type RequestLogger,
} from "./logging.ts";
import type {
  CrestMethod,
  CrestQueryResult,
  CrestRequest,
  IdmCallContext,
  IdmLogger,
  PatchOperation,
} from "./types.ts";
import {
  parseShape,
  type InferShape,
  type Issue,
  type Shape,
  type Validator,
} from "./validate.ts";

/** One piece of a sub-path pattern: a fixed segment or a named capture. */
export type PathSegment = { literal: string } | { param: string };

/** What the handler is handed. Every member is already validated. */
export interface RouteInput<
  P extends Shape,
  Q extends Shape,
  H extends Shape,
  B,
> {
  /** Captures from the sub-path pattern, URL-decoded then validated. */
  params: InferShape<P>;
  /** Non-`_`-prefixed query params, coerced per the declared validators. */
  query: InferShape<Q>;
  /** Declared headers, looked up case-insensitively. */
  headers: InferShape<H>;
  /** The validated request body (`undefined` when the route declares none). */
  body: B;
  /** CREST patch operations — only populated for the `patch` method. */
  patchOperations: PatchOperation[];
  /**
   * The client-supplied resource id on a `create`.
   *
   * A bare `PUT /openidm/endpoint/<name>/<id>` is a CREST **create** with
   * `newResourceId: "<id>"` and an EMPTY `resourcePath`, not an update
   * (probed 2026-08-13; the update route needs an `If-Match` header). So a
   * `create` route declared at `/` receives both call shapes, and this is how
   * it tells them apart.
   */
  newResourceId: string | null;
  /** The raw CREST request, for the fields the framework does not model. */
  request: CrestRequest;
  /** The CREST call chain. Never log it — use `describeCaller`. */
  context: IdmCallContext;
  /** Logger pre-bound to endpoint, route and correlation id. */
  log: RequestLogger;
  /** The `x-request-id` header when supplied, else a generated id. */
  correlationId: string;
}

/**
 * What a handler returns, for a caller who wants to name the type — a handler
 * written as a standalone function rather than inline.
 *
 * `R` is the route's `response` payload. A `query` handler MUST return a CREST
 * query result; anything else fails at runtime with `Script returned unexpected
 * query result structure` (verified 2026-06-04).
 */
export type ResultFor<M extends CrestMethod, R = unknown> = M extends "query"
  ? CrestQueryResult<R>
  : R;

/** Everything a route declares except the method and its handler. */
export interface RouteSpecBase<
  P extends Shape,
  Q extends Shape,
  H extends Shape,
  B,
  R,
> {
  /** Sub-path pattern: `"/"`, `"/{widgetId}"`, `"/widget/{widgetId}/summary"`. */
  path: string;
  /** Required for `method: "action"`; the `?_action=` name. */
  action?: string;
  summary?: string;
  description?: string;
  /** OAuth scopes the caller's token must carry, on top of IDM's own gates. */
  scopes?: readonly string[];
  params?: P;
  query?: Q;
  headers?: H;
  body?: Validator<B>;
  /** Validates `request.patchOperations` — only meaningful for `patch`. */
  patches?: Validator<PatchOperation[]>;
  /**
   * The success body's VALIDATOR — `v.object({ … })`, not its `.schema`.
   *
   * Passing the validator is what lets the handler's return type be checked
   * against the declared response; `.schema` is a plain `JsonSchema` value and
   * erases the type, which is how a declared response and a handler could
   * silently disagree. The OpenAPI generator reads `.schema` off this itself.
   *
   * For `method: "query"` this describes ONE ROW, not the envelope.
   *
   * Escape hatch for a body the validators cannot express:
   * `response: v.unknownValue()` leaves the handler unconstrained, explicitly.
   */
  response?: Validator<R>;
}

// `NoInfer` on the handler's return type below makes `response` the ONLY place
// `R` is inferred from. Without it a handler returning a wider object than the
// response declares wins the inference and `response` gets reported as the
// mismatch — blaming the declaration for the handler's error.
//
// KNOWN LIMIT. TypeScript will not use `R` as a contextual type here while the
// other generics are still being inferred, so a returned object literal does not
// get its literal types narrowed by the response. Overriding a member the
// response types as an enum needs `as const`:
//
//   return { ...widget, status: "retired" as const };
//
// Without it the literal widens to `string` and fails against the enum. The
// value is still CHECKED — `"retyred" as const` is an error — so this costs a
// keyword, not safety. Tried and rejected: a conditional `ResultFor<M, R>`
// return type, a discriminated union of spec types, and flattening the mapped
// type; each loses the narrowing the same way. Documented in
// docs/typescript-endpoints.md.

/**
 * A route declaration: the base above, plus a `method` and the handler that
 * method requires.
 *
 * A DISCRIMINATED UNION rather than one shape with a conditional
 * `ResultFor<M, R>` handler, because a conditional type over an un-inferred `M`
 * cannot serve as a contextual type. With one, `return { ...widget, status:
 * "retired" }` widened `status` to `string` and failed against the response's
 * own enum — the declaration would have been unusable for exactly the values it
 * describes. Narrowing on the `method` literal keeps the handler's expected
 * return type concrete, and keeps errors pointing at the offending property
 * instead of at a failed overload.
 *
 * A `query` handler must return the CREST envelope, so `response` there
 * describes ONE ROW and the framework wraps it — for the type here and for the
 * OpenAPI document in `openapi.ts`, from the single declaration.
 */
/**
 * A non-query route. `method: "query"` is not accepted here — use
 * {@link queryRoute}.
 */
export interface RouteSpec<
  P extends Shape,
  Q extends Shape,
  H extends Shape,
  B,
  R,
> extends RouteSpecBase<P, Q, H, B, R> {
  method: Exclude<CrestMethod, "query">;
  handler: (input: RouteInput<P, Q, H, B>) => NoInfer<R>;
}

/**
 * A query route. `response` describes ONE ROW; the handler returns the CREST
 * envelope around rows of that shape, and the OpenAPI generator wraps the same
 * declaration, so the document and the checked return type cannot disagree.
 */
export interface QueryRouteSpec<
  P extends Shape,
  Q extends Shape,
  H extends Shape,
  B,
  R,
> extends RouteSpecBase<P, Q, H, B, R> {
  handler: (input: RouteInput<P, Q, H, B>) => CrestQueryResult<NoInfer<R>>;
}

/** A route with its generics erased — what the endpoint and generator hold. */
export interface RouteDefinition {
  method: CrestMethod;
  path: string;
  segments: PathSegment[];
  action: string | undefined;
  summary: string | undefined;
  description: string | undefined;
  scopes: string[];
  params: Shape;
  query: Shape;
  headers: Shape;
  body: Validator<unknown> | undefined;
  patches: Validator<PatchOperation[]> | undefined;
  response: Validator<unknown> | undefined;
  run(input: RouteInput<Shape, Shape, Shape, unknown>): unknown;
}

/** Split `"/widget/{id}/summary"` into its segments. */
export function parsePath(path: string): PathSegment[] {
  return path
    .split("/")
    .filter((part) => part !== "")
    .map((part) => {
      const captured = /^\{(.+)\}$/.exec(part);
      return captured === null
        ? { literal: part }
        : { param: captured[1] as string };
    });
}

/**
 * Declare a non-query route. The generics are inferred from the validators, so
 * the handler sees `number` for an int query param, `"a" | "b"` for an enum, and
 * `string | undefined` for an optional — with no type annotations to keep in
 * step with the declaration. The return type comes from `response` the same way.
 *
 * Queries go through {@link queryRoute}. Two functions rather than one taking a
 * `method: "query"`: the handler's expected return type differs between them,
 * and expressing that in one signature needs either a conditional type or a
 * union, NEITHER of which TypeScript will use as a contextual type while it is
 * still inferring the other generics. Both cost the object literal its literal
 * types — `status: "retired"` widened to `string` and failed against the
 * response's own enum. Two concrete signatures keep the check honest and the
 * error message pointed at the offending property.
 */
export function route<
  P extends Shape = Record<never, never>,
  Q extends Shape = Record<never, never>,
  H extends Shape = Record<never, never>,
  B = undefined,
  R = unknown,
>(spec: RouteSpec<P, Q, H, B, R>): RouteDefinition {
  return build(spec.method, spec);
}

/**
 * Declare a query route. `response` describes ONE ROW; the handler returns
 * `queryResult(rows)`, whose envelope IDM requires — returning a bare object
 * fails at runtime with `Script returned unexpected query result structure`
 * (verified 2026-06-04).
 */
export function queryRoute<
  P extends Shape = Record<never, never>,
  Q extends Shape = Record<never, never>,
  H extends Shape = Record<never, never>,
  B = undefined,
  R = unknown,
>(spec: QueryRouteSpec<P, Q, H, B, R>): RouteDefinition {
  return build("query", spec);
}

function build<P extends Shape, Q extends Shape, H extends Shape, B, R>(
  method: CrestMethod,
  spec: RouteSpecBase<P, Q, H, B, R> & {
    handler: (input: RouteInput<P, Q, H, B>) => unknown;
  }
): RouteDefinition {
  if (method === "action" && spec.action === undefined) {
    throw new Error(
      "route " + spec.path + ': method "action" requires an action name'
    );
  }
  if (method !== "action" && spec.action !== undefined) {
    throw new Error(
      "route " + spec.path + ": only an action route may name an action"
    );
  }
  const declared = parsePath(spec.path);
  const params = (spec.params ?? {}) as Shape;
  for (const segment of declared) {
    if (
      "param" in segment &&
      !Object.prototype.hasOwnProperty.call(params, segment.param)
    ) {
      throw new Error(
        "route " +
          spec.path +
          ": path param {" +
          segment.param +
          "} has no validator"
      );
    }
  }
  for (const name of Object.keys(params)) {
    if (
      !declared.some((segment) => "param" in segment && segment.param === name)
    ) {
      throw new Error(
        "route " +
          spec.path +
          ": validator for {" +
          name +
          "} is not in the path"
      );
    }
  }
  return {
    method,
    path: spec.path,
    segments: declared,
    action: spec.action,
    summary: spec.summary,
    description: spec.description,
    scopes: spec.scopes === undefined ? [] : spec.scopes.slice(),
    params,
    query: (spec.query ?? {}) as Shape,
    headers: (spec.headers ?? {}) as Shape,
    body: spec.body as Validator<unknown> | undefined,
    patches: spec.patches,
    response: spec.response as Validator<unknown> | undefined,
    run: spec.handler as (
      input: RouteInput<Shape, Shape, Shape, unknown>
    ) => unknown,
  };
}

export interface EndpointSpec {
  /** The IDM config id suffix — `endpoint/<name>` and the emitted filename. */
  name: string;
  summary?: string;
  description?: string;
  version?: string;
  /** Headers validated on EVERY route (merged under the route's own). */
  headers?: Shape;
  /** Header used as the log correlation id. Default `x-request-id`. */
  correlationHeader?: string;
  /** Validate handler results at runtime. Useful in tests and non-production tenants. */
  validateResponses?: boolean;
  routes: RouteDefinition[];
}

/** The build-time view of an endpoint, consumed by the OpenAPI generator. */
export interface EndpointDefinition {
  name: string;
  summary: string | undefined;
  description: string | undefined;
  version: string;
  headers: Shape;
  correlationHeader: string;
  validateResponses: boolean;
  routes: RouteDefinition[];
}

/**
 * The emitted bundle's default export: a zero-argument function reading the
 * IDM globals, so the generated file can end with `__aicMain.default();` and
 * hand its completion value straight back as the HTTP response body.
 */
export interface EndpointMain {
  (): unknown;
  definition: EndpointDefinition;
  /** Same dispatch, with the bindings injected — how the unit tests drive it. */
  dispatch(
    request: CrestRequest,
    context: IdmCallContext,
    logger?: IdmLogger,
    options?: DispatchOptions
  ): unknown;
}

/** Per-call overrides for one {@link EndpointMain.dispatch}. */
export interface DispatchOptions {
  /**
   * Override the endpoint's `validateResponses`.
   *
   * Response validation is most valuable in TESTS and least wanted in
   * production, and the endpoint's own declaration cannot be both. So a test
   * turns it on per call — `dispatch(request, context, undefined, {
   * validateResponses: true })` — and nothing has to ship enabled to get the
   * check.
   */
  validateResponses?: boolean;
}

function segmentsMatch(
  segments: PathSegment[],
  actual: string[]
): Record<string, string> | null {
  if (segments.length !== actual.length) {
    return null;
  }
  const captured: Record<string, string> = {};
  for (let index = 0; index < segments.length; index += 1) {
    const segment = segments[index] as PathSegment;
    const value = actual[index] as string;
    if ("literal" in segment) {
      if (segment.literal !== value) {
        return null;
      }
    } else {
      captured[segment.param] = value;
    }
  }
  return captured;
}

/** More literal segments wins, so `/daily/{d}` beats a same-length `/{a}/{b}`. */
function specificity(route: RouteDefinition): number {
  return route.segments.filter((segment) => "literal" in segment).length;
}

function routesAreAmbiguous(left: RouteDefinition, right: RouteDefinition): boolean {
  if (
    left.method !== right.method ||
    left.action !== right.action ||
    left.segments.length !== right.segments.length ||
    specificity(left) !== specificity(right)
  ) {
    return false;
  }
  return left.segments.every((segment, index) => {
    const other = right.segments[index] as PathSegment;
    return (
      !("literal" in segment) ||
      !("literal" in other) ||
      segment.literal === other.literal
    );
  });
}

function assertUnambiguousRoutes(routes: RouteDefinition[]): void {
  for (let left = 0; left < routes.length; left += 1) {
    for (let right = left + 1; right < routes.length; right += 1) {
      const first = routes[left] as RouteDefinition;
      const second = routes[right] as RouteDefinition;
      if (routesAreAmbiguous(first, second)) {
        throw new Error(
          "ambiguous routes: " + routeLabel(first) + " and " + routeLabel(second)
        );
      }
    }
  }
}

function assertValidResponse(route: RouteDefinition, value: unknown): void {
  if (route.response === undefined) {
    return;
  }
  const issues: Issue[] = [];
  if (route.method === "query") {
    const rows =
      typeof value === "object" && value !== null
        ? (value as Record<string, unknown>)["result"]
        : undefined;
    if (!Array.isArray(rows)) {
      issues.push({ path: "response.result", message: "expected an array" });
    } else {
      for (let index = 0; index < rows.length; index += 1) {
        route.response.parse(
          rows[index],
          "response.result[" + index + "]",
          issues,
          "strict"
        );
      }
    }
  } else {
    route.response.parse(value, "response", issues, "strict");
  }
  if (issues.length > 0) {
    throw new Error(
      "response validation failed: " +
        issues.map((entry) => entry.path + " " + entry.message).join("; ")
    );
  }
}

function decodeSegment(value: string): string {
  try {
    return decodeURIComponent(value);
  } catch (_error) {
    // A malformed `%` escape is the caller's problem, not a 500: keep the
    // raw segment and let the path-param validator reject it.
    return value;
  }
}

/** Split a raw `resourcePath` into decoded segments. */
export function splitResourcePath(resourcePath: string): string[] {
  return resourcePath
    .split("/")
    .filter((part) => part !== "")
    .map(decodeSegment);
}

function headerLookup(
  context: IdmCallContext
): (name: string) => string | undefined {
  const source = context.http === undefined ? {} : context.http.headers;
  const lowered: Record<string, string> = {};
  for (const key of Object.keys(source)) {
    const value = source[key];
    if (typeof value === "string") {
      lowered[key.toLowerCase()] = value;
    }
  }
  return (name) => lowered[name.toLowerCase()];
}

function bodyOf(request: CrestRequest): unknown {
  if (
    request.method === "create" ||
    request.method === "update" ||
    request.method === "action"
  ) {
    return request.content;
  }
  return undefined;
}

/** Used when a caller drives `dispatch` without a `logger` binding (tests). */
const SILENT_LOGGER: IdmLogger = {
  trace: () => undefined,
  debug: () => undefined,
  info: () => undefined,
  warn: () => undefined,
  error: () => undefined,
};

function generateCorrelationId(): string {
  const random = Math.floor(Math.random() * 0xffffff).toString(16);
  return "aic-" + Date.now().toString(36) + "-" + random;
}

function checkScopes(
  scopes: string[],
  context: IdmCallContext
): CrestFault | null {
  if (scopes.length === 0) {
    return null;
  }
  const oauth2 = context.oauth2;
  if (oauth2 === undefined || oauth2.scopes === undefined) {
    return forbidden("Missing required OAuth scope", { required: scopes });
  }
  const missing: string[] = [];
  for (const scope of scopes) {
    // `context.oauth2.scopes` is a java.util.Set — `.contains`, never
    // `.includes` (docs/api/11-idm-endpoints.md).
    if (!oauth2.scopes.contains(scope)) {
      missing.push(scope);
    }
  }
  if (missing.length > 0) {
    return forbidden("Missing required OAuth scope", { missing });
  }
  return null;
}

/** Human label for a route, used in logs and error detail. */
export function routeLabel(route: RouteDefinition): string {
  const suffix = route.action === undefined ? "" : "?_action=" + route.action;
  return route.method + " " + route.path + suffix;
}

/**
 * Build an endpoint. The returned function is the module's default export; the
 * emitted bundle calls it as its final expression statement.
 */
export function defineEndpoint(spec: EndpointSpec): EndpointMain {
  assertUnambiguousRoutes(spec.routes);
  const definition: EndpointDefinition = {
    name: spec.name,
    summary: spec.summary,
    description: spec.description,
    version: spec.version ?? "1.0.0",
    headers: (spec.headers ?? {}) as Shape,
    correlationHeader: spec.correlationHeader ?? "x-request-id",
    validateResponses: spec.validateResponses ?? false,
    routes: spec.routes.slice(),
  };

  const dispatch = (
    request: CrestRequest,
    context: IdmCallContext,
    logger?: IdmLogger,
    options?: DispatchOptions
  ): unknown => {
    const validateResponses =
      options === undefined || options.validateResponses === undefined
        ? definition.validateResponses
        : options.validateResponses;
    const log = createRequestLogger(logger ?? SILENT_LOGGER, {
      endpoint: definition.name,
    });

    const header = headerLookup(context);
    const correlationId =
      header(definition.correlationHeader) ?? generateCorrelationId();
    const requestLog = log.child({ cid: correlationId });

    try {
      const actual = splitResourcePath(request.resourcePath);
      const pathMatches = definition.routes
        .map((candidate) => ({
          route: candidate,
          captured: segmentsMatch(candidate.segments, actual),
        }))
        .filter((entry) => entry.captured !== null)
        .sort(
          (left, right) => specificity(right.route) - specificity(left.route)
        );

      if (pathMatches.length === 0) {
        throw notFound("No route for /" + actual.join("/"), {
          method: request.method,
        });
      }
      const methodMatches = pathMatches.filter(
        (entry) => entry.route.method === request.method
      );
      if (methodMatches.length === 0) {
        const allowed: string[] = [];
        for (const entry of pathMatches) {
          if (allowed.indexOf(entry.route.method) < 0) {
            allowed.push(entry.route.method);
          }
        }
        throw methodNotAllowed(
          "Method " + request.method + " is not supported on this path",
          { allowed }
        );
      }

      let matched = methodMatches[0] as {
        route: RouteDefinition;
        captured: Record<string, string> | null;
      };
      if (request.method === "action") {
        const wanted = request.action;
        const found = methodMatches.find(
          (entry) => entry.route.action === wanted
        );
        if (found === undefined) {
          // No quotes: IDM HTML-escapes the strings in a thrown error.
          throw notFound("Unknown action: " + String(wanted), {
            supported: methodMatches.map((entry) => entry.route.action),
          });
        }
        matched = found;
      }

      const route = matched.route;
      const captured = matched.captured ?? {};
      const routed = requestLog.child({ route: routeLabel(route) });

      // Authorize before validation: validation detail would disclose the
      // request schema to a caller that does not hold the route's scope.
      const denied = checkScopes(route.scopes, context);
      if (denied !== null) {
        routed.warn("scope check failed", { required: route.scopes });
        throw denied;
      }

      const issues: Issue[] = [];
      const params = parseShape(
        route.params,
        "path",
        (key) => captured[key],
        issues
      );
      const query = parseShape(
        route.query,
        "query",
        (key) => request.additionalParameters[key],
        issues
      );
      const headerShape: Shape = { ...definition.headers, ...route.headers };
      const headers = parseShape(headerShape, "header", header, issues);
      let body: unknown = undefined;
      if (route.body !== undefined) {
        const raw = bodyOf(request);
        if (raw === undefined || raw === null) {
          issues.push({ path: "body", message: "is required" });
        } else {
          body = route.body.parse(raw, "body", issues, "strict");
        }
      }
      let patches: PatchOperation[] =
        request.method === "patch" ? request.patchOperations : [];
      if (route.patches !== undefined) {
        patches = route.patches.parse(
          patches,
          "patchOperations",
          issues,
          "strict"
        );
      }

      if (issues.length > 0) {
        routed.info("validation failed", { issues: issues.length });
        throw badRequest("Request validation failed", { issues });
      }

      routed.debug("dispatching", describeCaller(context));
      const result = route.run({
        params,
        newResourceId:
          request.method === "create" ? request.newResourceId : null,
        query,
        headers,
        body,
        patchOperations: patches,
        request,
        context,
        log: routed,
        correlationId,
      });
      if (validateResponses) {
        assertValidResponse(route, result);
      }
      return result;
    } catch (thrown) {
      const fault = toCrestFault(thrown);
      if (!isFault(thrown)) {
        // Unexpected: keep the real reason server-side only.
        requestLog.error("unhandled failure", {
          cause: describeThrowable(thrown),
          code: fault.code,
        });
      } else if (fault.code >= 500) {
        requestLog.error("request failed", { code: fault.code });
      }
      throw toCrestResponse(fault);
    }
  };

  const main = (): unknown => dispatch(request, context, logger);
  const exported = main as EndpointMain;
  exported.definition = definition;
  exported.dispatch = dispatch;
  return exported;
}
