// Standalone PingIDM scripts: scheduled jobs, and anything else IDM invokes by
// file rather than over HTTP.
//
// Endpoints answer requests and need routing, validation and a conf/ binding.
// A task has none of that -- IDM calls it, and its completion value is the
// result -- so it gets a much smaller surface. It still goes through the same
// bundle, ES5 downlevel and runtime-ban pipeline, and it sees the same PingIDM
// globals (`openidm`, `logger`), which is why tasks live here and not in
// src/scripts/ with the PingAM ones.
//
// Managed file -- regenerated by `fo upgrade`.

export interface TaskSpec<T> {
  /** Must match the source file name; it becomes the emitted script name. */
  name: string;
  description?: string;
  main: () => T;
}

export interface TaskDefinition {
  readonly kind: "idm-task";
  readonly name: string;
  readonly description?: string;
}

export interface TaskMain<T> {
  (): T;
  readonly definition: TaskDefinition;
}

/**
 * Declare a PingIDM task. The default export of every file in `src/tasks/`
 * must be the value this returns.
 */
export function defineTask<T>(spec: TaskSpec<T>): TaskMain<T> {
  const main = function (): T {
    return spec.main();
  } as { (): T; definition: TaskDefinition };
  main.definition = {
    kind: "idm-task",
    name: spec.name,
    ...(spec.description === undefined ? {} : { description: spec.description }),
  };
  return main as TaskMain<T>;
}
