// IDM custom-endpoint runtime types, in MODULE form.
//
// The workspace's `idm/types/*.d.ts` set declares the same bindings AMBIENTLY,
// for hand-written `.cjs` endpoints. This project is a real TypeScript program
// with imports, so it needs them as exported types; `framework/idm-globals.d.ts`
// re-declares the globals in terms of these.
//
// Ground truth: docs/api/11-idm-endpoints.md (request shapes per CREST method,
// verified 2026-06-04; `context.oauth2` keys 2026-08-06; `rawInfo` 2026-08-07)
// and docs/api/12-script-bindings-matrix.md.
//
// Managed file — regenerated by `aic workspace update`.

/** The CREST verbs an endpoint can be invoked with. */
export type CrestMethod =
  "read" | "create" | "update" | "patch" | "delete" | "action" | "query";

/** A single CREST patch operation. `field` is a JSON pointer (`/foo/bar`). */
export interface PatchOperation {
  operation:
    "add" | "remove" | "replace" | "increment" | "move" | "copy" | "transform";
  field: string;
  value?: unknown;
  from?: string;
}

/** Fields present on every `request`, whatever the method. */
export interface CrestRequestBase {
  /**
   * The sub-path below the endpoint, VERBATIM and UN-DECODED: `""` at the
   * root, `"x"`, `"a/b/c"` (probed 2026-08-13). The router decodes each
   * segment itself.
   */
  resourcePath: string;
  /** Non-`_`-prefixed query params, as a string -> string map. */
  additionalParameters: Record<string, string>;
  /** The `_fields` selector list. */
  fields: string[];
}

export type CrestRequest =
  | (CrestRequestBase & { method: "read" })
  | (CrestRequestBase & {
      method: "create";
      newResourceId: string | null;
      content: unknown;
    })
  | (CrestRequestBase & {
      method: "update";
      revision: string | null;
      content: unknown;
    })
  | (CrestRequestBase & {
      method: "patch";
      revision: string | null;
      patchOperations: PatchOperation[];
    })
  | (CrestRequestBase & { method: "delete"; revision: string | null })
  | (CrestRequestBase & { method: "action"; action: string; content: unknown })
  | (CrestRequestBase & {
      method: "query";
      queryFilter: string | null;
      queryId: string | null;
      queryExpression: string | null;
      pageSize: number;
      pagedResultsOffset: number;
      pagedResultsCookie: string | null;
      sortKeys: string[];
    });

/**
 * A `java.util.Set` as Rhino exposes it. Membership is `.contains(...)` —
 * `.includes`, `.indexOf` and `.length` do NOT exist on it.
 */
export interface JavaSet<T> {
  contains(value: T): boolean;
  size(): number;
  isEmpty(): boolean;
}

/**
 * The CREST call chain. `http` is present only when an HTTP request sits at
 * the ROOT of the chain, so it is optional even inside an endpoint (verified
 * 2026-07-21). `oauth2` is present only when `rsFilter` validated a bearer.
 */
export interface IdmCallContext {
  http?: {
    method: string;
    path: string;
    /** CREDENTIAL-BEARING: includes `Authorization`. Never log or return it. */
    headers: Record<string, string>;
    parameters: Record<string, string>;
  };
  security?: {
    authenticationId: string;
    authorization: { id: string; component: string; roles: string[] };
  };
  oauth2?: {
    scopes: JavaSet<string>;
    /** CREDENTIAL. Never log or return. */
    token?: string;
    rawInfo?: {
      /** CREDENTIAL. Never log or return. */
      sessionToken?: string;
      scope?: string;
      [key: string]: unknown;
    };
    [key: string]: unknown;
  };
  [key: string]: unknown;
}

/** The IDM `logger` binding. */
export interface IdmLogger {
  trace(message: string, ...args: unknown[]): void;
  debug(message: string, ...args: unknown[]): void;
  info(message: string, ...args: unknown[]): void;
  warn(message: string, ...args: unknown[]): void;
  error(message: string, ...args: unknown[]): void;
}

/** A resource object (read/create/update/patch/action return one). */
export type CrestResource = { _id?: string; _rev?: string } & Record<
  string,
  unknown
>;

/**
 * The structure a `query` handler MUST return. Returning a plain object fails
 * at runtime with `Script returned unexpected query result structure`
 * (verified 2026-06-04, docs/api/11-idm-endpoints.md).
 */
export interface CrestQueryResult<T = CrestResource> {
  result: T[];
  resultCount: number;
  pagedResultsCookie: string | null;
  totalPagedResults: number;
  remainingPagedResults: number;
  totalPagedResultsPolicy: string;
}

/** Overrides for the paging metadata filled by {@link queryResult}. */
export type QueryResultOptions = Partial<Omit<CrestQueryResult<never>, "result">>;

/**
 * The paging metadata an `openidm.query` result carries.
 *
 * Structural, and every field but `result` optional, so it accepts an
 * `OpenIdmQueryResult` without this module having to know about the `openidm`
 * globals — `idm-globals.d.ts` imports from HERE, so the dependency cannot run
 * the other way.
 */
export interface QueryPage<T> {
  result: T[];
  resultCount?: number;
  pagedResultsCookie?: string | null;
  totalPagedResults?: number;
  totalPagedResultsPolicy?: string;
  /** Absent from every observed script-side query result. */
  remainingPagedResults?: number;
}

/**
 * Pass an `openidm.query` page back out of a `query` handler, keeping ITS paging
 * metadata instead of recomputing it from the row count.
 *
 * A raw `openidm.query` result is deliberately not assignable to
 * `CrestQueryResult` — IDM never sends `remainingPagedResults` but requires it on
 * the way out — and rebuilding the envelope by hand meant transcribing four
 * fields per handler, which is exactly where a cursor gets dropped and paging
 * silently truncates at page one.
 *
 * ```ts
 * const page = openidm.query(USERS, { _queryFilter: filter, _pageSize: 10 });
 * return forwardQuery(page, page.result.map(summarise));
 * ```
 *
 * Omit `rows` to forward the page's own rows unchanged.
 */
export function forwardQuery<T>(page: QueryPage<T>): CrestQueryResult<T>;
export function forwardQuery<T, R>(
  page: QueryPage<T>,
  rows: R[]
): CrestQueryResult<R>;
export function forwardQuery(
  page: QueryPage<unknown>,
  rows?: unknown[]
): CrestQueryResult<unknown> {
  const forwarded = rows === undefined ? page.result : rows;
  return {
    result: forwarded,
    // The page's own count, not `forwarded.length`: a mapped or filtered row set
    // must not rewrite how many the STORE matched.
    resultCount: page.resultCount ?? forwarded.length,
    pagedResultsCookie: page.pagedResultsCookie ?? null,
    totalPagedResults: page.totalPagedResults ?? forwarded.length,
    remainingPagedResults: page.remainingPagedResults ?? 0,
    totalPagedResultsPolicy: page.totalPagedResultsPolicy ?? "EXACT",
  };
}

/** Build the complete response shape IDM requires from every query handler. */
export function queryResult<T>(
  rows: T[],
  options: QueryResultOptions = {}
): CrestQueryResult<T> {
  return {
    result: rows,
    resultCount: options.resultCount ?? rows.length,
    pagedResultsCookie: options.pagedResultsCookie ?? null,
    totalPagedResults: options.totalPagedResults ?? rows.length,
    remainingPagedResults: options.remainingPagedResults ?? 0,
    totalPagedResultsPolicy: options.totalPagedResultsPolicy ?? "EXACT",
  };
}
