// Typed validation combinators.
//
// One validator family covers path params, query params, headers and JSON
// bodies. Path/query/header values always arrive as STRINGS (see
// `request.additionalParameters`, a string -> string map), so the scalar
// validators coerce from a string as well as accepting the native JSON type.
// That is the whole reason `int()` exists separately from `number()`.
//
// Each validator carries the JSON Schema fragment that describes it, so the
// OpenAPI document is generated from the same declaration the runtime enforces
// — there is no second source of truth to drift.
//
// Managed file — regenerated by `aic workspace update`.

import type { PatchOperation } from "./types.ts";

/** A JSON Schema fragment (OpenAPI 3.1 uses JSON Schema 2020-12 directly). */
export type JsonSchema = Record<string, unknown>;

/** One validation failure. `path` is a dotted location, e.g. `body.items[0]`. */
export interface Issue {
  path: string;
  message: string;
}

export interface Validator<T> {
  /** JSON Schema for this value, used verbatim by the OpenAPI generator. */
  readonly schema: JsonSchema;
  /** `true` when the value may be absent (drives `required` in OpenAPI). */
  readonly isOptional: boolean;
  /**
   * Validate `input`, appending any failures to `issues`. Implementations
   * return a placeholder when they push an issue; the caller must not use the
   * result unless `issues` stayed empty.
   */
  parse(input: unknown, path: string, issues: Issue[], mode?: ParseMode): T;
}

export type ParseMode = "strict" | "coerce";

/** The TypeScript type a validator produces. */
export type Infer<V> = V extends Validator<infer T> ? T : never;

/** A named set of validators — a body shape, or one param location. */
export type Shape = Record<string, Validator<unknown>>;

/**
 * The object type a shape produces when PARSING. Every member is present, an
 * optional one holding `undefined` — which is exactly what `parseShape` builds,
 * and what a route's `params`/`query`/`headers`/`body` therefore look like.
 */
export type InferShape<S extends Shape> = { [K in keyof S]: Infer<S[K]> };

/**
 * The object type a shape describes when CONSTRUCTING a value: an optional
 * member is an optional KEY, not a required key holding `undefined`.
 *
 * `object()` produces this rather than {@link InferShape} because its type is
 * also what a route's `response` promises, and a handler must be able to omit an
 * optional it has nothing to say about instead of writing `owner: undefined`.
 *
 * Deliberately NOT a mapped type applied later, on top of `InferShape`: a mapped
 * type over an unresolved type parameter cannot serve as a contextual type, so
 * `status: "retired"` in a returned object literal would widen to `string` and
 * fail against its own declared enum. Baking it into the validator keeps the
 * response type concrete at the point the handler is checked.
 */
export type InferObject<S extends Shape> = Resolve<
  {
    [K in keyof S as undefined extends Infer<S[K]> ? never : K]: Infer<S[K]>;
  } & {
    [K in keyof S as undefined extends Infer<S[K]> ? K : never]?: Infer<S[K]>;
  }
>;

/**
 * Collapse an intersection into one object type, preserving optional modifiers.
 *
 * Not cosmetic: TypeScript will not use an unresolved alias as a contextual
 * type, so leaving `InferObject` as an intersection of two mapped types cost a
 * returned object literal its literal types. Forcing it flat here is what lets
 * `status: "retired"` narrow to the enum the response declares.
 */
type Resolve<T> = { [K in keyof T]: T[K] };

function issue(issues: Issue[], path: string, message: string): void {
  issues.push({ path, message });
}

function define<T>(
  schema: JsonSchema,
  isOptional: boolean,
  parse: (input: unknown, path: string, issues: Issue[], mode: ParseMode) => T
): Validator<T> {
  return {
    schema,
    isOptional,
    parse: (input, path, issues, mode = "strict") =>
      parse(input, path, issues, mode),
  };
}

// ---------------------------------------------------------------------------
// Scalars
// ---------------------------------------------------------------------------

export interface StringOptions {
  minLength?: number;
  maxLength?: number;
  /** Anchor it yourself; the validator does not add `^`/`$`. */
  pattern?: RegExp;
  /** Human wording for a pattern failure, e.g. `an ISO date (YYYY-MM-DD)`. */
  patternDescription?: string;
  description?: string;
}

export function string(options: StringOptions = {}): Validator<string> {
  const schema: JsonSchema = { type: "string" };
  if (options.minLength !== undefined) {
    schema["minLength"] = options.minLength;
  }
  if (options.maxLength !== undefined) {
    schema["maxLength"] = options.maxLength;
  }
  if (options.pattern !== undefined) {
    schema["pattern"] = options.pattern.source;
  }
  if (options.description !== undefined) {
    schema["description"] = options.description;
  }
  return define(schema, false, (input, path, issues) => {
    if (typeof input !== "string") {
      issue(issues, path, "expected a string");
      return "";
    }
    if (options.minLength !== undefined && input.length < options.minLength) {
      issue(
        issues,
        path,
        "must be at least " + options.minLength + " characters"
      );
    }
    if (options.maxLength !== undefined && input.length > options.maxLength) {
      issue(
        issues,
        path,
        "must be at most " + options.maxLength + " characters"
      );
    }
    if (options.pattern !== undefined) {
      // Global/sticky regular expressions retain state between `.test` calls.
      // Validators are reused across requests, so always make the result
      // independent of the preceding request.
      options.pattern.lastIndex = 0;
      const matches = options.pattern.test(input);
      options.pattern.lastIndex = 0;
      if (!matches) {
        const wanted =
          options.patternDescription ?? "match " + String(options.pattern);
        issue(issues, path, "must " + wanted);
      }
      // Deliberately NOT an early `return input` on a match: every check in
      // this function must stay reachable if another is added below.
    }
    return input;
  });
}

export interface NumberOptions {
  min?: number;
  max?: number;
  description?: string;
}

function numeric(integral: boolean, options: NumberOptions): Validator<number> {
  const schema: JsonSchema = { type: integral ? "integer" : "number" };
  if (options.min !== undefined) {
    schema["minimum"] = options.min;
  }
  if (options.max !== undefined) {
    schema["maximum"] = options.max;
  }
  if (options.description !== undefined) {
    schema["description"] = options.description;
  }
  return define(schema, false, (input, path, issues, mode) => {
    let value: number;
    if (typeof input === "number") {
      value = input;
    } else if (
      mode === "coerce" &&
      typeof input === "string" &&
      input.trim() !== ""
    ) {
      value = Number(input);
    } else {
      issue(
        issues,
        path,
        integral ? "expected an integer" : "expected a number"
      );
      return 0;
    }
    if (!isFinite(value)) {
      issue(
        issues,
        path,
        integral ? "expected an integer" : "expected a number"
      );
      return 0;
    }
    if (integral && Math.floor(value) !== value) {
      issue(issues, path, "expected an integer");
      return 0;
    }
    if (options.min !== undefined && value < options.min) {
      // IDM HTML-escapes every string in a thrown error, so `>=` would
      // reach the caller as `&#62;&#61;`. Keep messages to plain words.
      issue(issues, path, "must be at least " + options.min);
    }
    if (options.max !== undefined && value > options.max) {
      issue(issues, path, "must be at most " + options.max);
    }
    return value;
  });
}

export const integer = (options: NumberOptions = {}): Validator<number> =>
  numeric(true, options);

export const number = (options: NumberOptions = {}): Validator<number> =>
  numeric(false, options);

export function boolean(description?: string): Validator<boolean> {
  const schema: JsonSchema = { type: "boolean" };
  if (description !== undefined) {
    schema["description"] = description;
  }
  return define(schema, false, (input, path, issues, mode) => {
    if (typeof input === "boolean") {
      return input;
    }
    if (mode === "coerce" && input === "true") {
      return true;
    }
    if (mode === "coerce" && input === "false") {
      return false;
    }
    issue(issues, path, "expected true or false");
    return false;
  });
}

/**
 * A closed set of string values. `const` type parameter inference makes the
 * handler see the literal union, not `string`:
 * `enumOf(["active", "retired"])` -> `Validator<"active" | "retired">`.
 */
export function enumOf<const T extends readonly string[]>(
  values: T,
  description?: string
): Validator<T[number]> {
  const schema: JsonSchema = { type: "string", enum: values.slice() };
  if (description !== undefined) {
    schema["description"] = description;
  }
  return define(schema, false, (input, path, issues) => {
    if (
      typeof input === "string" &&
      (values as readonly string[]).includes(input)
    ) {
      return input as T[number];
    }
    issue(issues, path, "must be one of: " + values.join(", "));
    return values[0] as T[number];
  });
}

/** A UUID-shaped string (any version, case-insensitive). */
export const uuid = (description?: string): Validator<string> =>
  string({
    pattern:
      /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/,
    patternDescription: "be a UUID",
    ...(description === undefined ? {} : { description }),
  });

/** A real Gregorian calendar date in `YYYY-MM-DD` form. */
export const isoDate = (description?: string): Validator<string> => {
  const formatted = string({
    pattern: /^\d{4}-\d{2}-\d{2}$/,
    patternDescription: "be a date in YYYY-MM-DD form",
    ...(description === undefined ? {} : { description }),
  });
  return define(formatted.schema, false, (input, path, issues, mode) => {
    const before = issues.length;
    const value = formatted.parse(input, path, issues, mode);
    if (issues.length !== before) {
      return value;
    }
    const year = Number(value.slice(0, 4));
    const month = Number(value.slice(5, 7));
    const day = Number(value.slice(8, 10));
    const leap = year % 4 === 0 && (year % 100 !== 0 || year % 400 === 0);
    const days = [31, leap ? 29 : 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
    if (month < 1 || month > 12 || day < 1 || day > (days[month - 1] ?? 0)) {
      issue(issues, path, "must be a date in YYYY-MM-DD form");
    }
    return value;
  });
};

// ---------------------------------------------------------------------------
// Composition
// ---------------------------------------------------------------------------

/**
 * Widen a schema's `type` (and `enum`, when it has one) to admit `null`.
 * OpenAPI 3.1 is JSON Schema 2020-12, so `type: ["string", "null"]` is the
 * encoding — not the 3.0-era `nullable: true`.
 */
function nullableSchema(inner: JsonSchema): JsonSchema {
  const schema: JsonSchema = { ...inner };
  const type = schema["type"];
  if (typeof type === "string") {
    schema["type"] = [type, "null"];
  } else if (Array.isArray(type) && type.indexOf("null") < 0) {
    schema["type"] = type.concat(["null"]);
  }
  const values = schema["enum"];
  if (Array.isArray(values) && values.indexOf(null) < 0) {
    schema["enum"] = values.concat([null]);
  }
  return schema;
}

/**
 * Allow an explicit JSON `null` as well as `T`. Produces `T | null`.
 *
 * NULL AND ABSENT ARE DIFFERENT THINGS, and IDM uses both: a managed record
 * hands back `"manager": null` for an unset single-valued relationship, and a
 * caller clearing a field sends `null` rather than omitting it. {@link optional}
 * covers ABSENT (`undefined`); this covers PRESENT-AND-NULL. Compose them —
 * `optional(nullable(v.string()))` — for a member that may be either.
 *
 * A JSON body, a patch value and a declared `response` are all validated
 * STRICTLY (see {@link ParseMode}), so `null` there is a real value that only
 * this combinator accepts. Without it a handler returning IDM's own `null` fails
 * its own `response` declaration.
 */
export function nullable<T>(inner: Validator<T>): Validator<T | null> {
  return define(
    nullableSchema(inner.schema),
    inner.isOptional,
    (input, path, issues, mode) => {
      if (input === null) {
        return null;
      }
      return inner.parse(input, path, issues, mode);
    }
  );
}

/**
 * Allow the value to be absent. Produces `T | undefined`, never `?:`.
 *
 * In `coerce` mode (path/query/header strings) `null` and `""` also count as
 * absent, because that is what an omitted query param looks like. In `strict`
 * mode (JSON bodies, patch values, responses) only `undefined` is absent —
 * wrap with {@link nullable} to admit an explicit `null`.
 */
export function optional<T>(inner: Validator<T>): Validator<T | undefined> {
  return define(inner.schema, true, (input, path, issues, mode) => {
    if (
      input === undefined ||
      (mode === "coerce" && (input === null || input === ""))
    ) {
      return undefined;
    }
    return inner.parse(input, path, issues, mode);
  });
}

/** Substitute `value` when the input is absent. Stays required-typed (`T`). */
export function withDefault<T>(inner: Validator<T>, value: T): Validator<T> {
  const schema: JsonSchema = { ...inner.schema, default: value };
  return define(schema, true, (input, path, issues, mode) => {
    if (
      input === undefined ||
      (mode === "coerce" && (input === null || input === ""))
    ) {
      return value;
    }
    return inner.parse(input, path, issues, mode);
  });
}

export interface ListOptions {
  minItems?: number;
  maxItems?: number;
  description?: string;
}

function listSchema(inner: JsonSchema, options: ListOptions): JsonSchema {
  const schema: JsonSchema = { type: "array", items: inner };
  if (options.minItems !== undefined) {
    schema["minItems"] = options.minItems;
  }
  if (options.maxItems !== undefined) {
    schema["maxItems"] = options.maxItems;
  }
  if (options.description !== undefined) {
    schema["description"] = options.description;
  }
  return schema;
}

function checkLength(
  length: number,
  options: ListOptions,
  path: string,
  issues: Issue[]
): void {
  if (options.minItems !== undefined && length < options.minItems) {
    issue(issues, path, "must have at least " + options.minItems + " items");
  }
  if (options.maxItems !== undefined && length > options.maxItems) {
    issue(issues, path, "must have at most " + options.maxItems + " items");
  }
}

/** A JSON array. */
export function list<T>(
  inner: Validator<T>,
  options: ListOptions = {}
): Validator<T[]> {
  return define(
    listSchema(inner.schema, options),
    false,
    (input, path, issues, mode) => {
      if (!Array.isArray(input)) {
        issue(issues, path, "expected an array");
        return [];
      }
      checkLength(input.length, options, path, issues);
      const out: T[] = [];
      for (let index = 0; index < input.length; index += 1) {
        out.push(
          inner.parse(input[index], path + "[" + index + "]", issues, mode)
        );
      }
      return out;
    }
  );
}

/**
 * A comma-separated list in a query/path/header value (`tags=a,b,c`). Also
 * accepts a real array, so the same validator works for a JSON body field.
 * Empty segments are dropped, so `a,,b` is two items and `` is zero.
 */
export function csv<T>(
  inner: Validator<T>,
  options: ListOptions = {}
): Validator<T[]> {
  const schema = listSchema(inner.schema, options);
  schema["x-aic-encoding"] = "comma-separated";
  return define(schema, false, (input, path, issues, mode) => {
    let parts: unknown[];
    if (Array.isArray(input)) {
      parts = input;
    } else if (mode === "coerce" && typeof input === "string") {
      parts = input
        .split(",")
        .map((part) => part.trim())
        .filter((part) => part !== "");
    } else {
      issue(issues, path, "expected a comma-separated list");
      return [];
    }
    checkLength(parts.length, options, path, issues);
    const out: T[] = [];
    for (let index = 0; index < parts.length; index += 1) {
      out.push(
        inner.parse(parts[index], path + "[" + index + "]", issues, mode)
      );
    }
    return out;
  });
}

export interface ObjectOptions {
  /** Keep unrecognised keys instead of rejecting them. Default `false`. */
  allowUnknown?: boolean;
  description?: string;
}

/** A JSON object with a fixed set of keys. */
export function object<S extends Shape>(
  shape: S,
  options: ObjectOptions = {}
): Validator<InferObject<S>> {
  const properties: Record<string, JsonSchema> = {};
  const required: string[] = [];
  const keys = Object.keys(shape);
  for (const key of keys) {
    const member = shape[key] as Validator<unknown>;
    properties[key] = member.schema;
    if (!member.isOptional) {
      required.push(key);
    }
  }
  const schema: JsonSchema = {
    type: "object",
    properties,
    additionalProperties: options.allowUnknown === true,
  };
  if (required.length > 0) {
    schema["required"] = required;
  }
  if (options.description !== undefined) {
    schema["description"] = options.description;
  }

  return define(schema, false, (input, path, issues, mode) => {
    const out: Record<string, unknown> = {};
    if (typeof input !== "object" || input === null || Array.isArray(input)) {
      issue(issues, path, "expected an object");
      return out as InferObject<S>;
    }
    const source = input as Record<string, unknown>;
    for (const key of keys) {
      const member = shape[key] as Validator<unknown>;
      const child = path === "" ? key : path + "." + key;
      const raw = Object.prototype.hasOwnProperty.call(source, key)
        ? source[key]
        : undefined;
      if (raw === undefined && !member.isOptional) {
        issue(issues, child, "is required");
        continue;
      }
      const value = member.parse(raw, child, issues, mode);
      // AN ABSENT OPTIONAL STAYS ABSENT. Writing `out[key] = undefined` created
      // the key, so `"nickname" in body` was true for a field the caller never
      // sent, `Object.keys(body)` listed it, and spreading `body` into an
      // `openidm` write payload carried an explicit `undefined` for it. The
      // declared type has said optional KEY all along ({@link InferObject}); this
      // is the runtime catching up.
      //
      // `withDefault` and `nullable` are unaffected: the first returns its
      // default and the second returns `null`, and neither is `undefined`.
      if (value === undefined && member.isOptional) {
        continue;
      }
      out[key] = value;
    }
    if (options.allowUnknown !== true) {
      for (const key of Object.keys(source)) {
        if (!Object.prototype.hasOwnProperty.call(shape, key)) {
          issue(
            issues,
            path === "" ? key : path + "." + key,
            "is not a known field"
          );
        }
      }
    }
    // `out` has every key present, optionals holding `undefined`; that is
    // assignable to `InferObject` because an optional member's type includes
    // `undefined` even under `exactOptionalPropertyTypes`.
    return out as InferObject<S>;
  });
}

/** An open map of same-typed values (`Record<string, T>`). */
export function record<T>(
  inner: Validator<T>,
  description?: string
): Validator<Record<string, T>> {
  const schema: JsonSchema = {
    type: "object",
    additionalProperties: inner.schema,
  };
  if (description !== undefined) {
    schema["description"] = description;
  }
  return define(schema, false, (input, path, issues, mode) => {
    const out: Record<string, T> = {};
    if (typeof input !== "object" || input === null || Array.isArray(input)) {
      issue(issues, path, "expected an object");
      return out;
    }
    const source = input as Record<string, unknown>;
    for (const key of Object.keys(source)) {
      out[key] = inner.parse(source[key], path + "." + key, issues, mode);
    }
    return out;
  });
}

/** Anything at all — an escape hatch for genuinely free-form payloads. */
export function unknownValue(description?: string): Validator<unknown> {
  const schema: JsonSchema = {};
  if (description !== undefined) {
    schema["description"] = description;
  }
  return define(schema, false, (input) => input);
}

const PATCH_OPERATIONS = [
  "add",
  "remove",
  "replace",
  "increment",
  "move",
  "copy",
  "transform",
] as const;

/**
 * CREST patch operations. `request.patchOperations` is a Java list, mirrored
 * over the wire as an index-keyed object, so this accepts both an array and
 * `{ "0": {...} }` (docs/api/11-idm-endpoints.md).
 */
export function patchOperations(
  options: ListOptions = {}
): Validator<PatchOperation[]> {
  const operation = object({
    operation: enumOf(PATCH_OPERATIONS),
    field: string({ minLength: 1 }),
    value: optional(unknownValue()),
    from: optional(string()),
  });
  const inner = list(operation, options);
  const schema = { ...inner.schema, "x-aic-crest-patch": true };
  return define(schema, false, (input, path, issues, mode) => {
    let source: unknown = input;
    if (!Array.isArray(input) && typeof input === "object" && input !== null) {
      const indexed = input as Record<string, unknown>;
      const keys = Object.keys(indexed).sort(
        (left, right) => Number(left) - Number(right)
      );
      source = keys.map((key) => indexed[key]);
    }
    return inner.parse(source, path, issues, mode) as PatchOperation[];
  });
}

// ---------------------------------------------------------------------------
// Running a shape over one input location
// ---------------------------------------------------------------------------

/**
 * Validate a whole location (path params, query, headers) against `shape`,
 * reading raw values through `lookup` so a case-insensitive header map and a
 * plain query map can share this code. `lookup` returns `undefined` for absent.
 */
export function parseShape<S extends Shape>(
  shape: S,
  location: string,
  lookup: (key: string) => unknown,
  issues: Issue[]
): InferShape<S> {
  const out: Record<string, unknown> = {};
  for (const key of Object.keys(shape)) {
    const member = shape[key] as Validator<unknown>;
    const path = location + "." + key;
    const raw = lookup(key);
    if (raw === undefined && !member.isOptional) {
      issue(issues, path, "is required");
      continue;
    }
    out[key] = member.parse(raw, path, issues, "coerce");
  }
  return out as InferShape<S>;
}
