import { existsSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { capture } from "../lib/proc.ts";
import { kubeEnv, podName, q } from "../lib/k8s.ts";
import { detail, ok, warn } from "../lib/ui.ts";
import type { ResolvedConfig } from "../config.ts";

/**
 * Tier 1 of the inner loop: push authored files straight into the running pod
 * and let PingIDM's file-install watcher reload them. No image build, no
 * rollout, no restart.
 *
 * This only works because `fo`'s dev config profile turns the watcher on -
 * ForgeOps ships `openidm.fileinstall.enabled=false`, and against a stock
 * profile every sync here would be silently ignored. See profile.ts.
 */

type Target = { name: string; local: string; remote: string };

function targets(cfg: ResolvedConfig): Target[] {
  return [
    {
      name: "conf",
      local: join(cfg.root, "platform", "idm", "conf"),
      remote: "/opt/openidm/conf",
    },
    {
      name: "script",
      local: join(cfg.root, "platform", "idm", "script"),
      remote: "/opt/openidm/script",
    },
    {
      // Sample data a connector reads from disk, e.g. a CSV an example syncs
      // from. NOT a mount, so a pod restart loses it until the next sync -
      // which is fine for sample data and wrong for anything else.
      name: "data",
      local: join(cfg.root, "platform", "idm", "data"),
      remote: "/opt/openidm/data",
    },
  ];
}

function fileCount(dir: string): number {
  try {
    return readdirSync(dir, { recursive: true, withFileTypes: true }).filter(
      (e) => e.isFile(),
    ).length;
  } catch {
    return 0;
  }
}

/**
 * Returns false if nothing could be synced, so a watcher can tell "no pod" from
 * "nothing to do" rather than reporting success either way.
 */
export function syncIdm(
  cfg: ResolvedConfig,
  only?: "conf" | "script" | "data",
): boolean {
  const pod = podName(cfg, "app=idm");
  if (!pod) {
    warn("no running idm pod; skipping sync");
    return false;
  }

  let synced = 0;
  for (const t of targets(cfg)) {
    if (only && t.name !== only) continue;
    if (!existsSync(t.local)) continue;
    const n = fileCount(t.local);
    if (n === 0) continue;

    // tar over exec rather than a `kubectl cp` per file: one round trip for
    // the whole tree, which is what keeps this inside the 5s budget.
    capture(
      "sh",
      [
        "-c",
        // mkdir first: `data` is not one of the image's directories.
        `kubectl -n ${q(cfg.namespace)} exec ${q(pod)} -c openidm -- ` +
          `mkdir -p ${q(t.remote)} && ` +
          `tar -C ${q(t.local)} -cf - . | ` +
          `kubectl -n ${q(cfg.namespace)} exec -i ${q(pod)} -c openidm -- ` +
          `tar -C ${q(t.remote)} -xf -`,
      ],
      { env: kubeEnv(cfg) },
    );
    detail(`${t.name}: ${n} file${n === 1 ? "" : "s"} -> ${pod}:${t.remote}`);
    synced += n;
  }

  retireOrphans(cfg, pod);

  if (synced === 0) {
    detail("nothing to sync (platform/idm/{conf,script} are empty)");
    return false;
  }
  ok(`synced ${synced} file${synced === 1 ? "" : "s"}`);
  return true;
}

/** The marker `fo build` writes into everything it generates. */
const GENERATED_MARKER = "@generated by `fo build`";

/**
 * Delete generated files the pod still has and the repo no longer does.
 *
 * `fo sync` pushes a tar of the current tree, which ADDS and OVERWRITES but
 * never removes - so deleting an endpoint's TypeScript left it serving in the
 * pod indefinitely. `fo build` retires the generated files from disk, the next
 * sync says "synced 3 files", and the endpoint you deleted still answers 200.
 *
 * Only files carrying `fo build`'s own generated marker are eligible, so this
 * can never remove something a person put there - including anything
 * `fo config export idm` adopted.
 */
function retireOrphans(cfg: ResolvedConfig, pod: string): void {
  const keep = new Set<string>();
  for (const dir of ["script", "conf"]) {
    const local = join(cfg.root, "platform", "idm", dir);
    if (!existsSync(local)) continue;
    for (const e of readdirSync(local, { withFileTypes: true })) {
      if (e.isFile()) keep.add(e.name);
    }
  }

  // One exec, not one per file: this runs on every sync and the tier-1 budget
  // is a second.
  const script = [
    `for f in /opt/openidm/script/* /opt/openidm/conf/endpoint-*.json; do`,
    `  [ -f "$f" ] || continue;`,
    `  head -5 "$f" | grep -qF ${q(GENERATED_MARKER)} || continue;`,
    `  b=$(basename "$f");`,
    `  case "|$FO_KEEP|" in *"|$b|"*) ;; *) rm -f "$f" && echo "$b";; esac;`,
    `done`,
  ].join(" ");

  const r = capture(
    "kubectl",
    [
      "-n", cfg.namespace, "exec", pod, "-c", "openidm", "--",
      "env", `FO_KEEP=${[...keep].join("|")}`, "sh", "-c", script,
    ],
    { env: kubeEnv(cfg), allowFailure: true },
  );
  const removed = r.stdout.trim().split("\n").filter(Boolean);
  for (const name of removed) detail(`retired ${name} (no longer generated)`);
}
