// The two-step build: type-check -> esbuild bundle -> Babel downlevel -> emit.
//
// WHY TWO TOOLS. esbuild cannot target ES5 at all ("Transforming const to the
// configured target environment (es5) is not supported yet", probed
// 2026-08-13), and Babel has no bundler. So esbuild resolves the module graph
// into one IIFE at ES2020, and Babel downlevels that single file to ES5 with
// `@babel/preset-env`. Babel 8 removed `loose`, so the size/shape savings come
// from `assumptions` instead.
//
// NOTHING IS EMITTED UNLESS EVERY STEP SUCCEEDS FOR EVERY ENDPOINT. A broken
// build must not leave a half-updated bundle for `fo sync` to push.
//
// ON-PREM: output goes to platform/idm/script/ and platform/idm/conf/, which
// the config profile and `fo sync` consume. There is no tenant, so there is no
// push, no conflict detection and no watcher racing a remote — the whole class
// of "someone else overwrote my change" problems simply does not exist here.
//
// Managed file — regenerated by `fo upgrade`.

import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { basename, dirname, join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { assertMeasurementCovers } from "./engine-coverage.mjs";
import {
  assertNoAbsentBuiltinUses,
  assertNoNativeSubclasses,
} from "./engine-usage.mjs";
import { findRuntimeBanViolations } from "./idm-runtime-bans.mjs";
import { generateManagedTypes } from "./managed-types.mjs";
import { GLOBAL_NAME, bundle, downlevel } from "./pipeline.mjs";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const workspaceRoot = resolve(projectRoot, "..");

const endpointsDir = join(projectRoot, "src", "endpoints");
const scriptsDir = join(projectRoot, "src", "scripts");
// Standalone PingIDM scripts. Same globals and same output directory as an
// endpoint's bundle, but no routing and no conf/ binding.
const tasksDir = join(projectRoot, "src", "tasks");
// PingAM scripts deploy as amster entities, not as files in a pod, so they
// land in the tier-2 tree rather than under idm/.
const amScriptsDir = join(
  workspaceRoot, "amster", "config", "realms", "root", "Scripts"
);
// PingIDM reads scripts from script/ and binds them to a route with a
// conf/endpoint-<name>.json. The build owns both, so the two can never drift.
const outputDir = join(workspaceRoot, "idm", "script");
const confDir = join(workspaceRoot, "idm", "conf");
const openapiDir = join(projectRoot, "openapi");
const distDir = join(projectRoot, "dist");
const manifestPath = join(projectRoot, ".fo-ts-manifest.json");
// Types for PingIDM's managed objects, derived from the deployment's own
// managed.json rather than hard-coded. `fo config export idm` is what puts
// that file in the repo; until it has run there is nothing to generate from.
const managedJsonPath = join(workspaceRoot, "idm", "conf", "managed.json");
const generatedDir = join(projectRoot, "src", "generated");
const managedTypesPath = join(generatedDir, "managed.ts");

const argv = process.argv.slice(2);
const watchMode = argv.includes("--watch");
const skipTypeCheck = argv.includes("--no-type-check");
// `npm run type-check` is this file with nothing else turned on, so the list
// of programs above cannot drift from what the build enforces.
const typeCheckOnly = argv.includes("--type-check-only");
let atomicSequence = 0;

// ---------------------------------------------------------------------------
// Steps
// ---------------------------------------------------------------------------

/**
 * Every TypeScript program in this package.
 *
 * THE list, not a copy of it: `package.json`'s `type-check` script runs this
 * file too (`--type-check-only`), because when the two kept their own copies
 * they drifted - `tsconfig.am.json` was in one and not the other, so a type
 * error in a PingAM script passed `fo build`, was emitted, and only `fo check`
 * would catch it. A build that emits code it never type-checked is not a
 * build.
 */
const TYPE_CHECK_PROGRAMS = [
  "tsconfig.json",
  "tsconfig.am.json",
  "tsconfig.tests.json",
];

function typeCheck() {
  // tsgo, not tsc: the project moved to TypeScript 7 for the 5.7x, and this
  // file was left behind on the old compiler while `package.json` moved. Two
  // programs AND two compilers out of step.
  const tsgo = join(projectRoot, "node_modules", ".bin", "tsgo");
  if (!existsSync(tsgo)) {
    // Never "run npm install": the dependency tree is built by nix from the
    // committed lockfile and linked in by the devShell.
    throw new Error(
      "node_modules is missing. Enter the dev shell (direnv allow, or " +
        "nix develop) — it links platform/typescript/node_modules from the " +
        "nix store. `npm install` is never the answer here."
    );
  }
  for (const config of TYPE_CHECK_PROGRAMS) {
    const result = spawnSync(
      tsgo,
      ["--noEmit", "-p", join(projectRoot, config)],
      {
        stdio: "inherit",
        cwd: projectRoot,
      }
    );
    if (result.status !== 0) {
      throw new Error("type-check failed (" + config + ")");
    }
  }

  // Part of the type-check, not a separate step, and deliberately BEFORE any
  // emission: `@babel/preset-env` runs with `useBuiltIns: false`, so a builtin
  // Rhino lacks is not polyfilled -- it type-checks, builds, deploys, and
  // throws inside somebody's login. tsgo cannot see that, because the pinned
  // `lib` legitimately declares those members and TypeScript has no way to
  // un-declare one.
  // FIRST, because the two checks below read `engine-surface.json` and are
  // only worth anything if it still describes the compilers in use. After a
  // bump, a newly declared builtin is simply absent from the file rather than
  // recorded `false`, and an absent key reads as "fine".
  assertMeasurementCovers(
    JSON.parse(readFileSync(join(projectRoot, "framework", "engine-surface.json"), "utf8")),
    JSON.parse(readFileSync(join(projectRoot, "framework", "engine-coverage.json"), "utf8")),
  );

  assertNoAbsentBuiltinUses();

  // Same step, same reason: `_wrapNativeSuper` was measured to break on both
  // engines, and a syntactic rule could not tell a real `Map` from a project
  // class that happens to be called one.
  assertNoNativeSubclasses();
}

function entryPoints() {
  if (!existsSync(endpointsDir)) {
    return [];
  }
  return readdirSync(endpointsDir)
    .filter((name) => name.endsWith(".ts") && !name.endsWith(".d.ts"))
    .sort()
    .map((name) => join(endpointsDir, name));
}

/**
 * A stable UUID for an amster Scripts entity, derived from the script name.
 *
 * AM identifies scripts by UUID, but a developer names a FILE. Deriving the id
 * means renaming nothing and re-importing repeatedly both stay idempotent -- a
 * random id would create a second copy of the script on every build.
 */
function scriptUuid(name) {
  const hash = createHash("sha1")
    .update("fo/am-script/" + name)
    .digest("hex");
  const hex = hash.slice(0, 32).split("");
  // Stamp version 5 and the RFC 4122 variant so AM sees a well-formed UUID.
  hex[12] = "5";
  hex[16] = "8";
  const s = hex.join("");
  return [
    s.slice(0, 8), s.slice(8, 12), s.slice(12, 16), s.slice(16, 20), s.slice(20),
  ].join("-");
}

/**
 * Read the endpoint's declaration by importing it. Bundling to ESM first means
 * the tool never has to care how the source is split up or whether node can
 * strip its types.
 */
async function readDefinition(entry, name) {
  const esm = await bundle(entry, "esm", undefined);
  mkdirSync(join(distDir, "meta"), { recursive: true });
  const metaPath = join(distDir, "meta", name + ".mjs");
  writeFileSync(metaPath, esm, "utf8");
  const module = await import(
    pathToFileURL(metaPath).href + "?t=" + Date.now()
  );
  const main = module.default;
  if (typeof main !== "function" || typeof main.definition !== "object") {
    throw new Error(
      relative(projectRoot, entry) +
        ": default export must be the value returned by defineEndpoint()"
    );
  }
  return main.definition;
}

function banner(name, sourceRelative) {
  return [
    "// @generated by `fo build` from platform/typescript — DO NOT EDIT.",
    "// @ts-nocheck",
    "//",
    "// Source:  " + sourceRelative,
    "// Rebuild: fo build",
    "//",
    "// Bundled with esbuild (es2020) then downlevelled to ES5 by Babel. Edit the",
    "// TypeScript, never this file: the next build overwrites it.",
    "",
  ].join("\n");
}

function footer() {
  // The endpoint's HTTP response body is the script's COMPLETION VALUE, so the
  // file must end with an expression statement (verified 2026-08-13).
  return "\n" + GLOBAL_NAME + ".default();\n";
}

async function buildEndpoint(entry) {
  const fileName = basename(entry, ".ts");
  const definition = await readDefinition(entry, fileName);
  if (definition.name !== fileName) {
    throw new Error(
      relative(projectRoot, entry) +
        ': endpoint name "' +
        definition.name +
        '" must match the file name "' +
        fileName +
        '" — the file name is what `fo sync` pushes'
    );
  }
  const iife = await bundle(entry, "iife", GLOBAL_NAME);
  const code = downlevel(iife, fileName);
  const violations = findRuntimeBanViolations(code);
  if (violations.length > 0) {
    const lines = violations.map(
      (violation) =>
        "  line " +
        violation.line +
        " [" +
        violation.rule +
        "] " +
        violation.message
    );
    throw new Error(
      fileName +
        ": generated bundle breaks IDM runtime rules\n" +
        lines.join("\n")
    );
  }
  const sourceRelative = "typescript/" + relative(projectRoot, entry);
  return {
    name: definition.name,
    entry,
    sourceRelative,
    definition,
    code: banner(definition.name, sourceRelative) + code + footer(),
  };
}

function taskEntryPoints() {
  if (!existsSync(tasksDir)) {
    return [];
  }
  return readdirSync(tasksDir)
    .filter((name) => name.endsWith(".ts") && !name.endsWith(".d.ts"))
    .sort()
    .map((name) => join(tasksDir, name));
}

async function buildTask(entry) {
  const fileName = basename(entry, ".ts");
  const esm = await bundle(entry, "esm", undefined);
  mkdirSync(join(distDir, "meta"), { recursive: true });
  const metaPath = join(distDir, "meta", "task-" + fileName + ".mjs");
  writeFileSync(metaPath, esm, "utf8");
  const module = await import(
    pathToFileURL(metaPath).href + "?t=" + Date.now()
  );
  const main = module.default;
  if (typeof main !== "function" || typeof main.definition !== "object") {
    throw new Error(
      relative(projectRoot, entry) +
        ": default export must be the value returned by defineTask()"
    );
  }
  if (main.definition.name !== fileName) {
    throw new Error(
      relative(projectRoot, entry) +
        ': task name "' + main.definition.name +
        '" must match the file name "' + fileName + '"'
    );
  }
  const iife = await bundle(entry, "iife", GLOBAL_NAME);
  const code = downlevel(iife, fileName);
  const violations = findRuntimeBanViolations(code);
  if (violations.length > 0) {
    throw new Error(
      fileName + ": generated bundle breaks IDM runtime rules\n" +
        violations.map((v) => "  line " + v.line + " [" + v.rule + "] " + v.message).join("\n")
    );
  }
  const sourceRelative = "typescript/" + relative(projectRoot, entry);
  return {
    name: fileName,
    definition: main.definition,
    sourceRelative,
    code: banner(fileName, sourceRelative) + code + footer(),
  };
}

function amEntryPoints() {
  if (!existsSync(scriptsDir)) {
    return [];
  }
  return readdirSync(scriptsDir)
    .filter((name) => name.endsWith(".ts") && !name.endsWith(".d.ts"))
    .sort()
    .map((name) => join(scriptsDir, name));
}

async function readAmDefinition(entry, name) {
  const esm = await bundle(entry, "esm", undefined);
  mkdirSync(join(distDir, "meta"), { recursive: true });
  const metaPath = join(distDir, "meta", "am-" + name + ".mjs");
  writeFileSync(metaPath, esm, "utf8");
  const module = await import(
    pathToFileURL(metaPath).href + "?t=" + Date.now()
  );
  const main = module.default;
  if (typeof main !== "function" || typeof main.definition !== "object") {
    throw new Error(
      relative(projectRoot, entry) +
        ": default export must be the value returned by defineAmScript()"
    );
  }
  return main.definition;
}

async function buildAmScript(entry) {
  const fileName = basename(entry, ".ts");
  const definition = await readAmDefinition(entry, fileName);
  if (definition.name !== fileName) {
    throw new Error(
      relative(projectRoot, entry) +
        ': script name "' + definition.name +
        '" must match the file name "' + fileName + '"'
    );
  }
  const iife = await bundle(entry, "iife", GLOBAL_NAME);
  const code = downlevel(iife, fileName);
  const violations = findRuntimeBanViolations(code);
  if (violations.length > 0) {
    throw new Error(
      fileName + ": generated bundle breaks runtime rules\n" +
        violations.map((v) => "  line " + v.line + " [" + v.rule + "] " + v.message).join("\n")
    );
  }
  const sourceRelative = "typescript/" + relative(projectRoot, entry);
  return {
    name: definition.name,
    definition,
    sourceRelative,
    code: banner(definition.name, sourceRelative) + code + footer(),
  };
}

/** One amster `Scripts` entity per AM script, ready for `fo amster`. */
function amScriptOutputs(built) {
  return built.map((script) => ({
    path: join(amScriptsDir, script.name + ".json"),
    content:
      JSON.stringify(
        {
          metadata: {
            realm: "/",
            amsterVersion: "&{version}",
            entityType: "Scripts",
            entityId: scriptUuid(script.name),
            pathParams: {},
          },
          data: {
            _id: scriptUuid(script.name),
            name: script.definition.name,
            description:
              script.definition.description ??
              "Generated by fo build from " + script.sourceRelative,
            // AM stores the body base64-encoded.
            script: Buffer.from(script.code, "utf8").toString("base64"),
            language: "JAVASCRIPT",
            context: script.definition.context,
            evaluatorVersion: "2.0",
          },
        },
        null,
        2
      ) + "\n",
  }));
}

// ---------------------------------------------------------------------------
// Emission
// ---------------------------------------------------------------------------

/** Publish a complete file in one rename so watchers never see partial data. */
function atomicWrite(path, content) {
  const temporary = join(
    dirname(path),
    "." + basename(path) + "." + process.pid + "." + atomicSequence++ + ".tmp"
  );
  try {
    writeFileSync(temporary, content, "utf8");
    renameSync(temporary, path);
  } finally {
    rmSync(temporary, { force: true });
  }
}

function previouslyOwnedAmScriptNames() {
  if (!existsSync(manifestPath)) {
    return [];
  }
  try {
    const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
    if (!Array.isArray(manifest.amScripts)) {
      return [];
    }
    return manifest.amScripts
      .map((script) => script?.name)
      .filter(
        (name) =>
          typeof name === "string" && /^[A-Za-z0-9._-]+$/.test(name) &&
          name !== "." && name !== ".."
      );
  } catch {
    return [];
  }
}

function retireRemovedAmScripts(previousNames, built) {
  const current = new Set(built.map((script) => script.name));
  for (const name of previousNames) {
    if (!current.has(name)) {
      // Only the local file goes. AM keeps the script until someone deletes
      // it there: an import cannot express a deletion, and silently pruning
      // config from a running realm is not a build's business.
      rmSync(join(amScriptsDir, name + ".json"), { force: true });
    }
  }
}

function previouslyOwnedNames(key) {
  if (!existsSync(manifestPath)) {
    return [];
  }
  try {
    const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
    if (!Array.isArray(manifest[key])) {
      return [];
    }
    return manifest[key]
      .map((entry) => entry?.name)
      .filter(
        (name) =>
          typeof name === "string" && /^[A-Za-z0-9._-]+$/.test(name) &&
          name !== "." && name !== ".."
      );
  } catch {
    return [];
  }
}

function retireRemovedTasks(previousNames, built) {
  const current = new Set(built.map((task) => task.name));
  for (const name of previousNames) {
    if (!current.has(name)) {
      rmSync(join(outputDir, name + ".js"), { force: true });
    }
  }
}

function writeManifest(built, amBuilt, taskBuilt) {
  const manifest = {
    version: 1,
    tasks: taskBuilt.map((task) => ({
      name: task.name,
      source: task.sourceRelative,
      file: "idm/script/" + task.name + ".js",
    })),
    amScripts: amBuilt.map((script) => ({
      name: script.name,
      id: scriptUuid(script.name),
      context: script.definition.context,
      outcomes: script.definition.outcomes,
      source: script.sourceRelative,
      file:
        "amster/config/realms/root/Scripts/" + script.name + ".json",
    })),
    // The record of what this build OWNS, so the next build can retire an
    // endpoint you deleted instead of leaving an orphan script in the pod.
    endpoints: built.map((endpoint) => ({
      name: endpoint.name,
      script: "idm/script/" + endpoint.name + ".js",
      conf: "idm/conf/endpoint-" + endpoint.name + ".json",
      source: endpoint.sourceRelative,
      routes: endpoint.definition.routes.map((route) => ({
        method: route.method,
        path: route.path,
        ...(route.action === undefined ? {} : { action: route.action }),
      })),
    })),
  };
  atomicWrite(manifestPath, JSON.stringify(manifest, null, 2) + "\n");
}

function previouslyOwnedEndpointNames() {
  if (!existsSync(manifestPath)) {
    return [];
  }
  try {
    const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
    if (!Array.isArray(manifest.endpoints)) {
      return [];
    }
    return manifest.endpoints
      .map((endpoint) => endpoint?.name)
      .filter(
        (name) =>
          typeof name === "string" &&
          name !== "." &&
          name !== ".." &&
          /^[A-Za-z0-9._-]+$/.test(name)
      );
  } catch {
    // A malformed generated manifest must not authorize deleting arbitrary
    // workspace files. The new manifest will repair it on this build.
    return [];
  }
}

function retireRemovedEndpoints(previousNames, built) {
  const current = new Set(built.map((endpoint) => endpoint.name));
  for (const name of previousNames) {
    if (!current.has(name)) {
      rmSync(join(outputDir, name + ".js"), { force: true });
      rmSync(join(confDir, "endpoint-" + name + ".json"), { force: true });
      rmSync(join(openapiDir, name + ".openapi.json"), { force: true });
    }
  }
}

function confOutputs(built) {
  return built.map((endpoint) => ({
    path: join(confDir, "endpoint-" + endpoint.name + ".json"),
    content:
      JSON.stringify(
        {
          "//": "@generated by `fo build` from typescript/src/endpoints/" +
            endpoint.name + ".ts — DO NOT EDIT.",
          type: "text/javascript",
          file: endpoint.name + ".js",
        },
        null,
        2
      ) + "\n",
  }));
}

function openApiOutputs(built, toOpenApi) {
  return built.map((endpoint) => {
    const document = toOpenApi(endpoint.definition, {
      title: endpoint.definition.summary ?? endpoint.name,
    });
    return {
      path: join(openapiDir, endpoint.name + ".openapi.json"),
      content: JSON.stringify(document, null, 2) + "\n",
    };
  });
}

/**
 * Regenerate src/generated/managed.ts, if there is a managed.json to read.
 *
 * Runs BEFORE the type-check, because the endpoints being checked import from
 * it. An ABSENT managed.json leaves any existing generated file alone: the
 * file is committed so a fresh clone type-checks without a cluster, and
 * deleting it because nobody has exported yet would break exactly that.
 */
function generateManaged() {
  if (!existsSync(managedJsonPath)) {
    return;
  }
  const managed = JSON.parse(readFileSync(managedJsonPath, "utf8"));
  const content = generateManagedTypes(managed);
  if (existsSync(managedTypesPath) && readFileSync(managedTypesPath, "utf8") === content) {
    return;
  }
  mkdirSync(generatedDir, { recursive: true });
  atomicWrite(managedTypesPath, content);
  const count = Array.isArray(managed.objects) ? managed.objects.length : 0;
  console.log(
    "generated src/generated/managed.ts (" + count + " managed objects)"
  );
}

async function run() {
  generateManaged();
  // Cleared every generation, not just on one-shot builds: `readDefinition`
  // writes one `.mjs` per endpoint here, so a long `--watch` session otherwise
  // accumulates a file per endpoint it has ever seen, including renamed and
  // deleted ones. They are cache-busted on import, so nothing reads a stale one
  // — they just pile up.
  rmSync(join(distDir, "meta"), { recursive: true, force: true });
  const entries = entryPoints();
  const previousNames = previouslyOwnedEndpointNames();
  const previousAmNames = previouslyOwnedAmScriptNames();
  const previousTaskNames = previouslyOwnedNames("tasks");
  // AN ABSENT `src/endpoints` IS NOT AN EMPTY ONE. Retirement deletes every
  // bundle the previous manifest owned, so it must be driven by a project that
  // says "no endpoints", not by a directory that happens not to be there right
  // now — a branch switch, an interrupted move, or a watch tick mid-rename would
  // otherwise wipe the lot and empty the manifest, silently and with exit 0.
  if (!skipTypeCheck) {
    typeCheck();
  }
  if (!existsSync(endpointsDir)) {
    console.log(
      "src/endpoints does not exist — kept the previous manifest and bundles; " +
        "create the directory (even empty) to retire them"
    );
    return;
  }

  // Build everything into memory first: a failure in the last endpoint must
  // not leave the earlier ones half-written on disk.
  const built = [];
  for (const entry of entries) {
    built.push(await buildEndpoint(entry));
  }
  const taskBuilt = [];
  for (const entry of taskEntryPoints()) {
    taskBuilt.push(await buildTask(entry));
  }
  const amBuilt = [];
  for (const entry of amEntryPoints()) {
    amBuilt.push(await buildAmScript(entry));
  }

  const toOpenApi = await loadOpenApiGenerator();

  // Prepare every fallible transformation before publishing any watched
  // output. Publication itself is a sequence of same-directory atomic renames;
  // the manifest is the final commit marker for the generation.
  const openApi = openApiOutputs(built, toOpenApi);
  const confs = confOutputs(built);
  const amScripts = amScriptOutputs(amBuilt);

  mkdirSync(outputDir, { recursive: true });
  mkdirSync(confDir, { recursive: true });
  mkdirSync(openapiDir, { recursive: true });
  if (amScripts.length > 0) {
    mkdirSync(amScriptsDir, { recursive: true });
  }
  for (const endpoint of [...built, ...taskBuilt]) {
    atomicWrite(join(outputDir, endpoint.name + ".js"), endpoint.code);
  }
  for (const output of [...confs, ...openApi, ...amScripts]) {
    atomicWrite(output.path, output.content);
  }
  retireRemovedEndpoints(previousNames, built);
  retireRemovedAmScripts(previousAmNames, amBuilt);
  retireRemovedTasks(previousTaskNames, taskBuilt);
  writeManifest(built, amBuilt, taskBuilt);

  if (built.length === 0) {
    console.log("no endpoints in src/endpoints — retired generated endpoints");
  }

  for (const task of taskBuilt) {
    console.log(
      "built " + task.name + " (IDM task) -> idm/script/" + task.name + ".js"
    );
  }

  for (const script of amBuilt) {
    console.log(
      "built " + script.name + " (AM " + script.definition.context +
        ", " + script.definition.outcomes.length + " outcomes) -> amster/config/realms/root/Scripts/" +
        script.name + ".json"
    );
  }

  for (const endpoint of built) {
    const bytes = Buffer.byteLength(endpoint.code, "utf8");
    console.log(
      "built " +
        endpoint.name +
        " (" +
        endpoint.definition.routes.length +
        " routes, " +
        Math.round(bytes / 1024) +
        " KB) -> idm/script/" +
        endpoint.name +
        ".js + idm/conf/endpoint-" +
        endpoint.name +
        ".json"
    );
  }
}

/** Bundle the framework's OpenAPI generator so this tool can call it. */
async function loadOpenApiGenerator() {
  const source = join(projectRoot, "framework", "openapi.ts");
  const esm = await bundle(source, "esm", undefined);
  mkdirSync(join(distDir, "meta"), { recursive: true });
  const path = join(distDir, "meta", "__openapi.mjs");
  writeFileSync(path, esm, "utf8");
  const module = await import(pathToFileURL(path).href + "?t=" + Date.now());
  return module.toOpenApi;
}

// ---------------------------------------------------------------------------
// Entry
// ---------------------------------------------------------------------------

async function once() {
  try {
    await run();
    return true;
  } catch (error) {
    console.error(
      "build failed: " + (error instanceof Error ? error.message : error)
    );
    return false;
  }
}

if (typeCheckOnly) {
  // `npm run type-check`. Same function, same program list, no emit.
  //
  // It regenerates managed types FIRST, exactly as the build does. It did not,
  // and the two paths then answered different questions: a changed
  // `managed.json` meant the type-check ran against a stale `src/generated/`
  // while the build regenerated it and emitted against the new one.
  try {
    generateManaged();
    typeCheck();
    process.exit(0);
  } catch (error) {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  }
} else if (watchMode) {
  const { watch } = await import("node:fs");
  let pending = null;
  let building = false;
  let rerun = false;
  const buildLatest = async () => {
    if (building) {
      rerun = true;
      return;
    }
    building = true;
    try {
      do {
        rerun = false;
        await once();
      } while (rerun);
    } finally {
      building = false;
    }
  };
  const trigger = () => {
    if (pending !== null) {
      clearTimeout(pending);
    }
    pending = setTimeout(() => {
      pending = null;
      void buildLatest();
    }, 250);
  };
  await buildLatest();
  for (const dir of ["src", "framework"]) {
    const target = join(projectRoot, dir);
    if (existsSync(target)) {
      watch(target, { recursive: true }, trigger);
    }
  }
  console.log("watching src/ and framework/ — Ctrl-C to stop");
} else {
  const ok = await once();
  process.exit(ok ? 0 : 1);
}
