// The behavioural half of the engine proof: does what Babel ACTUALLY emits
// still run on the engine?
//
// The six `emit:*` checks this replaces were hand-written ES5 that mirrored
// what Babel's output was assumed to look like -- the "spread" case was a
// literal `[].concat(...)` and the "for-of" case was a raw `for...of`. They
// tested a guess about the pipeline, not the pipeline. A preset-env upgrade
// could start emitting `_toConsumableArray` (which needs `Symbol.iterator`
// and `Array.from`) and every one of them would have stayed green.
//
// So this file is TypeScript, and it goes through the SAME esbuild + Babel
// path as a real endpoint. The committed result is
// `framework/engine-emit-probe.js`; `tests/emit-probe.test.mjs` regenerates it
// and fails if it has drifted from the pipeline, and `fo doctor --engines`
// executes exactly that file on both engines.
//
// Each case gets its own try, so one failure reports one key rather than
// aborting the run. Keep the cases to constructs an author would plausibly
// write: the point is coverage of Babel's HELPERS, not of the language.
//
// Managed file -- regenerated by `fo upgrade`.

type Report = string[];

function record(out: Report, key: string, run: () => boolean): void {
  try {
    out.push((run() ? "+" : "-") + "emit:" + key);
  } catch {
    out.push("-emit:" + key);
  }
}

/**
 * Subclassing a native, which Babel lowers through `_wrapNativeSuper` and
 * `_construct`.
 *
 * WHY THESE ARE MEASURED RATHER THAN REASONED ABOUT. `_construct` prefers
 * `Reflect.construct`, and this engine has no `Reflect` -- but it FALLS BACK to
 * `Function#bind` plus `Object.setPrototypeOf`, and both of those are recorded
 * present. "No Reflect, therefore every native subclass breaks" simply does not
 * follow, and the project asserted it anyway on the strength of one measurement
 * of `Error`.
 *
 * Both cases fail, and finer-grained probes said why -- differently for each:
 *
 *   - `new MyError("x")` constructs and `instanceof Error` is true, but
 *     `instanceof MyError` is FALSE. The prototype is not restored.
 *   - `new MyMap()` does not construct at all. It throws before anything else
 *     can be asked.
 *
 * Which is a stronger reason to ban the pattern than the one that was written
 * down, and a reason that is now a live measurement rather than an inference.
 */
class MyMap extends Map<string, number> {
  double(key: string): number {
    return (this.get(key) ?? 0) * 2;
  }
}

class MyError extends Error {}

class Base {
  constructor(readonly tag: string) {}
  describe(): string {
    return "base:" + this.tag;
  }
}

class Derived extends Base {
  override describe(): string {
    return "derived:" + super.describe();
  }
  get shouted(): string {
    return this.tag.toUpperCase();
  }
  static of(tag: string): Derived {
    return new Derived(tag);
  }
}

export default function probe(): Report {
  const out: Report = [];

  // `_createForOfIteratorHelper`, which reaches for Symbol.iterator and falls
  // back to an index loop. The array and the Set take different branches.
  record(out, "for-of-array", () => {
    let total = 0;
    for (const value of [1, 2, 3]) total += value;
    return total === 6;
  });
  record(out, "for-of-set", () => {
    let seen = "";
    for (const value of new Set(["a", "b"])) seen += value;
    return seen === "ab";
  });
  record(out, "for-of-map-entries", () => {
    const map = new Map([["k", 1]]);
    let seen = "";
    for (const [key, value] of map) seen += key + value;
    return seen === "k1";
  });

  // `_toConsumableArray`: array spread is NOT `concat` once an iterable is
  // involved, which is what the hand-written check assumed.
  record(out, "spread-array", () => [...[1, 2], ...[3, 4]].length === 4);
  record(out, "spread-iterable", () => [...new Set([1, 2, 2, 3])].length === 3);

  // `_objectSpread` -> Object.keys, getOwnPropertySymbols,
  // getOwnPropertyDescriptor(s), defineProperty.
  record(out, "spread-object", () => {
    const base = { a: 1, b: 2 };
    const merged = { ...base, b: 3 };
    return merged.a === 1 && merged.b === 3;
  });

  // `_slicedToArray` and the object-destructuring lowering.
  record(out, "destructure-array", () => {
    const [first, ...rest] = [10, 20, 30];
    return first === 10 && rest.length === 2;
  });
  record(out, "destructure-object", () => {
    const { a, ...others } = { a: 1, b: 2, c: 3 };
    return a === 1 && Object.keys(others).length === 2;
  });

  // Default and rest parameters.
  record(out, "params-default-rest", () => {
    const f = (a = 1, ...more: number[]): number => a + more.length;
    return f() === 1 && f(2, 9, 9) === 4;
  });

  // Classes: `_inherits`, `_createClass`, getters, statics, `super`.
  record(out, "class-inheritance", () => {
    const d = Derived.of("x");
    return d.describe() === "derived:base:x" && d.shouted === "X";
  });

  // Template literals and computed keys.
  record(out, "template-literal", () => {
    const who = "world";
    return `hello ${who}` === "hello world";
  });
  record(out, "computed-key", () => {
    const k = "dyn";
    return { [k + "1"]: true }["dyn1"] === true;
  });

  // Native subclassing. Split per native, because the answer is not obviously
  // the same for all of them: `Error` is special-cased in every engine.
  record(out, "subclass-map", () => {
    const m = new MyMap();
    m.set("a", 2);
    return m instanceof MyMap && m instanceof Map && m.double("a") === 4;
  });
  record(out, "subclass-error", () => {
    const e = new MyError("boom");
    return e instanceof MyError && e instanceof Error && e.message === "boom";
  });

  // Optional chaining and nullish coalescing lower to plain conditionals, but
  // only if the pipeline actually lowers them.
  record(out, "optional-chaining", () => {
    const maybe: { inner?: { value: number } } = {};
    return (maybe.inner?.value ?? 7) === 7;
  });

  return out;
}
