// Generates `framework/engine-emit-probe.js` from `tools/emit-corpus.ts`.
//
// The corpus goes through `pipeline.mjs` -- the same esbuild bundle and the
// same Babel downlevel a deployed endpoint gets -- so the thing the engines
// are asked to run is genuinely the pipeline's output rather than somebody's
// idea of what the pipeline produces.
//
// The result is COMMITTED, for two reasons. `fo doctor --engines` needs it
// without a node_modules tree, and a committed artefact is diffable: a Babel
// or esbuild bump that changes the emitted helpers shows up as a reviewable
// change rather than as a silent shift in what the probe proves.
//
//   node tools/emit-probe.mjs           regenerate the committed file
//   node tools/emit-probe.mjs --check   fail if it has drifted (used by tests)
//
// Managed file -- regenerated by `fo upgrade`.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { GLOBAL_NAME, bundle, downlevel } from "./pipeline.mjs";

const projectRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const corpusPath = join(projectRoot, "tools", "emit-corpus.ts");
export const emitProbePath = join(
  projectRoot,
  "framework",
  "engine-emit-probe.js",
);

const HEADER = [
  "// @generated from tools/emit-corpus.ts by tools/emit-probe.mjs -- DO NOT EDIT.",
  "//",
  "// The real output of the real pipeline: esbuild bundle, then Babel to ES5",
  "// with the same preset-env settings a deployed endpoint gets. `fo doctor",
  "// --engines` runs this verbatim on PingAM and PingIDM, so the `emit:*` keys",
  "// in engine-surface.json record whether OUR OUTPUT works on the engine, not",
  "// whether a hand-written approximation of it does.",
  "//",
  "// Regenerate: node tools/emit-probe.mjs",
  "",
].join("\n");

/**
 * An ES5 expression evaluating to an array of `+emit:key` / `-emit:key`.
 *
 * Wrapped so the caller can splice it into the larger probe: the corpus is an
 * IIFE assigned to `GLOBAL_NAME`, and calling its default export is what
 * produces the report.
 */
export async function generate() {
  const iife = await bundle(corpusPath, "iife", GLOBAL_NAME);
  const code = downlevel(iife, "emit-corpus");
  return HEADER + "(function () {\n" + code + "\nreturn " + GLOBAL_NAME +
    ".default();\n})()\n";
}

export function committed() {
  return readFileSync(emitProbePath, "utf8");
}

if (process.argv[2] === "--check") {
  const fresh = await generate();
  if (fresh !== committed()) {
    process.stderr.write(
      "framework/engine-emit-probe.js is not what the pipeline produces " +
        "today.\nRegenerate with `node tools/emit-probe.mjs`, then re-run " +
        "`fo doctor --engines --record` against a running stack: the " +
        "behavioural half of the engine proof is only worth anything if the " +
        "engines ran THIS output.\n",
    );
    process.exit(1);
  }
  process.stdout.write("engine-emit-probe.js matches the pipeline\n");
} else if (process.argv[1]?.endsWith("emit-probe.mjs")) {
  writeFileSync(emitProbePath, await generate(), "utf8");
  process.stdout.write(
    "wrote framework/engine-emit-probe.js — now re-record with " +
      "`fo doctor --engines --record`\n",
  );
}
