// Using a builtin the engine does not have is a build failure.
//
// WHY THIS EXISTS. `engine-coverage.mjs` derives everything the pinned `lib`
// promises; the probe measures what the engines actually answer. Comparing
// them found 234 declarations the lib admits and Rhino does not have --
// almost all of `Float32Array` and its siblings, plus `RegExp#flags`,
// `Date#[Symbol.toPrimitive]` and a handful more.
//
// None of that can be removed from the type system. `lib.es5.d.ts` is
// monolithic: the typed arrays arrive with `Date` and `JSON`, and TypeScript
// has no way to un-declare an interface member. Declaration merging can add a
// member; it cannot subtract one, and redeclaring it as `never` conflicts with
// the original rather than removing it. So the old gate -- "no pinned lib
// entry may declare a builtin the engine lacks" -- is not something any real
// lib list can satisfy, and passing it only ever meant the measurement was too
// small to notice.
//
// The check that CAN hold is this one: nothing we compile may USE one. That
// turns `new Float32Array(8).map(f)` from code that type-checks, builds,
// deploys and throws in the middle of a request into a failed build, which is
// what the lib pin was supposed to buy in the first place.
//
// WHAT IT PROVES, EXACTLY. Direct, statically resolvable uses of a builtin in
// this package's own TypeScript are rejected before anything is emitted. It
// resolves four forms:
//
//   obj.member            property access
//   obj["member"]         element access with a literal or finite-union key
//   const { member } = o  binding patterns, including nested and parameters
//   ({ member } = o)      destructuring assignment
//
// and well-known symbol members (`Math[Symbol.toStringTag]`) in the element
// access form.
//
// WHAT IT DOES NOT PROVE -- the honest boundary, stated so nobody reads the
// green tick as more than it is:
//
//   - Dynamic access. `obj[key]` where `key` is `string` names no member the
//     compiler can resolve, so nothing is checked.
//   - Structural erasure. `function f<T extends { map(...): U }>(x: T)` sees a
//     structural constraint, not `Float32Array`; the call site that supplies
//     the typed array IS caught, but a cast or `any` in between is not.
//   - Bundled dependency code. The program sees a dependency's declarations,
//     never its executable JavaScript, so a builtin used inside a node_modules
//     implementation is invisible here. This package has no runtime
//     dependencies today, which is what keeps that boundary theoretical.
//
// Each program is checked against ITS OWN engine. They are nearly the same
// Rhino, but the audit found two keys where they differ, so "the engines
// agree" is an observation about the current measurement rather than a
// property to build on.
//
// Managed file - regenerated by `fo upgrade`.

import { readFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

import ts from "typescript";

const projectRoot = join(dirname(fileURLToPath(import.meta.url)), "..");

/**
 * The interface a member was declared on, as a surface-key holder.
 *
 * `ArrayConstructor` holds statics (`Array.from`), `Array` holds prototype
 * members (`Array#map`), and a singleton like `Math` holds what reads as a
 * static. Returns undefined for anything not declared in a lib file, which is
 * the project's own code and none of this check's business.
 */
function holderOf(declaration, isLibFile) {
  const parent = declaration.parent;
  if (parent === undefined || !ts.isInterfaceDeclaration(parent)) return undefined;
  if (!isLibFile(parent.getSourceFile())) return undefined;

  const name = parent.name.text;
  if (name.endsWith("Constructor")) {
    return { holder: name.slice(0, -"Constructor".length), separator: "." };
  }
  // `Math` and `JSON` are objects, not constructors: their members are reached
  // as `Math.floor`, so they key like statics even though the interface is the
  // instance one.
  if (name === "Math" || name === "JSON") return { holder: name, separator: "." };
  return { holder: name, separator: "#" };
}

/** A global declared by a lib file, as `g:Name`. */
function globalKeyOf(declaration, isLibFile) {
  if (!ts.isVariableDeclaration(declaration) && !ts.isFunctionDeclaration(declaration)) {
    return undefined;
  }
  if (!isLibFile(declaration.getSourceFile())) return undefined;
  if (declaration.name === undefined || !ts.isIdentifier(declaration.name)) {
    return undefined;
  }
  return `g:${declaration.name.text}`;
}

/**
 * The surface key a symbol corresponds to, or undefined if it is not a
 * builtin the probe knows about.
 */
function keyForSymbol(symbol, memberName, isLibFile) {
  for (const declaration of symbol.declarations ?? []) {
    const global = globalKeyOf(declaration, isLibFile);
    if (global !== undefined) return global;
    const holder = holderOf(declaration, isLibFile);
    if (holder !== undefined) {
      return `${holder.holder}${holder.separator}${memberName}`;
    }
  }
  return undefined;
}

/**
 * The surface's spelling of a symbol's name.
 *
 * A well-known symbol member is `__@toStringTag@18` internally -- the trailing
 * id is the declaration's, so it is not stable and must not reach a key. The
 * surface writes these as `[Symbol.toStringTag]`.
 */
function surfaceMemberName(symbol) {
  const escaped = String(symbol.escapedName);
  const wellKnown = /^__@([A-Za-z]+)@\d+$/.exec(escaped);
  if (wellKnown) return `[Symbol.${wellKnown[1]}]`;
  if (escaped.startsWith("__")) return undefined; // some other internal name
  return escaped;
}

/**
 * Property symbols an element access could be reaching.
 *
 * A literal key names one; a finite union of literals names each of them; a
 * unique symbol type (`Symbol.iterator`) names the late-bound member. Anything
 * wider -- `string`, `number`, a computed name -- resolves to nothing, which is
 * the dynamic-access boundary the header describes.
 */
function elementAccessProperties(node, checker) {
  if (node.argumentExpression === undefined) return [];
  const receiver = checker.getTypeAtLocation(node.expression);
  const argument = checker.getTypeAtLocation(node.argumentExpression);
  const candidates = argument.isUnion() ? argument.types : [argument];

  const properties = checker.getPropertiesOfType(receiver);
  const found = [];
  for (const candidate of candidates) {
    let escaped;
    if (candidate.isStringLiteral()) {
      escaped = candidate.value;
    } else if (candidate.flags & ts.TypeFlags.UniqueESSymbol) {
      escaped = String(candidate.escapedName);
    } else {
      continue;
    }
    const property = properties.find((p) => String(p.escapedName) === escaped);
    if (property !== undefined) found.push(property);
  }
  return found;
}

/**
 * The property an object binding element reads.
 *
 * `const { map } = arr` and `const { map: renamed } = arr` both read `map` off
 * the type of the pattern, which is the type of whatever is being destructured
 * -- an initialiser, a parameter, or an enclosing binding element.
 */
function bindingElementProperty(node, checker) {
  if (!ts.isObjectBindingPattern(node.parent)) return undefined;
  const name = node.propertyName ?? node.name;
  if (!ts.isIdentifier(name) && !ts.isStringLiteral(name)) return undefined;
  const source = checker.getTypeAtLocation(node.parent);
  return checker.getPropertyOfType(source, name.text);
}

/**
 * Whether this object-literal member really is a destructuring TARGET.
 *
 * `getPropertySymbolOfDestructuringAssignment` asserts rather than returning
 * undefined -- handed a member of an ordinary object literal it throws
 * "Invalid cast" from deep inside the checker -- so the caller has to know
 * before it asks. Walks out through nested patterns to the `=` (or the
 * `for (... of ...)` binding) that makes the whole literal an assignment.
 */
function isDestructuringTarget(member) {
  let node = member.parent; // the ObjectLiteralExpression
  for (;;) {
    const parent = node.parent;
    if (parent === undefined) return false;
    if (ts.isParenthesizedExpression(parent)) {
      node = parent;
    } else if (ts.isBinaryExpression(parent)) {
      return (
        parent.operatorToken.kind === ts.SyntaxKind.EqualsToken &&
        parent.left === node
      );
    } else if (ts.isForOfStatement(parent) || ts.isForInStatement(parent)) {
      return parent.initializer === node;
    } else if (
      ts.isPropertyAssignment(parent) ||
      ts.isShorthandPropertyAssignment(parent) ||
      ts.isSpreadAssignment(parent) ||
      ts.isSpreadElement(parent) ||
      ts.isArrayLiteralExpression(parent) ||
      ts.isObjectLiteralExpression(parent)
    ) {
      // A nested pattern: keep climbing towards the outermost literal.
      node = parent;
    } else {
      return false;
    }
  }
}

function loadProgram(tsconfigName) {
  const configPath = join(projectRoot, tsconfigName);
  const read = ts.readConfigFile(configPath, (p) => readFileSync(p, "utf8"));
  if (read.error) {
    throw new Error(
      `${tsconfigName}: ${ts.flattenDiagnosticMessageText(read.error.messageText, " ")}`,
    );
  }
  // Relative to the CONFIG, not to the package: a tsconfig in a subdirectory
  // resolves its own `include` from where it sits.
  const parsed = ts.parseJsonConfigFileContent(
    read.config,
    ts.sys,
    dirname(configPath),
  );
  if (parsed.fileNames.length === 0) {
    throw new Error(`${tsconfigName}: matched no files`);
  }
  return ts.createProgram({
    rootNames: parsed.fileNames,
    options: { ...parsed.options, noEmit: true },
  });
}

/**
 * Every use, in the given program, of a builtin recorded absent on that
 * engine.
 */
export function checkEngineUsage(tsconfigName, engineSurface) {
  const program = loadProgram(tsconfigName);
  const checker = program.getTypeChecker();
  const findings = [];

  // Ask the PROGRAM which files are lib files rather than matching a path.
  // `node_modules` is a symlink into the nix store here, so the lib TypeScript
  // actually loaded lives under /nix/store/... - an earlier version of this
  // compared against `<project>/node_modules/typescript/lib`, matched nothing,
  // and reported a clean result for a file that used `Float32Array#map`.
  const libFiles = new Set(
    program.getSourceFiles().filter((f) => program.isSourceFileDefaultLibrary(f)),
  );
  const isLibFile = (sourceFile) => libFiles.has(sourceFile);
  if (libFiles.size === 0) {
    throw new Error(
      `${tsconfigName}: the program loaded no default-library files, so this ` +
        "check could not detect anything. Refusing to report a clean result.",
    );
  }

  const absent = (key) => engineSurface[key] === false;
  const seen = new Set();

  function report(node, key) {
    const sourceFile = node.getSourceFile();
    const { line, character } = sourceFile.getLineAndCharacterOfPosition(
      node.getStart(sourceFile),
    );
    // One finding per position and key: a nested binding element is visited
    // once, but a destructuring assignment target is reachable two ways.
    const at = `${sourceFile.fileName}:${line}:${character}:${key}`;
    if (seen.has(at)) return;
    seen.add(at);
    findings.push({
      file: relative(projectRoot, sourceFile.fileName),
      line: line + 1,
      column: character + 1,
      key,
    });
  }

  /** Report `symbol` if it is a builtin this engine lacks. */
  function consider(node, symbol, memberName) {
    if (symbol === undefined) return;
    const name = memberName ?? surfaceMemberName(symbol);
    if (name === undefined) return;
    const key = keyForSymbol(symbol, name, isLibFile);
    if (key !== undefined && absent(key)) report(node, key);
  }

  for (const sourceFile of program.getSourceFiles()) {
    if (sourceFile.isDeclarationFile) continue;

    const visit = (node) => {
      if (ts.isPropertyAccessExpression(node)) {
        consider(node, checker.getSymbolAtLocation(node.name), node.name.text);
      } else if (ts.isElementAccessExpression(node)) {
        for (const property of elementAccessProperties(node, checker)) {
          consider(node, property, undefined);
        }
      } else if (ts.isBindingElement(node)) {
        consider(node, bindingElementProperty(node, checker), undefined);
      } else if (
        ts.isShorthandPropertyAssignment(node) ||
        ts.isPropertyAssignment(node)
      ) {
        // `({ map } = arr)` and `({ map: renamed } = arr)`.
        if (isDestructuringTarget(node)) {
          consider(
            node,
            checker.getPropertySymbolOfDestructuringAssignment(node.name),
            undefined,
          );
        }
      } else if (ts.isIdentifier(node) && !ts.isPropertyAccessExpression(node.parent)) {
        // A bare global: `Float32Array`, `Proxy`. Skipped when it is the
        // `.name` half of a property access, which the branch above handles.
        const symbol = checker.getSymbolAtLocation(node);
        if (symbol) {
          const key = keyForSymbol(symbol, node.text, isLibFile);
          if (key !== undefined && key.startsWith("g:") && absent(key)) {
            report(node, key);
          }
        }
      }
      ts.forEachChild(node, visit);
    };
    ts.forEachChild(sourceFile, visit);
  }

  return findings;
}

export function formatFindings(tsconfigName, engine, findings, probedOn) {
  return findings
    .map(
      (f) =>
        `  ${f.file}:${f.line}:${f.column}  \`${f.key}\` is not in ` +
        `${engine === "am" ? "PingAM" : "PingIDM"}'s script engine ` +
        `(probed ${probedOn}). Nothing polyfills it, so this compiles ` +
        `and throws at runtime.`,
    )
    .join("\n");
}

/**
 * The programs whose output actually runs on a Ping script engine, and which
 * engine each one lands on.
 *
 * THE list, not a copy of it: `tools/build.mjs` and `tests/engine-lib.test.mjs`
 * both read this. `tsconfig.tests.json` is deliberately absent -- it runs on
 * node and is entitled to a modern lib.
 */
export const RUNTIME_PROGRAMS = [
  { tsconfig: "tsconfig.json", engine: "idm" },
  { tsconfig: "tsconfig.am.json", engine: "am" },
];

/**
 * Throw if any runtime program uses a builtin its engine lacks.
 *
 * Called from the type-check step of `tools/build.mjs`, BEFORE anything is
 * emitted. It lived only in a test once, and `npm run check` runs the build
 * before the tests -- so an absent builtin was written to
 * `platform/idm/script/` and the command failed afterwards, leaving output
 * that `fo sync` would happily push. A gate that fires after emission is not a
 * gate.
 */
export function assertNoAbsentBuiltinUses() {
  const surface = JSON.parse(
    readFileSync(join(projectRoot, "framework", "engine-surface.json"), "utf8"),
  );
  const messages = [];
  for (const { tsconfig, engine } of RUNTIME_PROGRAMS) {
    const findings = checkEngineUsage(tsconfig, surface[engine]);
    if (findings.length > 0) {
      messages.push(
        `${tsconfig} uses ${findings.length} builtin(s) this engine does not ` +
          "have:\n" +
          formatFindings(tsconfig, engine, findings, surface.probedOn),
      );
    }
  }
  if (messages.length > 0) throw new Error(messages.join("\n\n"));
}
