// Using a builtin the engine does not have is a build failure.
//
// WHY THIS EXISTS. `engine-coverage.mjs` derives everything the pinned `lib`
// promises; the probe measures what the engines actually answer. Comparing
// them found 234 declarations the lib admits and Rhino does not have --
// almost all of `Float32Array` and its siblings, plus `RegExp#flags`,
// `Date#[Symbol.toPrimitive]` and a handful more.
//
// None of that can be removed from the type system. `lib.es5.d.ts` is
// monolithic: the typed arrays arrive with `Date` and `JSON`, and TypeScript
// has no way to un-declare an interface member. Declaration merging can add a
// member; it cannot subtract one, and redeclaring it as `never` conflicts with
// the original rather than removing it. So the old gate -- "no pinned lib
// entry may declare a builtin the engine lacks" -- is not something any real
// lib list can satisfy, and passing it only ever meant the measurement was too
// small to notice.
//
// The check that CAN hold is this one: nothing we compile may USE one. That
// turns `new Float32Array(8).map(f)` from code that type-checks, builds,
// deploys and throws in the middle of a request into a failed build, which is
// what the lib pin was supposed to buy in the first place.
//
// WHAT IT PROVES, EXACTLY. Direct, statically resolvable uses of a builtin in
// this package's own TypeScript are rejected before anything is emitted. It
// resolves four forms:
//
//   obj.member                 property access
//   obj["member"]              element access, literal or finite-union key
//   const { member } = o       binding patterns: nested, renamed, parameters,
//   const { ["member"]: m } = o  and computed names that are literal
//   ({ member } = o)           destructuring assignment, including "quoted"
//                              and [computed] names
//
// and well-known symbol members (`Math[Symbol.toStringTag]`, and
// `const { [Symbol.iterator]: it } = o`).
//
// WHAT IT DOES NOT PROVE -- the honest boundary, stated so nobody reads the
// green tick as more than it is:
//
//   - Dynamic access. `obj[key]` where `key` is `string` names no member the
//     compiler can resolve, so nothing is checked. A COMPUTED key that is a
//     literal or a well-known symbol is resolved; a variable one is not.
//   - Array-pattern and `for...of` destructuring positions in an ASSIGNMENT
//     pattern with a non-shorthand key. The binding-pattern forms are covered;
//     `([{ "map": m }] = xs)` is not.
//   - Structural erasure. `function f<T extends { map(...): U }>(x: T)` sees a
//     structural constraint, not `Float32Array`; the call site that supplies
//     the typed array IS caught, but a cast or `any` in between is not.
//   - Bundled dependency code. The program sees a dependency's declarations,
//     never its executable JavaScript, so a builtin used inside a node_modules
//     implementation is invisible here. This package has no runtime
//     dependencies today, which is what keeps that boundary theoretical.
//
// Each program is checked against ITS OWN engine. They are nearly the same
// Rhino, but the audit found two keys where they differ, so "the engines
// agree" is an observation about the current measurement rather than a
// property to build on.
//
// Managed file - regenerated by `fo upgrade`.

import { readFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

import ts from "typescript";

const projectRoot = join(dirname(fileURLToPath(import.meta.url)), "..");

/**
 * The interface a member was declared on, as a surface-key holder.
 *
 * `ArrayConstructor` holds statics (`Array.from`), `Array` holds prototype
 * members (`Array#map`), and a singleton like `Math` holds what reads as a
 * static. Returns undefined for anything not declared in a lib file, which is
 * the project's own code and none of this check's business.
 */
function holderOf(declaration, isLibFile) {
  const parent = declaration.parent;
  if (parent === undefined || !ts.isInterfaceDeclaration(parent)) return undefined;
  if (!isLibFile(parent.getSourceFile())) return undefined;

  const name = parent.name.text;
  if (name.endsWith("Constructor")) {
    return { holder: name.slice(0, -"Constructor".length), separator: "." };
  }
  // `Math` and `JSON` are objects, not constructors: their members are reached
  // as `Math.floor`, so they key like statics even though the interface is the
  // instance one.
  if (name === "Math" || name === "JSON") return { holder: name, separator: "." };
  return { holder: name, separator: "#" };
}

/** A global declared by a lib file, as `g:Name`. */
function globalKeyOf(declaration, isLibFile) {
  if (!ts.isVariableDeclaration(declaration) && !ts.isFunctionDeclaration(declaration)) {
    return undefined;
  }
  if (!isLibFile(declaration.getSourceFile())) return undefined;
  if (declaration.name === undefined || !ts.isIdentifier(declaration.name)) {
    return undefined;
  }
  return `g:${declaration.name.text}`;
}

/**
 * The surface key a symbol corresponds to, or undefined if it is not a
 * builtin the probe knows about.
 */
function keyForSymbol(symbol, memberName, isLibFile) {
  for (const declaration of symbol.declarations ?? []) {
    const global = globalKeyOf(declaration, isLibFile);
    if (global !== undefined) return global;
    const holder = holderOf(declaration, isLibFile);
    if (holder !== undefined) {
      return `${holder.holder}${holder.separator}${memberName}`;
    }
  }
  return undefined;
}

/**
 * The surface's spelling of a symbol's name.
 *
 * A well-known symbol member is `__@toStringTag@18` internally -- the trailing
 * id is the declaration's, so it is not stable and must not reach a key. The
 * surface writes these as `[Symbol.toStringTag]`.
 */
function surfaceMemberName(symbol) {
  const escaped = String(symbol.escapedName);
  const wellKnown = /^__@([A-Za-z]+)@\d+$/.exec(escaped);
  if (wellKnown) return `[Symbol.${wellKnown[1]}]`;
  if (escaped.startsWith("__")) return undefined; // some other internal name
  return escaped;
}

/**
 * Property symbols an element access could be reaching.
 *
 * A literal key names one; a finite union of literals names each of them; a
 * unique symbol type (`Symbol.iterator`) names the late-bound member. Anything
 * wider -- `string`, `number`, a computed name -- resolves to nothing, which is
 * the dynamic-access boundary the header describes.
 */
function elementAccessProperties(node, checker) {
  if (node.argumentExpression === undefined) return [];
  const receiver = checker.getTypeAtLocation(node.expression);
  const argument = checker.getTypeAtLocation(node.argumentExpression);
  const candidates = argument.isUnion() ? argument.types : [argument];

  const found = [];
  for (const candidate of candidates) {
    let escaped;
    if (candidate.isStringLiteral()) {
      escaped = candidate.value;
    } else if (candidate.flags & ts.TypeFlags.UniqueESSymbol) {
      escaped = String(candidate.escapedName);
    } else {
      continue;
    }
    const property = propertyByEscapedName(receiver, escaped, checker);
    if (property !== undefined) found.push(property);
  }
  return found;
}

/**
 * The escaped property name a destructuring key refers to, if it is knowable.
 *
 * `{ map }`, `{ map: renamed }`, `{ "map": renamed }` and
 * `{ ["map"]: renamed }` all read the same property, and so does
 * `{ [Symbol.iterator]: it }`. A computed name that is not a literal -- a
 * variable, a template with a hole -- names nothing resolvable and is part of
 * the dynamic-access boundary.
 */
function destructuringKey(name, checker) {
  if (ts.isIdentifier(name) || ts.isStringLiteral(name)) return name.text;
  if (ts.isNumericLiteral(name)) return name.text;
  if (!ts.isComputedPropertyName(name)) return undefined;
  const type = checker.getTypeAtLocation(name.expression);
  if (type.isStringLiteral()) return type.value;
  if (type.flags & ts.TypeFlags.UniqueESSymbol) return String(type.escapedName);
  return undefined;
}

/** Find a property on a type by its ESCAPED name, symbols included. */
function propertyByEscapedName(type, escaped, checker) {
  return checker
    .getPropertiesOfType(type)
    .find((p) => String(p.escapedName) === escaped);
}

/**
 * The property an object binding element reads.
 *
 * `const { map } = arr` and `const { map: renamed } = arr` both read `map` off
 * the type of the pattern, which is the type of whatever is being destructured
 * -- an initialiser, a parameter, or an enclosing binding element.
 */
function bindingElementProperty(node, checker) {
  if (!ts.isObjectBindingPattern(node.parent)) return undefined;
  const escaped = destructuringKey(node.propertyName ?? node.name, checker);
  if (escaped === undefined) return undefined;
  const source = checker.getTypeAtLocation(node.parent);
  return propertyByEscapedName(source, escaped, checker);
}

/**
 * The type being destructured by the pattern this member belongs to.
 *
 * Neither the literal's own type nor its contextual type is the answer -- in
 * `({ "map": m } = arr)` the literal types as `{ map: unknown }`, and looking
 * a property up on THAT finds a project declaration rather than the builtin.
 * So walk out to the `=`, take the type of its right-hand side, and descend
 * back down the keys collected on the way out.
 */
/** Whether this node sits where a destructuring pattern's member sits. */
function isPatternMember(node) {
  const parent = node.parent;
  return (
    parent !== undefined &&
    (ts.isPropertyAssignment(parent) ||
      ts.isShorthandPropertyAssignment(parent) ||
      ts.isSpreadAssignment(parent) ||
      ts.isSpreadElement(parent) ||
      ts.isArrayLiteralExpression(parent))
  );
}

function destructuringSourceType(member, checker) {
  const keys = [];
  let node = member.parent; // the ObjectLiteralExpression
  for (;;) {
    const parent = node.parent;
    if (parent === undefined) return undefined;
    if (ts.isParenthesizedExpression(parent)) {
      node = parent;
      continue;
    }
    if (
      ts.isBinaryExpression(parent) &&
      parent.operatorToken.kind === ts.SyntaxKind.EqualsToken &&
      parent.left === node
    ) {
      // NOT NECESSARILY THE ASSIGNMENT. `({ inner: { map: m } = fallback } =
      // rhs)` has an `=` inside the pattern too, and taking its right-hand
      // side resolved `map` against the FALLBACK -- which is project code, so
      // the builtin went unreported and the check looked clean. A default sits
      // in a pattern-member position; the real assignment does not.
      if (isPatternMember(parent)) {
        node = parent;
        continue;
      }
      let type = checker.getTypeAtLocation(parent.right);
      for (const key of keys.reverse()) {
        const property = propertyByEscapedName(type, key, checker);
        if (property === undefined) return undefined;
        // Non-nullable: a property that a default covers is still read off the
        // source when the source has it, and that is the reachable case.
        type = checker.getNonNullableType(
          checker.getTypeOfSymbolAtLocation(property, parent.right),
        );
      }
      return type;
    }
    if (
      ts.isPropertyAssignment(parent) &&
      ts.isObjectLiteralExpression(parent.parent)
    ) {
      const key = destructuringKey(parent.name, checker);
      if (key === undefined) return undefined;
      keys.push(key);
      node = parent.parent;
      continue;
    }
    // An array pattern position, a `for...of` binding, a default: the source
    // is not reachable this way, and guessing would be worse than declining.
    return undefined;
  }
}

/**
 * The property a destructuring-assignment member reads.
 *
 * `getPropertySymbolOfDestructuringAssignment` answers for a plain shorthand
 * and for `{ map: renamed }`, and returns undefined for a string-literal or
 * computed key -- so those are resolved against the source type instead.
 */
function destructuringAssignmentProperty(node, checker) {
  const direct = checker.getPropertySymbolOfDestructuringAssignment(node.name);
  if (direct !== undefined) return direct;
  const escaped = destructuringKey(node.name, checker);
  if (escaped === undefined) return undefined;
  const source = destructuringSourceType(node, checker);
  if (source === undefined) return undefined;
  return propertyByEscapedName(source, escaped, checker);
}

/**
 * Whether this object-literal member really is a destructuring TARGET.
 *
 * `getPropertySymbolOfDestructuringAssignment` asserts rather than returning
 * undefined -- handed a member of an ordinary object literal it throws
 * "Invalid cast" from deep inside the checker -- so the caller has to know
 * before it asks. Walks out through nested patterns to the `=` (or the
 * `for (... of ...)` binding) that makes the whole literal an assignment.
 */
function isDestructuringTarget(member) {
  let node = member.parent; // the ObjectLiteralExpression
  for (;;) {
    const parent = node.parent;
    if (parent === undefined) return false;
    if (ts.isParenthesizedExpression(parent)) {
      node = parent;
    } else if (ts.isBinaryExpression(parent)) {
      return (
        parent.operatorToken.kind === ts.SyntaxKind.EqualsToken &&
        parent.left === node
      );
    } else if (ts.isForOfStatement(parent) || ts.isForInStatement(parent)) {
      return parent.initializer === node;
    } else if (
      ts.isPropertyAssignment(parent) ||
      ts.isShorthandPropertyAssignment(parent) ||
      ts.isSpreadAssignment(parent) ||
      ts.isSpreadElement(parent) ||
      ts.isArrayLiteralExpression(parent) ||
      ts.isObjectLiteralExpression(parent)
    ) {
      // A nested pattern: keep climbing towards the outermost literal.
      node = parent;
    } else {
      return false;
    }
  }
}

function loadProgram(tsconfigName) {
  const configPath = join(projectRoot, tsconfigName);
  const read = ts.readConfigFile(configPath, (p) => readFileSync(p, "utf8"));
  if (read.error) {
    throw new Error(
      `${tsconfigName}: ${ts.flattenDiagnosticMessageText(read.error.messageText, " ")}`,
    );
  }
  // Relative to the CONFIG, not to the package: a tsconfig in a subdirectory
  // resolves its own `include` from where it sits.
  const parsed = ts.parseJsonConfigFileContent(
    read.config,
    ts.sys,
    dirname(configPath),
  );
  if (parsed.fileNames.length === 0) {
    throw new Error(`${tsconfigName}: matched no files`);
  }
  const program = ts.createProgram({
    rootNames: parsed.fileNames,
    options: { ...parsed.options, noEmit: true },
  });

  // FAIL CLOSED. This program is built by the `typescript` package, and the
  // build type-checks with tsgo -- two compilers over the same sources. If the
  // older one cannot understand the program (a syntax it does not have, an
  // option it does not know, a type error only it sees), every symbol
  // resolution below is guesswork and a clean result means nothing. It is the
  // signal that the two have drifted, so it stops the build rather than
  // reporting no findings.
  const diagnostics = [
    ...program.getConfigFileParsingDiagnostics(),
    ...program.getOptionsDiagnostics(),
    ...program.getGlobalDiagnostics(),
    ...program.getSyntacticDiagnostics(),
    ...program.getSemanticDiagnostics(),
  ];
  if (diagnostics.length > 0) {
    throw new Error(
      `${tsconfigName}: TypeScript ${ts.version} reports ${diagnostics.length} ` +
        "diagnostic(s) for this program, so the engine analysis below cannot " +
        "be trusted. The build type-checks with tsgo and this check runs on " +
        "the typescript package; a disagreement between them is the thing to " +
        "fix, not to route around.\n" +
        diagnostics
          .slice(0, 10)
          .map((d) => {
            const where =
              d.file && d.start !== undefined
                ? `${relative(projectRoot, d.file.fileName)}:${
                    d.file.getLineAndCharacterOfPosition(d.start).line + 1
                  }  `
                : "";
            return `  ${where}${ts.flattenDiagnosticMessageText(d.messageText, " ")}`;
          })
          .join("\n"),
    );
  }
  return program;
}

/**
 * Every use, in the given program, of a builtin recorded absent on that
 * engine.
 */
export function checkEngineUsage(tsconfigName, engineSurface) {
  const program = loadProgram(tsconfigName);
  const checker = program.getTypeChecker();
  const findings = [];

  // Ask the PROGRAM which files are lib files rather than matching a path.
  // `node_modules` is a symlink into the nix store here, so the lib TypeScript
  // actually loaded lives under /nix/store/... - an earlier version of this
  // compared against `<project>/node_modules/typescript/lib`, matched nothing,
  // and reported a clean result for a file that used `Float32Array#map`.
  const libFiles = new Set(
    program.getSourceFiles().filter((f) => program.isSourceFileDefaultLibrary(f)),
  );
  const isLibFile = (sourceFile) => libFiles.has(sourceFile);
  if (libFiles.size === 0) {
    throw new Error(
      `${tsconfigName}: the program loaded no default-library files, so this ` +
        "check could not detect anything. Refusing to report a clean result.",
    );
  }

  const absent = (key) => engineSurface[key] === false;
  const seen = new Set();

  function report(node, key) {
    const sourceFile = node.getSourceFile();
    const { line, character } = sourceFile.getLineAndCharacterOfPosition(
      node.getStart(sourceFile),
    );
    // One finding per position and key: a nested binding element is visited
    // once, but a destructuring assignment target is reachable two ways.
    const at = `${sourceFile.fileName}:${line}:${character}:${key}`;
    if (seen.has(at)) return;
    seen.add(at);
    findings.push({
      file: relative(projectRoot, sourceFile.fileName),
      line: line + 1,
      column: character + 1,
      key,
    });
  }

  /** Report `symbol` if it is a builtin this engine lacks. */
  function consider(node, symbol, memberName) {
    if (symbol === undefined) return;
    const name = memberName ?? surfaceMemberName(symbol);
    if (name === undefined) return;
    const key = keyForSymbol(symbol, name, isLibFile);
    if (key !== undefined && absent(key)) report(node, key);
  }

  for (const sourceFile of program.getSourceFiles()) {
    if (sourceFile.isDeclarationFile) continue;

    const visit = (node) => {
      if (ts.isPropertyAccessExpression(node)) {
        consider(node, checker.getSymbolAtLocation(node.name), node.name.text);
      } else if (ts.isElementAccessExpression(node)) {
        for (const property of elementAccessProperties(node, checker)) {
          consider(node, property, undefined);
        }
      } else if (ts.isBindingElement(node)) {
        consider(node, bindingElementProperty(node, checker), undefined);
      } else if (
        ts.isShorthandPropertyAssignment(node) ||
        ts.isPropertyAssignment(node)
      ) {
        // `({ map } = arr)`, `({ map: renamed } = arr)`, `({ "map": r } = arr)`.
        if (isDestructuringTarget(node)) {
          consider(node, destructuringAssignmentProperty(node, checker), undefined);
        }
      } else if (ts.isIdentifier(node) && !ts.isPropertyAccessExpression(node.parent)) {
        // A bare global: `Float32Array`, `Proxy`. Skipped when it is the
        // `.name` half of a property access, which the branch above handles.
        const symbol = checker.getSymbolAtLocation(node);
        if (symbol) {
          const key = keyForSymbol(symbol, node.text, isLibFile);
          if (key !== undefined && key.startsWith("g:") && absent(key)) {
            report(node, key);
          }
        }
      }
      ts.forEachChild(node, visit);
    };
    ts.forEachChild(sourceFile, visit);
  }

  return findings;
}

export function formatFindings(tsconfigName, engine, findings, probedOn) {
  return findings
    .map(
      (f) =>
        `  ${f.file}:${f.line}:${f.column}  \`${f.key}\` is not in ` +
        `${engine === "am" ? "PingAM" : "PingIDM"}'s script engine ` +
        `(probed ${probedOn}). Nothing polyfills it, so this compiles ` +
        `and throws at runtime.`,
    )
    .join("\n");
}

/**
 * Classes that extend a builtin constructor.
 *
 * WHY THIS IS TYPE-AWARE AND NOT A LINT SELECTOR. It was a lint selector, and
 * a syntactic one has both escapes and false positives: an alias
 * (`const E = Error; class X extends E`) or `globalThis.Error` walks past it,
 * while a project's own class named `Map` is caught for no reason. Resolving
 * the heritage expression through the checker and asking whether it lands on a
 * lib declaration answers the actual question.
 *
 * Babel lowers `class X extends Map` through `_wrapNativeSuper` and
 * `_construct`, and it was MEASURED to fail on both engines -- differently for
 * each. `new (class extends Error {})("x")` constructs and satisfies
 * `instanceof Error`, but not `instanceof` its own class; `new (class extends
 * Map {})()` throws outright. The old rationale ("Reflect is absent") does not
 * survive contact with the emitted helper, which falls back to `Function#bind`
 * and `Object.setPrototypeOf` -- both present. See `emit:subclass-error` and
 * `emit:subclass-map` in the surface, and `tools/emit-corpus.ts` for what they
 * run.
 */
function nativeSuperclassName(expression, checker, libFiles) {
  const declaredInLib = (symbol) =>
    (symbol?.declarations ?? []).some((d) => libFiles.has(d.getSourceFile()));

  const readable = (symbol) =>
    symbol.name.endsWith("Constructor")
      ? symbol.name.slice(0, -"Constructor".length)
      : symbol.name;

  // The identifier itself, following an import alias.
  let symbol = checker.getSymbolAtLocation(expression);
  if (symbol && symbol.flags & ts.SymbolFlags.Alias) {
    symbol = checker.getAliasedSymbol(symbol);
  }
  if (declaredInLib(symbol)) return symbol.name;

  // ...and failing that, what it EVALUATES to. `const Aliased = Error` and
  // `globalThis.Error` both leave the identifier declared in project code
  // while the value is still the native, which is what actually matters.
  //
  // Constituents, not just the type: `class X extends (c ? Error : Local)` has
  // type `ErrorConstructor | typeof Local`, and a union has no symbol of its
  // own -- so asking the top-level type returned nothing and the branch that
  // picks the native at runtime went unreported.
  const seen = new Set();
  const search = (type) => {
    if (type === undefined || seen.has(type)) return undefined;
    seen.add(type);
    const symbolOfType = type.getSymbol();
    if (declaredInLib(symbolOfType)) return readable(symbolOfType);
    if (type.isUnionOrIntersection()) {
      for (const constituent of type.types) {
        const found = search(constituent);
        if (found !== undefined) return found;
      }
    }
    return undefined;
  };
  return search(checker.getTypeAtLocation(expression));
}

export function findNativeSubclasses(tsconfigName) {
  const program = loadProgram(tsconfigName);
  const checker = program.getTypeChecker();
  const libFiles = new Set(
    program.getSourceFiles().filter((f) => program.isSourceFileDefaultLibrary(f)),
  );
  if (libFiles.size === 0) {
    throw new Error(
      `${tsconfigName}: no default-library files loaded; refusing to report ` +
        "a clean result.",
    );
  }

  const findings = [];
  for (const sourceFile of program.getSourceFiles()) {
    if (sourceFile.isDeclarationFile) continue;

    const visit = (node) => {
      if (
        (ts.isClassDeclaration(node) || ts.isClassExpression(node)) &&
        node.heritageClauses !== undefined
      ) {
        for (const clause of node.heritageClauses) {
          if (clause.token !== ts.SyntaxKind.ExtendsKeyword) continue;
          for (const type of clause.types) {
            const native = nativeSuperclassName(
              type.expression,
              checker,
              libFiles,
            );
            if (native === undefined) continue;
            const { line, character } =
              sourceFile.getLineAndCharacterOfPosition(node.getStart(sourceFile));
            findings.push({
              file: relative(projectRoot, sourceFile.fileName),
              line: line + 1,
              column: character + 1,
              native,
            });
          }
        }
      }
      ts.forEachChild(node, visit);
    };
    ts.forEachChild(sourceFile, visit);
  }
  return findings;
}

/**
 * The programs whose output actually runs on a Ping script engine, and which
 * engine each one lands on.
 *
 * THE list, not a copy of it: `tools/build.mjs` and `tests/engine-lib.test.mjs`
 * both read this. `tsconfig.tests.json` is deliberately absent -- it runs on
 * node and is entitled to a modern lib.
 */
export const RUNTIME_PROGRAMS = [
  { tsconfig: "tsconfig.json", engine: "idm" },
  { tsconfig: "tsconfig.am.json", engine: "am" },
];

/**
 * Throw if any runtime program uses a builtin its engine lacks.
 *
 * Called from the type-check step of `tools/build.mjs`, BEFORE anything is
 * emitted. It lived only in a test once, and `npm run check` runs the build
 * before the tests -- so an absent builtin was written to
 * `platform/idm/script/` and the command failed afterwards, leaving output
 * that `fo sync` would happily push. A gate that fires after emission is not a
 * gate.
 */
export function assertNoAbsentBuiltinUses() {
  const surface = JSON.parse(
    readFileSync(join(projectRoot, "framework", "engine-surface.json"), "utf8"),
  );
  const messages = [];
  for (const { tsconfig, engine } of RUNTIME_PROGRAMS) {
    const findings = checkEngineUsage(tsconfig, surface[engine]);
    if (findings.length > 0) {
      messages.push(
        `${tsconfig} uses ${findings.length} builtin(s) this engine does not ` +
          "have:\n" +
          formatFindings(tsconfig, engine, findings, surface.probedOn),
      );
    }
  }
  if (messages.length > 0) throw new Error(messages.join("\n\n"));
}

/** Throw if any runtime program subclasses a builtin. */
export function assertNoNativeSubclasses() {
  const messages = [];
  for (const { tsconfig } of RUNTIME_PROGRAMS) {
    for (const f of findNativeSubclasses(tsconfig)) {
      messages.push(
        `  ${f.file}:${f.line}:${f.column}  extends \`${f.native}\`. Babel ` +
          "lowers a native superclass through `_wrapNativeSuper`, which was\n" +
          "    measured to fail on both engines: an `Error` subclass loses its " +
          "own `instanceof`,\n    and a `Map` subclass does not construct at " +
          "all. Compose instead; for faults use\n    the tagged objects in " +
          "framework/errors.ts.",
      );
    }
  }
  if (messages.length > 0) {
    throw new Error("a runtime program subclasses a builtin:\n" + messages.join("\n"));
  }
}
