// Using a builtin the engine does not have is a build failure.
//
// WHY THIS EXISTS. `engine-coverage.mjs` derives everything the pinned `lib`
// promises; the probe measures what the engines actually answer. Comparing
// them found 234 declarations the lib admits and Rhino does not have --
// almost all of `Float32Array` and its siblings, plus `RegExp#flags`,
// `Date#[Symbol.toPrimitive]` and a handful more.
//
// None of that can be removed from the type system. `lib.es5.d.ts` is
// monolithic: the typed arrays arrive with `Date` and `JSON`, and TypeScript
// has no way to un-declare an interface member. So the old gate -- "no pinned
// lib entry may declare a builtin the engine lacks" -- is not something any
// real lib list can satisfy, and passing it only ever meant the measurement
// was too small to notice.
//
// The check that CAN hold is this one: nothing we compile may USE one. That
// turns `new Float32Array(8).map(f)` from code that type-checks, builds,
// deploys and throws in the middle of a request into a failed build, which is
// what the lib pin was supposed to buy in the first place.
//
// Each program is checked against ITS OWN engine. They are nearly the same
// Rhino, but the audit found two keys where they differ, so "the engines
// agree" is an observation about the current measurement rather than a
// property to build on.
//
// Managed file - regenerated by `fo upgrade`.

import { readFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

import ts from "typescript";

const projectRoot = join(dirname(fileURLToPath(import.meta.url)), "..");

/**
 * The interface a member was declared on, as a surface-key holder.
 *
 * `ArrayConstructor` holds statics (`Array.from`), `Array` holds prototype
 * members (`Array#map`), and a singleton like `Math` holds what reads as a
 * static. Returns undefined for anything not declared in a lib file, which is
 * the project's own code and none of this check's business.
 */
function holderOf(declaration, isLibFile) {
  const parent = declaration.parent;
  if (parent === undefined || !ts.isInterfaceDeclaration(parent)) return undefined;
  if (!isLibFile(parent.getSourceFile())) return undefined;

  const name = parent.name.text;
  if (name.endsWith("Constructor")) {
    return { holder: name.slice(0, -"Constructor".length), separator: "." };
  }
  // `Math` and `JSON` are objects, not constructors: their members are reached
  // as `Math.floor`, so they key like statics even though the interface is the
  // instance one.
  if (name === "Math" || name === "JSON") return { holder: name, separator: "." };
  return { holder: name, separator: "#" };
}

/** A global declared by a lib file, as `g:Name`. */
function globalKeyOf(declaration, isLibFile) {
  if (!ts.isVariableDeclaration(declaration) && !ts.isFunctionDeclaration(declaration)) {
    return undefined;
  }
  if (!isLibFile(declaration.getSourceFile())) return undefined;
  if (declaration.name === undefined || !ts.isIdentifier(declaration.name)) {
    return undefined;
  }
  return `g:${declaration.name.text}`;
}

/**
 * The surface key a symbol corresponds to, or undefined if it is not a
 * builtin the probe knows about.
 */
function keyForSymbol(symbol, memberName, isLibFile) {
  for (const declaration of symbol.declarations ?? []) {
    const global = globalKeyOf(declaration, isLibFile);
    if (global !== undefined) return global;
    const holder = holderOf(declaration, isLibFile);
    if (holder !== undefined) {
      return `${holder.holder}${holder.separator}${memberName}`;
    }
  }
  return undefined;
}

/**
 * A well-known symbol access (`x[Symbol.iterator]`) written in source. Rare in
 * hand-written code, but the surface records these and a missing one throws
 * the same way.
 */
function wellKnownSymbolName(node) {
  const argument = node.argumentExpression;
  if (argument === undefined || !ts.isPropertyAccessExpression(argument)) {
    return undefined;
  }
  if (!ts.isIdentifier(argument.expression)) return undefined;
  if (argument.expression.text !== "Symbol") return undefined;
  return `[Symbol.${argument.name.text}]`;
}

function loadProgram(tsconfigName) {
  const configPath = join(projectRoot, tsconfigName);
  const read = ts.readConfigFile(configPath, (p) => readFileSync(p, "utf8"));
  if (read.error) {
    throw new Error(
      `${tsconfigName}: ${ts.flattenDiagnosticMessageText(read.error.messageText, " ")}`,
    );
  }
  // Relative to the CONFIG, not to the package: a tsconfig in a subdirectory
  // resolves its own `include` from where it sits.
  const parsed = ts.parseJsonConfigFileContent(
    read.config,
    ts.sys,
    dirname(configPath),
  );
  if (parsed.fileNames.length === 0) {
    throw new Error(`${tsconfigName}: matched no files`);
  }
  return ts.createProgram({
    rootNames: parsed.fileNames,
    options: { ...parsed.options, noEmit: true },
  });
}

/**
 * Every use, in the given program, of a builtin recorded absent on that
 * engine.
 */
export function checkEngineUsage(tsconfigName, engineSurface) {
  const program = loadProgram(tsconfigName);
  const checker = program.getTypeChecker();
  const findings = [];

  // Ask the PROGRAM which files are lib files rather than matching a path.
  // `node_modules` is a symlink into the nix store here, so the lib TypeScript
  // actually loaded lives under /nix/store/... - an earlier version of this
  // compared against `<project>/node_modules/typescript/lib`, matched nothing,
  // and reported a clean result for a file that used `Float32Array#map`.
  const libFiles = new Set(
    program.getSourceFiles().filter((f) => program.isSourceFileDefaultLibrary(f)),
  );
  const isLibFile = (sourceFile) => libFiles.has(sourceFile);
  if (libFiles.size === 0) {
    throw new Error(
      `${tsconfigName}: the program loaded no default-library files, so this ` +
        "check could not detect anything. Refusing to report a clean result.",
    );
  }

  const absent = (key) => engineSurface[key] === false;

  function report(node, key) {
    const sourceFile = node.getSourceFile();
    const { line, character } = sourceFile.getLineAndCharacterOfPosition(
      node.getStart(sourceFile),
    );
    findings.push({
      file: relative(projectRoot, sourceFile.fileName),
      line: line + 1,
      column: character + 1,
      key,
    });
  }

  for (const sourceFile of program.getSourceFiles()) {
    if (sourceFile.isDeclarationFile) continue;

    const visit = (node) => {
      if (ts.isPropertyAccessExpression(node)) {
        const symbol = checker.getSymbolAtLocation(node.name);
        if (symbol) {
          const key = keyForSymbol(symbol, node.name.text, isLibFile);
          if (key !== undefined && absent(key)) report(node, key);
        }
      } else if (ts.isElementAccessExpression(node)) {
        const member = wellKnownSymbolName(node);
        if (member !== undefined) {
          const symbol = checker.getSymbolAtLocation(node.argumentExpression);
          if (symbol) {
            const key = keyForSymbol(symbol, member, isLibFile);
            if (key !== undefined && absent(key)) report(node, key);
          }
        }
      } else if (ts.isIdentifier(node) && !ts.isPropertyAccessExpression(node.parent)) {
        // A bare global: `Float32Array`, `Proxy`. Skipped when it is the
        // `.name` half of a property access, which the branch above handles.
        const symbol = checker.getSymbolAtLocation(node);
        if (symbol) {
          const key = keyForSymbol(symbol, node.text, isLibFile);
          if (key !== undefined && key.startsWith("g:") && absent(key)) {
            report(node, key);
          }
        }
      }
      ts.forEachChild(node, visit);
    };
    ts.forEachChild(sourceFile, visit);
  }

  return findings;
}

export function formatFindings(tsconfigName, engine, findings, probedOn) {
  return findings
    .map(
      (f) =>
        `  ${f.file}:${f.line}:${f.column}  \`${f.key}\` is not in ` +
        `${engine === "am" ? "PingAM" : "PingIDM"}'s script engine ` +
        `(probed ${probedOn}). Nothing polyfills it, so this compiles ` +
        `and throws at runtime.`,
    )
    .join("\n");
}
