// Generate TypeScript types for PingIDM's managed objects from managed.json.
//
// managed.json is not in the repo by default — it lives in the PingIDM image,
// and `fo config export idm` is what puts a copy under platform/idm/conf. That
// is why this generator exists here rather than shipping a fixed set of types:
// the shape of `managed/user` is a property of YOUR deployment, and it changes
// the moment someone adds a property in the admin UI.
//
// Managed file — regenerated by `fo upgrade`.

/**
 * Optional properties are `T | null`, not just `T`.
 *
 * PingIDM returns JSON `null` for a property that exists in the schema and has
 * been cleared, so `description?: string` type-checks a guard that throws at
 * runtime: `if (user.description !== undefined) user.description.indexOf(...)`
 * passes the check and then fails on null. Verified against a live IDM
 * 2026-08-25 while writing example-stale-accounts.
 */
const NULLABLE_OPTIONALS = true;

const HEADER = `// GENERATED — do not edit.
//
// Written by \`fo build\` from platform/idm/conf/managed.json, which
// \`fo config export idm\` puts there. Re-run either after changing a managed
// object, and commit the result: it is the only reason a fresh clone
// type-checks without a cluster.
`;

const RELATIONSHIP = `/**
 * A reference to another managed object. PingIDM returns these expanded only
 * when the query asks for it, so everything but \`_ref\` is optional.
 */
export type ManagedRelationship = {
  _ref: string;
  _refResourceCollection?: string | null;
  _refResourceId?: string | null;
  _refProperties?: Record<string, unknown> | null;
};
`;

/** `user` -> `ManagedUser`, `aiagentprivilege` -> `ManagedAiagentprivilege`. */
export function typeName(objectName) {
  const cleaned = objectName.replace(/[^A-Za-z0-9]+(.)?/g, (_, c) =>
    c ? c.toUpperCase() : ""
  );
  return "Managed" + cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
}

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function key(name) {
  return IDENTIFIER.test(name) ? name : JSON.stringify(name);
}

function scalar(type) {
  switch (type) {
    case "string":
      return "string";
    case "boolean":
      return "boolean";
    case "number":
    case "integer":
      return "number";
    case "null":
      return "null";
    case "relationship":
      return "ManagedRelationship";
    default:
      return undefined;
  }
}

function propertyType(prop, indent) {
  if (!prop || typeof prop !== "object") return "unknown";
  const type = prop.type;

  if (Array.isArray(type)) {
    const parts = type.map((t) => scalar(t) ?? "unknown");
    return [...new Set(parts)].join(" | ");
  }

  const simple = scalar(type);
  if (simple) return simple;

  if (type === "array") {
    const item = propertyType(prop.items, indent);
    // `A | B[]` parses as `A | (B[])`, so a union item type needs parens.
    return /[ |]/.test(item) ? `Array<${item}>` : `${item}[]`;
  }

  if (type === "object") {
    if (!prop.properties || Object.keys(prop.properties).length === 0) {
      return "Record<string, unknown>";
    }
    return objectLiteral(prop, indent);
  }

  return "unknown";
}

function docComment(prop, indent) {
  const text = prop.title && prop.title !== prop.description
    ? `${prop.title} — ${prop.description ?? ""}`.replace(/ — $/, "")
    : (prop.description ?? prop.title ?? "");
  if (!text) return "";
  return `${indent}/** ${text.replace(/\*\//g, "*\\/")} */\n`;
}

function objectLiteral(schema, indent) {
  const inner = indent + "  ";
  const required = new Set(schema.required ?? []);
  const lines = ["{"];
  for (const [name, prop] of Object.entries(schema.properties ?? {})) {
    const optional = !required.has(name);
    let type = propertyType(prop, inner);
    // Decided from the SCHEMA, not from the rendered string: a nested object
    // whose own members are nullable would otherwise look like it already
    // declares null and quietly lose its own `| null`.
    const declaresNull = Array.isArray(prop?.type)
      ? prop.type.includes("null")
      : prop?.type === "null";
    if (optional && NULLABLE_OPTIONALS && !declaresNull) {
      const union = Array.isArray(prop?.type) && prop.type.length > 1;
      type = union ? `(${type}) | null` : `${type} | null`;
    }
    lines.push(docComment(prop, inner) + `${inner}${key(name)}${optional ? "?" : ""}: ${type};`);
  }
  lines.push(indent + "}");
  return lines.join("\n");
}

/**
 * @param {object} managed the parsed managed.json
 * @returns {string} the contents of src/generated/managed.ts
 */
export function generateManagedTypes(managed) {
  const objects = managed?.objects;
  if (!Array.isArray(objects)) {
    throw new Error("managed.json has no `objects` array");
  }

  const parts = [HEADER, RELATIONSHIP];
  const names = [];
  for (const object of objects) {
    if (!object?.name || !object.schema) continue;
    const name = typeName(object.name);
    names.push([object.name, name]);
    const title = object.schema.title ?? object.name;
    parts.push(
      `/** PingIDM \`managed/${object.name}\`${title === object.name ? "" : ` (${title})`}. */\n` +
        `export interface ${name} ${objectLiteral(object.schema, "")}\n`
    );
  }

  // The framework declares `interface ManagedObjects {}` empty and keys it by
  // COLLECTION PATH, so that `openidm.read("managed/user/x")` can resolve a
  // return type. This block is what fills it in. It has to be a `declare
  // global` inside a real module: an ambient .d.ts is invisible from inside a
  // module graph, and this file is only in the program because tsconfig
  // includes src/generated, not because anything imports it.
  parts.push(
    "declare global {\n" +
      "  /** Every managed object this deployment defines, keyed by collection path. */\n" +
      "  interface ManagedObjects {\n" +
      names.map(([resource, type]) => `    ${key("managed/" + resource)}: ${type};`).join("\n") +
      "\n  }\n}\n"
  );

  return parts.join("\n");
}
