// The emit pipeline: esbuild bundle -> Babel downlevel to ES5.
//
// Its own module because two callers must be provably running the SAME thing:
// `build.mjs`, which emits what deploys, and `emit-probe.mjs`, which emits the
// corpus `fo doctor --engines` runs on the engines to prove that output still
// works. If those two ever drift, the behavioural half of the engine proof is
// measuring a pipeline nobody ships.
//
// Managed file -- regenerated by `fo upgrade`.

import * as babel from "@babel/core";
import * as esbuild from "esbuild";

/** The IIFE binding the emitted file's final expression statement calls. */
export const GLOBAL_NAME = "__foMain";

export async function bundle(entry, format, globalName) {
  const result = await esbuild.build({
    entryPoints: [entry],
    bundle: true,
    write: false,
    format,
    ...(globalName === undefined ? {} : { globalName }),
    // ES5 is Babel's job — esbuild refuses to transform `const` to ES5.
    target: "es2020",
    platform: "neutral",
    charset: "utf8",
    legalComments: "none",
    logLevel: "silent",
  });
  return result.outputFiles[0].text;
}

export function downlevel(code, name) {
  const result = babel.transformSync(code, {
    filename: name + ".bundle.js",
    babelrc: false,
    configFile: false,
    sourceType: "script",
    compact: false,
    comments: false,
    assumptions: {
      constantSuper: true,
      noClassCalls: true,
      setClassMethods: true,
      superIsCallableConstructor: true,
      noDocumentAll: true,
    },
    presets: [
      [
        "@babel/preset-env",
        {
          targets: { ie: "11" },
          modules: false,
          // Rhino has Map/Set/Symbol/Promise natively; a core-js polyfill would
          // be dead weight and cannot be installed on IDM anyway.
          useBuiltIns: false,
        },
      ],
    ],
  });
  if (result === null || typeof result.code !== "string") {
    throw new Error(name + ": Babel produced no output");
  }
  return result.code;
}

