// The AM source rule, and proof that it can still fail.
//
// `defineAmScript` narrows `goTo` to the declared outcomes, but an author can
// annotate `main`'s parameter and take the narrowing back -- TypeScript
// compares method parameters bivariantly, so `{ goTo(outcome: string): void }`
// is an accepted stand-in for `AmAction<"high" | "low">` and there is no
// variance annotation that changes it. `tools/am-source-rules.mjs` is the
// answer, and this is what keeps it honest.
//
// Managed file - regenerated by `fo upgrade`.

import assert from "node:assert/strict";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";

import {
  assertNoAnnotatedActionParameters,
  findAnnotatedActionParameters,
} from "../tools/am-source-rules.mjs";

const here = dirname(fileURLToPath(import.meta.url));

test("no authored PingAM script annotates main's parameter", () => {
  assertNoAnnotatedActionParameters();
});

test("the rule rejects an annotated parameter", () => {
  const findings = findAnnotatedActionParameters([
    join(here, "fixtures", "am-annotated-action.ts"),
  ]);
  assert.equal(
    findings.length,
    1,
    "the fixture annotates `main`'s parameter with a method-syntax `goTo`, " +
      "which type-checks; the rule is the only thing that can see it",
  );
  assert.match(findings[0].text, /goTo\(outcome: string\)/);
});

test("an inferred parameter is left alone", () => {
  // The positive control. Without it a rule that returned nothing at all would
  // pass the test above by reporting one finding from somewhere and this one
  // by reporting none.
  const findings = findAnnotatedActionParameters([
    join(here, "fixtures", "am-inferred-action.ts"),
  ]);
  assert.deepEqual(findings, []);
});
