// The PingAM scripts, checked for the things a journey cannot tell you until a
// real user hits it.
//
// These run as .mjs against the BUILT artefacts rather than as .ts against the
// sources, because the AM sources are a separate TypeScript program whose
// globals (`action`, `nodeState`, `logger`) collide with IDM's — importing them
// into the IDM-shaped test program is exactly what the split prevents.
//
// Managed file — regenerated by `fo upgrade`.

import assert from "node:assert/strict";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const manifestPath = join(projectRoot, ".fo-ts-manifest.json");
const scriptsDir = join(projectRoot, "src", "scripts");

function manifest() {
  if (!existsSync(manifestPath)) return { amScripts: [] };
  return JSON.parse(readFileSync(manifestPath, "utf8"));
}

function sourceNames() {
  if (!existsSync(scriptsDir)) return [];
  return readdirSync(scriptsDir)
    .filter((n) => n.endsWith(".ts") && !n.endsWith(".d.ts"))
    .map((n) => n.slice(0, -3))
    .sort();
}

test("every AM script source has a built amster entity", () => {
  const built = manifest().amScripts ?? [];
  assert.deepEqual(
    built.map((s) => s.name).sort(),
    sourceNames(),
    "run `fo build` — the manifest is stale",
  );
});

test("each entity is well-formed and carries an ES5 body", () => {
  for (const script of manifest().amScripts ?? []) {
    const entity = JSON.parse(
      readFileSync(join(projectRoot, "..", script.file), "utf8"),
    );
    assert.equal(entity.metadata.entityType, "Scripts");
    assert.equal(entity.data.context, script.context);
    assert.equal(entity.data.language, "JAVASCRIPT");
    assert.equal(entity.data.evaluatorVersion, "2.0");

    // The id must be derived from the name, not random: a fresh id on every
    // build would create a SECOND copy of the script in AM each time, and
    // journeys would keep pointing at the first.
    assert.equal(entity.data._id, script.id);
    assert.equal(entity.metadata.entityId, script.id);

    const body = Buffer.from(entity.data.script, "base64").toString("utf8");
    assert.match(body, /@generated by `fo build`/);
    assert.doesNotMatch(
      body,
      /\b(let|const)\b|=>/,
      script.name + ": ES5 downlevel leaked modern syntax",
    );

    // A goTo naming an outcome the node does not declare dead-ends at runtime.
    for (const match of body.matchAll(/goTo\(\s*"([^"]+)"\s*\)/g)) {
      assert.ok(
        script.outcomes.includes(match[1]),
        script.name + ': goTo("' + match[1] + '") is not a declared outcome',
      );
    }
  }
});
