// The committed behavioural corpus must be what the pipeline produces today.
//
// `framework/engine-emit-probe.js` is Babel's real ES5 output, and `fo doctor
// --engines` runs it verbatim on both engines to answer the `emit:*` keys. If
// a Babel or esbuild bump changes the helpers and the committed file is not
// regenerated, the engines keep being asked about an emit shape nobody ships
// any more - which is the exact failure the generated corpus replaced.
//
// Managed file — regenerated by `fo upgrade`.

import assert from "node:assert/strict";
import { test } from "node:test";

import { committed, generate } from "../tools/emit-probe.mjs";

test("engine-emit-probe.js is the pipeline's current output", async () => {
  assert.equal(
    await generate(),
    committed(),
    "regenerate with `node tools/emit-probe.mjs`, then re-record the surface " +
      "with `fo doctor --engines --record` — the engines have to have run " +
      "THIS output for the emit: keys to mean anything",
  );
});

test("the corpus exercises Babel's helpers, not a hand-written stand-in", () => {
  // The previous checks were ES5 written by hand to look like Babel's output.
  // These names cannot appear unless the file really came through Babel.
  const text = committed();
  for (const helper of [
    "_toConsumableArray",
    "_objectSpread",
    "_createForOfIteratorHelper",
    "_slicedToArray",
    "_inherits",
  ]) {
    assert.match(text, new RegExp(helper), `${helper} missing from the corpus`);
  }
});
