// The gate on `lib`.
//
// `@babel/preset-env` runs with `useBuiltIns: false`, so nothing is
// polyfilled: if the pinned `lib` declares a builtin the script engine lacks,
// the code type-checks, builds, deploys, and throws at runtime in the middle
// of somebody's login. That is the failure this file exists to prevent, and
// it cannot be caught by a compile-time fixture, because the test program
// deliberately runs on a wider `lib` than the two runtime programs do.
//
// So the check is derived rather than restated: take the `lib` entries the
// tsconfigs actually name, read the declarations out of TypeScript's OWN lib
// .d.ts files, and cross-check them against builtins probed on a running
// stack (framework/engine-surface.json).
//
// This file used to assert that no pinned lib entry declares anything the
// engine lacks. That gate passed for one reason only: the measurement covered
// 97 keys out of the 714 the pin promises, so nothing unmeasured could ever
// fail it. Deriving the required set from the lib side closed that
// circularity and immediately found 234 declarations Rhino does not have -
// almost all of the typed arrays, which arrive inseparably with `lib.es5`.
// No lib list can satisfy the old gate, so the assertion that replaces it is
// the one that can hold: nothing we compile may USE an absent builtin.
//
// Managed file — regenerated by `fo upgrade`.

import assert from "node:assert/strict";
import { readFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";

const here = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(here, "..");

import {
  libDigests,
  requiredKeys,
  typescriptVersion,
} from "../tools/engine-coverage.mjs";
import { checkEngineUsage, formatFindings } from "../tools/engine-usage.mjs";

const surface = JSON.parse(
  readFileSync(join(projectRoot, "framework", "engine-surface.json"), "utf8"),
);
const coverage = JSON.parse(
  readFileSync(join(projectRoot, "framework", "engine-coverage.json"), "utf8"),
);

/** Strip comments so JSON.parse accepts a tsconfig. */
function readTsconfig(name) {
  const text = readFileSync(join(projectRoot, name), "utf8");
  return JSON.parse(text);
}

const RUNTIME_PROGRAMS = [
  // The two programs whose output actually runs on a Ping script engine. The
  // test program (tsconfig.tests.json) is deliberately excluded: it runs on
  // node and is entitled to a modern lib.
  { tsconfig: "tsconfig.json", engine: "idm" },
  { tsconfig: "tsconfig.am.json", engine: "am" },
];

// Both runtime programs pin the same list today; derive it rather than
// restate it, so a divergence shows up as a failure and not as a stale const.
const LIBS = readTsconfig("tsconfig.json").compilerOptions.lib;

function libFile(entry) {
  return join(
    projectRoot,
    "node_modules",
    "typescript",
    "lib",
    `lib.${entry.toLowerCase()}.d.ts`,
  );
}

test("every lib entry the runtime programs name actually exists", () => {
  for (const { tsconfig } of RUNTIME_PROGRAMS) {
    for (const entry of readTsconfig(tsconfig).compilerOptions.lib) {
      assert.ok(
        existsSync(libFile(entry)),
        `${tsconfig} names lib "${entry}", which TypeScript does not ship`,
      );
    }
  }
});

test("every builtin the pinned lib promises has actually been probed", () => {
  // The circularity-breaker. `fo doctor --engines` generates its probes FROM
  // engine-surface.json, so without this the surface can only ever confirm
  // what it already contains: a builtin nobody thought of is not measured,
  // not reported, and silently assumed present.
  const { keys, unclassified } = requiredKeys(LIBS);
  assert.deepEqual(
    unclassified,
    [],
    "engine-coverage.mjs cannot classify these interfaces as runtime-bearing " +
      "or structural, so it does not know whether to require them",
  );
  for (const engine of ["am", "idm"]) {
    const unprobed = keys.filter((k) => !(k in surface[engine]));
    assert.deepEqual(
      unprobed,
      [],
      `${unprobed.length} builtin(s) the pinned lib declares were never ` +
        `probed on ${engine}. Run \`node tools/engine-coverage.mjs --seed\` ` +
        "then `fo doctor --engines --record` against a running stack.",
    );
  }
});

test("no source uses a builtin the engine lacks", () => {
  // What replaces the old lib-level gate. 234 of the declarations the pin
  // admits are absent from Rhino and cannot be removed from the type system,
  // so the line that can be held is at the use site: `new Float32Array(8).map(f)`
  // fails the build instead of throwing inside somebody's login.
  for (const { tsconfig, engine } of RUNTIME_PROGRAMS) {
    const findings = checkEngineUsage(tsconfig, surface[engine]);
    assert.deepEqual(
      findings,
      [],
      `${tsconfig} uses builtins this engine does not have:\n` +
        formatFindings(tsconfig, engine, findings, surface.probedOn),
    );
  }
});

test("the usage check can still fail", () => {
  // The check matched lib files by path once, and `node_modules` is a symlink
  // into the nix store: it compared against `<project>/node_modules/...`,
  // saw `/nix/store/...`, matched nothing, and passed a file that used
  // `Float32Array#map`. Green meant "found nothing" and "cannot find
  // anything" and there was no way to tell them apart.
  const findings = checkEngineUsage(
    join("tests", "fixtures", "tsconfig.absent.json"),
    surface.idm,
  );
  assert.deepEqual(
    findings.map((f) => f.key).sort(),
    ["Float32Array#map", "RegExp#flags"],
    "the fixture uses two builtins this engine lacks; the check must see both",
  );
});

test("the measurement still covers the lib files it was taken against", () => {
  // A TypeScript upgrade can add a member to a lib file, and nothing else
  // here would notice: the new declaration would simply never be probed, and
  // every test above would stay green while the pin described a smaller lib
  // than the one in use.
  assert.equal(
    coverage.typescript,
    typescriptVersion(),
    "TypeScript changed since the engine surface was audited; re-probe with " +
      "`fo doctor --engines --record`, then `node tools/engine-coverage.mjs --manifest`",
  );
  assert.deepEqual(
    libDigests(LIBS),
    coverage.lib,
    "a pinned lib file changed since the engine surface was audited; " +
      "re-probe with `fo doctor --engines --record`, then " +
      "`node tools/engine-coverage.mjs --manifest`",
  );
});

/**
 * Where PingAM's and PingIDM's engines were measured to differ.
 *
 * The old claim was that they agree everywhere, and at 97 probes they did.
 * At 714 they do not: IDM's Rhino puts `Symbol.toStringTag` on `Math` and
 * `JSON` and AM's does not. Neither is reachable from anything worth writing,
 * so the two programs can still share a lib -- but only because the usage
 * check runs each program against ITS OWN engine, not because the engines are
 * the same object.
 */
const KNOWN_DISAGREEMENTS = [
  "JSON.[Symbol.toStringTag]",
  "Math.[Symbol.toStringTag]",
];

test("the probe covered both engines, and they differ only where recorded", () => {
  const shared = Object.keys(surface.am).filter((k) => k in surface.idm);
  assert.ok(shared.length > 700, `only ${shared.length} shared probes`);
  const disagreed = shared.filter((k) => surface.am[k] !== surface.idm[k]);
  assert.deepEqual(
    disagreed,
    KNOWN_DISAGREEMENTS,
    "PingAM and PingIDM's engines differ somewhere new. Check whether " +
      "anything reachable is affected before adding it to the list: a shared " +
      "`lib` is only sound while each program is checked against its own engine.",
  );
});

test("engine-lib.d.ts only declares members the engine has", () => {
  // The escape hatch for a lib entry that is a PARTIAL match. Anything
  // declared there is invisible to the check above, so it gets its own.
  const text = readFileSync(
    join(projectRoot, "framework", "engine-lib.d.ts"),
    "utf8",
  );
  const declared = [...text.matchAll(/^\s{2}([a-zA-Z][a-zA-Z0-9]*)[(<]/gm)].map(
    (m) => m[1],
  );
  assert.ok(declared.length > 0, "no members parsed out of engine-lib.d.ts");
  for (const name of new Set(declared)) {
    for (const engine of ["am", "idm"]) {
      const key = Object.keys(surface[engine]).find(
        (k) => k.split(/[.#]/).slice(1).join(".") === name,
      );
      assert.ok(
        key !== undefined,
        `engine-lib.d.ts declares \`${name}\`, which the probe never checked ` +
          `on ${engine}. Probe it before declaring it.`,
      );
      assert.equal(
        surface[engine][key],
        true,
        `engine-lib.d.ts declares \`${name}\`, which ${engine}'s engine lacks`,
      );
    }
  }
});
