// The gate on `lib`.
//
// `@babel/preset-env` runs with `useBuiltIns: false`, so nothing is
// polyfilled: if the pinned `lib` declares a builtin the script engine lacks,
// the code type-checks, builds, deploys, and throws at runtime in the middle
// of somebody's login. That is the failure this file exists to prevent, and
// it cannot be caught by a compile-time fixture, because the test program
// deliberately runs on a wider `lib` than the two runtime programs do.
//
// So the check is derived rather than restated: take the `lib` entries the
// tsconfigs actually name, read the member names out of TypeScript's OWN lib
// .d.ts files, and cross-check them against builtins probed on a running
// stack (framework/engine-surface.json). Adding a lib entry that declares
// something the engine lacks fails here.
//
// Managed file — regenerated by `fo upgrade`.

import assert from "node:assert/strict";
import { readFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";

const here = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(here, "..");

const surface = JSON.parse(
  readFileSync(join(projectRoot, "framework", "engine-surface.json"), "utf8"),
);

/** Strip comments so JSON.parse accepts a tsconfig. */
function readTsconfig(name) {
  const text = readFileSync(join(projectRoot, name), "utf8");
  return JSON.parse(text);
}

const RUNTIME_PROGRAMS = [
  // The two programs whose output actually runs on a Ping script engine. The
  // test program (tsconfig.tests.json) is deliberately excluded: it runs on
  // node and is entitled to a modern lib.
  { tsconfig: "tsconfig.json", engine: "idm" },
  { tsconfig: "tsconfig.am.json", engine: "am" },
];

/**
 * Builtins the probe recorded as ABSENT, expressed as the shape they take in
 * TypeScript's lib files: a global `declare var X`, or a member declared
 * inside an interface.
 */
function absentMembers(engine) {
  const recorded = surface[engine];
  const globals = [];
  const members = [];
  for (const [key, present] of Object.entries(recorded)) {
    if (present) continue;
    if (key.startsWith("g:")) globals.push(key.slice(2));
    else if (key.includes("#")) members.push(key.split("#")[1]);
    else if (key.includes(".")) members.push(key.split(".").slice(1).join("."));
  }
  return { globals, members };
}

function libFile(entry) {
  return join(
    projectRoot,
    "node_modules",
    "typescript",
    "lib",
    `lib.${entry.toLowerCase()}.d.ts`,
  );
}

test("every lib entry the runtime programs name actually exists", () => {
  for (const { tsconfig } of RUNTIME_PROGRAMS) {
    for (const entry of readTsconfig(tsconfig).compilerOptions.lib) {
      assert.ok(
        existsSync(libFile(entry)),
        `${tsconfig} names lib "${entry}", which TypeScript does not ship`,
      );
    }
  }
});

test("no pinned lib entry declares a builtin the engine lacks", () => {
  for (const { tsconfig, engine } of RUNTIME_PROGRAMS) {
    const { globals, members } = absentMembers(engine);
    for (const entry of readTsconfig(tsconfig).compilerOptions.lib) {
      const text = readFileSync(libFile(entry), "utf8");

      for (const name of globals) {
        // A global arrives as `declare var X:` or `declare const X:`.
        const declared = new RegExp(`^declare (var|const) ${name}\\b`, "m");
        assert.ok(
          !declared.test(text),
          `${tsconfig}: lib "${entry}" declares global \`${name}\`, which ` +
            `PingAM/PingIDM's engine does not have (probed ${surface.probedOn}). ` +
            `Nothing polyfills it, so this compiles and throws at runtime.`,
        );
      }
      for (const name of members) {
        // A member arrives as an indented `name(` or `readonly name:`.
        const declared = new RegExp(`^\\s+(readonly )?${name}\\s*[(<:]`, "m");
        assert.ok(
          !declared.test(text),
          `${tsconfig}: lib "${entry}" declares \`${name}\`, which ` +
            `PingAM/PingIDM's engine does not have (probed ${surface.probedOn}). ` +
            `Nothing polyfills it, so this compiles and throws at runtime.`,
        );
      }
    }
  }
});

test("the probe covered both engines and they agreed", () => {
  // If they ever diverge, the two programs need different libs and the
  // shared `engine-lib.d.ts` stops being sound.
  const shared = Object.keys(surface.am).filter((k) => k in surface.idm);
  assert.ok(shared.length > 80, `only ${shared.length} shared probes`);
  const disagreed = shared.filter((k) => surface.am[k] !== surface.idm[k]);
  assert.deepEqual(
    disagreed,
    [],
    "PingAM and PingIDM's engines disagree; they can no longer share a lib",
  );
});

test("engine-lib.d.ts only declares members the engine has", () => {
  // The escape hatch for a lib entry that is a PARTIAL match. Anything
  // declared there is invisible to the check above, so it gets its own.
  const text = readFileSync(
    join(projectRoot, "framework", "engine-lib.d.ts"),
    "utf8",
  );
  const declared = [...text.matchAll(/^\s{2}([a-zA-Z][a-zA-Z0-9]*)[(<]/gm)].map(
    (m) => m[1],
  );
  assert.ok(declared.length > 0, "no members parsed out of engine-lib.d.ts");
  for (const name of new Set(declared)) {
    for (const engine of ["am", "idm"]) {
      const key = Object.keys(surface[engine]).find(
        (k) => k.split(/[.#]/).slice(1).join(".") === name,
      );
      assert.ok(
        key !== undefined,
        `engine-lib.d.ts declares \`${name}\`, which the probe never checked ` +
          `on ${engine}. Probe it before declaring it.`,
      );
      assert.equal(
        surface[engine][key],
        true,
        `engine-lib.d.ts declares \`${name}\`, which ${engine}'s engine lacks`,
      );
    }
  }
});
