// The gate on `lib`.
//
// `@babel/preset-env` runs with `useBuiltIns: false`, so nothing is
// polyfilled: if the pinned `lib` declares a builtin the script engine lacks,
// the code type-checks, builds, deploys, and throws at runtime in the middle
// of somebody's login. That is the failure this file exists to prevent, and
// it cannot be caught by a compile-time fixture, because the test program
// deliberately runs on a wider `lib` than the two runtime programs do.
//
// So the check is derived rather than restated: take the `lib` entries the
// tsconfigs actually name, read the declarations out of the compilers' OWN lib
// .d.ts files, and cross-check them against builtins probed on a running stack
// (framework/engine-surface.json).
//
// This file used to assert that no pinned lib entry declares anything the
// engine lacks. That gate passed for one reason only: the measurement covered
// 97 keys out of the 728 the pin promises, so nothing unmeasured could ever
// fail it. Deriving the required set from the lib side closed that
// circularity and immediately found 234 declarations Rhino does not have -
// almost all of the typed arrays, which arrive inseparably with `lib.es5`.
// No lib list can satisfy the old gate, so the assertion that replaces it is
// the one that can hold: nothing we compile may USE an absent builtin.
//
// That assertion runs at BUILD time, in `tools/build.mjs`'s type-check step.
// What is here is the discrimination test - proof the checker can still fail -
// plus the coverage and manifest gates, which are properties of the recorded
// measurement rather than of any one build.
//
// Managed file — regenerated by `fo upgrade`.

import assert from "node:assert/strict";
import { readFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";

import ts from "typescript";

const here = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(here, "..");

import {
  TSGO_LIB_DIR,
  TS_LIB_DIR,
  assertMeasurementCovers,
  sharedRuntimeLibs,
} from "../tools/engine-coverage.mjs";
import {
  RUNTIME_PROGRAMS,
  checkEngineUsage,
  findNativeSubclasses,
  formatFindings,
} from "../tools/engine-usage.mjs";

const surface = JSON.parse(
  readFileSync(join(projectRoot, "framework", "engine-surface.json"), "utf8"),
);
const coverage = JSON.parse(
  readFileSync(join(projectRoot, "framework", "engine-coverage.json"), "utf8"),
);

/** Strip comments so JSON.parse accepts a tsconfig. */
function readTsconfig(name) {
  const text = readFileSync(join(projectRoot, name), "utf8");
  return JSON.parse(text);
}

function libFile(entry, libDir) {
  return join(libDir, `lib.${entry.toLowerCase()}.d.ts`);
}

test("the two runtime programs pin the same lib, and every entry exists", () => {
  // The sharing is the premise of ONE surface covering both engines, and it
  // was never checked: the census read `tsconfig.json` alone, so an entry
  // added to `tsconfig.am.json` would be type-checked against and never
  // probed.
  sharedRuntimeLibs();
  for (const { tsconfig } of RUNTIME_PROGRAMS) {
    for (const entry of readTsconfig(tsconfig).compilerOptions.lib) {
      for (const [what, dir] of [
        ["tsgo", TSGO_LIB_DIR],
        ["typescript", TS_LIB_DIR],
      ]) {
        assert.ok(
          existsSync(libFile(entry, dir)),
          `${tsconfig} names lib "${entry}", which ${what} does not ship`,
        );
      }
    }
  }
});

test("the measurement still covers what the compilers actually declare", () => {
  // Drives the REAL pre-emission assertion rather than restating it. This was
  // three separate tests that reimplemented the same comparisons, and they
  // drifted: the build's version walked only the digests it could see, so a
  // manifest entry for a lib no longer pinned survived, while the test's
  // `deepEqual` caught it -- after emission.
  //
  // What it covers: every interface classified, tsgo and typescript declaring
  // the same builtins (they ship different bytes for all twelve pinned files),
  // every declared builtin probed on both engines, and the manifest matching
  // both compilers exactly.
  assertMeasurementCovers(surface, coverage);
});

test("...and says so when it does not", () => {
  // The positive control. `assertMeasurementCovers` returning nothing is what
  // a passing build looks like AND what a function that checks nothing looks
  // like.
  assert.throws(
    () =>
      assertMeasurementCovers(surface, {
        ...coverage,
        lib: {
          ...coverage.lib,
          tsgo: { ...coverage.lib.tsgo, ES5: "0000000000000000" },
        },
      }),
    /different declaration files/,
  );
  assert.throws(
    () => assertMeasurementCovers(surface, { ...coverage, requiredKeys: 1 }),
    /requiredKeys 1 ->/,
  );
  assert.throws(
    () =>
      assertMeasurementCovers(surface, {
        ...coverage,
        lib: {
          ...coverage.lib,
          tsgo: { ...coverage.lib.tsgo, "ES2099.Imaginary": "abc" },
        },
      }),
    /no longer pinned/,
  );
  const short = { ...surface, am: { ...surface.am } };
  delete short.am["Array#map"];
  assert.throws(
    () => assertMeasurementCovers(short, coverage),
    /never probed on am/,
  );
});

test("no source uses a builtin the engine lacks", () => {
  // What replaces the old lib-level gate. 234 of the declarations the pin
  // admits are absent from Rhino and cannot be removed from the type system,
  // so the line that can be held is at the use site: `new Float32Array(8).map(f)`
  // fails the build instead of throwing inside somebody's login.
  //
  // The BUILD is where this is enforced; the assertion here is a second
  // reader of the same function, so a regression shows up in `npm test` too.
  for (const { tsconfig, engine } of RUNTIME_PROGRAMS) {
    const findings = checkEngineUsage(tsconfig, surface[engine]);
    assert.deepEqual(
      findings,
      [],
      `${tsconfig} uses builtins this engine does not have:\n` +
        formatFindings(tsconfig, engine, findings, surface.probedOn),
    );
  }
});

test("the usage check can still fail, in every form it claims to resolve", () => {
  // The check matched lib files by path once, and `node_modules` is a symlink
  // into the nix store: it compared against `<project>/node_modules/...`,
  // saw `/nix/store/...`, matched nothing, and passed a file that used
  // `Float32Array#map`. Green meant "found nothing" and "cannot find
  // anything" and there was no way to tell them apart.
  //
  // One case per FORM, because a later version resolved only property access
  // and would have passed this test on the strength of the first line alone.
  const findings = checkEngineUsage(
    join("tests", "fixtures", "tsconfig.absent.json"),
    surface.idm,
  );
  assert.deepEqual(
    findings.map((f) => f.key).sort(),
    [
      "Float32Array#every", // binding pattern, quoted key
      "Float32Array#fill", // element access, finite union key
      "Float32Array#findIndex", // PARAMETER binding pattern
      "Float32Array#forEach", // binding pattern
      "Float32Array#indexOf", // destructuring assignment
      "Float32Array#lastIndexOf", // destructuring assignment, quoted key
      "Float32Array#map", // property access
      "Float32Array#reduce", // element access, literal key
      "Float32Array#some", // binding pattern, computed literal key
      "RegExp#flags",
      "Uint8Array#join", // nested destructuring assignment, computed key
      "Uint8Array#reverse", // ...and one behind a nested pattern DEFAULT
      "Uint8Array#slice", // nested binding pattern
    ],
    "the fixture reaches thirteen absent builtins, one per resolvable form. " +
      "Five were added after reviews found them silently missed, and one - " +
      "the parameter case - the fixture had claimed to cover and did not. " +
      "The default case was worse than a miss: the `=` in `{ x } = fallback` " +
      "was read as the assignment, so the member resolved against the " +
      "fallback object and came back clean.",
  );
});

test("the usage check resolves well-known symbol members to their holder", () => {
  // `Math[Symbol.toStringTag]` resolved the symbol rather than the property
  // and produced a `Symbol...` key, so the one member PingAM is known to lack
  // was reachable and reported clean. It is checked against AM specifically:
  // PingIDM's engine HAS it, and asserting against that engine would prove
  // nothing.
  const findings = checkEngineUsage(
    join("tests", "fixtures", "tsconfig.absent.json"),
    surface.am,
  );
  assert.ok(
    findings.some((f) => f.key === "Math.[Symbol.toStringTag]"),
    "the fixture reads `Math[Symbol.toStringTag]`, which PingAM's engine " +
      `lacks; found ${JSON.stringify(findings.map((f) => f.key))}`,
  );
});

/**
 * Where PingAM's and PingIDM's engines were measured to differ.
 *
 * The old claim was that they agree everywhere, and at 97 probes they did.
 * At 728 they do not: IDM's Rhino puts `Symbol.toStringTag` on `Math` and
 * `JSON` and AM's does not. Neither is reachable from anything worth writing,
 * so the two programs can still share a lib -- but only because the usage
 * check runs each program against ITS OWN engine, not because the engines are
 * the same object.
 */
const KNOWN_DISAGREEMENTS = [
  "JSON.[Symbol.toStringTag]",
  "Math.[Symbol.toStringTag]",
];

test("the probe covered both engines, and they differ only where recorded", () => {
  const shared = Object.keys(surface.am).filter((k) => k in surface.idm);
  assert.ok(shared.length > 700, `only ${shared.length} shared probes`);
  const disagreed = shared.filter((k) => surface.am[k] !== surface.idm[k]);
  assert.deepEqual(
    disagreed,
    KNOWN_DISAGREEMENTS,
    "PingAM and PingIDM's engines differ somewhere new. Check whether " +
      "anything reachable is affected before adding it to the list: a shared " +
      "`lib` is only sound while each program is checked against its own engine.",
  );
});

/**
 * Every member `engine-lib.d.ts` declares, as an exact surface key.
 *
 * Read from the AST rather than by regular expression, because the member name
 * alone is ambiguous: matching `entries` against any key ending in `entries`
 * finds `Array#entries` and passes without ever checking `Object.entries`,
 * which is the declaration actually being made.
 */
function declaredKeys(text) {
  const sourceFile = ts.createSourceFile(
    "engine-lib.d.ts",
    text,
    ts.ScriptTarget.Latest,
    true,
  );
  const keys = new Set();
  for (const statement of sourceFile.statements) {
    if (!ts.isInterfaceDeclaration(statement)) continue;
    const name = statement.name.text;
    const [holder, separator] = name.endsWith("Constructor")
      ? [name.slice(0, -"Constructor".length), "."]
      : name === "Math" || name === "JSON"
        ? [name, "."]
        : [name, "#"];
    for (const member of statement.members) {
      if (member.name === undefined) continue;
      if (!ts.isIdentifier(member.name) && !ts.isStringLiteral(member.name)) {
        continue;
      }
      keys.add(`${holder}${separator}${member.name.text}`);
    }
  }
  return [...keys].sort();
}

test("engine-lib.d.ts only declares members the engine has", () => {
  // The escape hatch for a lib entry that is a PARTIAL match. Anything
  // declared there is invisible to the coverage census above, so it gets its
  // own gate.
  const keys = declaredKeys(
    readFileSync(join(projectRoot, "framework", "engine-lib.d.ts"), "utf8"),
  );
  assert.ok(keys.length > 0, "no members parsed out of engine-lib.d.ts");
  for (const key of keys) {
    for (const engine of ["am", "idm"]) {
      assert.ok(
        key in surface[engine],
        `engine-lib.d.ts declares \`${key}\`, which the probe never checked ` +
          `on ${engine}. Probe it before declaring it.`,
      );
      assert.equal(
        surface[engine][key],
        true,
        `engine-lib.d.ts declares \`${key}\`, which ${engine}'s engine lacks`,
      );
    }
  }
});

test("the native-subclass gate can still fail, however the native is named", () => {
  // `emit:subclass-error` and `emit:subclass-map` prove the LOWERING fails on
  // the engines. They say nothing about whether the source gate can see it,
  // and the gate resolves through the checker - so it has escapes only a
  // fixture will find. The union case was one: `class X extends (c ? Error :
  // Local)` types as a union, a union carries no symbol of its own, and the
  // branch that picks the native went unreported.
  const found = findNativeSubclasses(
    join("tests", "fixtures", "tsconfig.subclass.json"),
  );
  assert.deepEqual(
    found.map((f) => f.native).sort(),
    ["Error", "Error", "Error", "Map"],
    "the fixture names a native four ways - directly, through a `const` " +
      "alias, through `globalThis`, and as one branch of a union",
  );
  assert.ok(
    !found.some((f) => f.native === "Local"),
    "extending a project class is legitimate and must not be flagged",
  );
});
