// CREST error mapping. Managed file — regenerated by `aic workspace update`.

import assert from "node:assert/strict";
import { test } from "node:test";

import {
  badRequest,
  describeThrowable,
  fault,
  forbidden,
  isFault,
  notFound,
  reasonFor,
  toCrestFault,
} from "../framework/index.ts";

test("a fault carries code, reason, message and optional detail", () => {
  const built = badRequest("bad", { issues: [] });
  assert.equal(built.code, 400);
  assert.equal(built.reason, "Bad Request");
  assert.equal(built.message, "bad");
  assert.deepEqual(built.detail, { issues: [] });
});

test("detail is omitted rather than set to undefined", () => {
  assert.equal(
    Object.prototype.hasOwnProperty.call(notFound("gone"), "detail"),
    false
  );
});

test("reasonFor falls back by status class", () => {
  assert.equal(reasonFor(403), "Forbidden");
  assert.equal(reasonFor(418), "Client Error");
  assert.equal(reasonFor(599), "Server Error");
});

test("isFault duck-types the tag rather than using instanceof", () => {
  assert.equal(isFault(forbidden("no")), true);
  assert.equal(isFault({ code: 400, message: "x" }), false);
  assert.equal(isFault(new Error("x")), false);
  assert.equal(isFault(null), false);
  assert.equal(isFault("string"), false);
});

test("a fault survives a structured clone, which an Error subclass would not", () => {
  // This is the property the framework depends on: identity lives in the data,
  // not in the prototype chain, so the ES5 downlevel cannot break it.
  const round = JSON.parse(JSON.stringify(forbidden("no"))) as unknown;
  assert.equal(isFault(round), true);
});

test("toCrestFault passes a fault through untouched", () => {
  const original = notFound("gone", { key: "widget/w-1" });
  assert.equal(toCrestFault(original), original);
});

test("toCrestFault keeps a downstream status but drops its message", () => {
  const mapped = toCrestFault({
    code: 404,
    message: "managed/user/x not found",
  });
  assert.equal(mapped.code, 404);
  assert.equal(mapped.message, "Not Found");
  assert.equal(mapped.detail, undefined);
});

test("toCrestFault turns anything else into an opaque 500", () => {
  for (const thrown of [new Error("secret"), "boom", 42, null, undefined, {}]) {
    const mapped = toCrestFault(thrown);
    assert.equal(mapped.code, 500);
    assert.equal(mapped.message, "Internal error");
  }
});

test("toCrestFault ignores a code outside the HTTP error range", () => {
  assert.equal(toCrestFault({ code: 200 }).code, 500);
  assert.equal(toCrestFault({ code: 700 }).code, 500);
});

test("describeThrowable renders for the log without leaking the object", () => {
  assert.equal(describeThrowable(new Error("nope")), "Error: nope");
  assert.equal(describeThrowable({ name: "Weird" }), "Weird");
  assert.equal(describeThrowable("plain"), "plain");
  assert.equal(describeThrowable(7), "7");
});

test("fault() accepts an arbitrary status", () => {
  assert.equal(fault(451, "unavailable for legal reasons").code, 451);
});
