// The committed src/generated/managed.ts must match what the generator makes
// from the committed managed.json.
//
// It is committed so a fresh clone type-checks without a cluster, which means
// it can drift: someone edits it by hand, or exports a new managed.json and
// forgets to rebuild. Either way the types then describe a deployment that no
// longer exists, and nothing else notices.
//
// Managed file — regenerated by `fo upgrade`.

import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

import { generateManagedTypes } from "../tools/managed-types.mjs";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const managedJson = join(projectRoot, "..", "idm", "conf", "managed.json");
const generated = join(projectRoot, "src", "generated", "managed.ts");

test("generated managed types are in sync with managed.json", (t) => {
  if (!existsSync(managedJson)) {
    // Not a failure: managed.json only arrives with `fo config export idm`,
    // and a checkout that has never talked to a cluster is a valid state.
    t.skip("no platform/idm/conf/managed.json — run `fo config export idm`");
    return;
  }
  assert.ok(
    existsSync(generated),
    "platform/idm/conf/managed.json exists but src/generated/managed.ts does not — run `fo build`"
  );
  assert.equal(
    readFileSync(generated, "utf8"),
    generateManagedTypes(JSON.parse(readFileSync(managedJson, "utf8"))),
    "src/generated/managed.ts is stale or hand-edited — run `fo build`"
  );
});
