// Test doubles for the IDM bindings.
//
// Managed file — regenerated by `aic workspace update`.

import type {
  CrestErrorResponse,
  CrestRequest,
  IdmCallContext,
  IdmLogger,
  JavaSet,
  PatchOperation,
} from "../framework/index.ts";

/** Capture the caller-facing object an endpoint dispatch throws to IDM. */
export function crestErrorFrom(run: () => unknown): CrestErrorResponse {
  try {
    run();
  } catch (thrown) {
    const value = thrown as Record<string, unknown> | null;
    if (typeof value === "object" && value !== null &&
        typeof value["code"] === "number" && typeof value["message"] === "string") {
      return thrown as CrestErrorResponse;
    }
    throw new Error("expected a CREST error response, got " + String(thrown));
  }
  throw new Error("expected a throw");
}

/** A `java.util.Set` stand-in: membership is `.contains`, never `.includes`. */
export function javaSet(values: string[]): JavaSet<string> {
  return {
    contains: (value) => values.indexOf(value) >= 0,
    size: () => values.length,
    isEmpty: () => values.length === 0,
  };
}

export interface CapturedLine {
  level: "trace" | "debug" | "info" | "warn" | "error";
  message: string;
}

export interface RecordingLogger extends IdmLogger {
  lines: CapturedLine[];
}

export function recordingLogger(): RecordingLogger {
  const lines: CapturedLine[] = [];
  const push =
    (level: CapturedLine["level"]) =>
    (message: string): void => {
      lines.push({ level, message });
    };
  return {
    lines,
    trace: push("trace"),
    debug: push("debug"),
    info: push("info"),
    warn: push("warn"),
    error: push("error"),
  };
}

export interface RequestOptions {
  resourcePath?: string;
  query?: Record<string, string>;
  fields?: string[];
  content?: unknown;
  action?: string;
  patchOperations?: PatchOperation[];
  /** Client-supplied id — what a bare `PUT .../{id}` delivers. */
  newResourceId?: string;
}

/** Build a `request` binding for one CREST method. */
export function crestRequest(
  method: CrestRequest["method"],
  options: RequestOptions = {}
): CrestRequest {
  const base = {
    resourcePath: options.resourcePath ?? "",
    additionalParameters: options.query ?? {},
    fields: options.fields ?? [],
  };
  switch (method) {
    case "read":
      return { ...base, method: "read" };
    case "delete":
      return { ...base, method: "delete", revision: null };
    case "create":
      return {
        ...base,
        method: "create",
        newResourceId: options.newResourceId ?? null,
        content: options.content,
      };
    case "update":
      return {
        ...base,
        method: "update",
        revision: null,
        content: options.content,
      };
    case "action":
      return {
        ...base,
        method: "action",
        action: options.action ?? "",
        content: options.content,
      };
    case "patch":
      return {
        ...base,
        method: "patch",
        revision: null,
        patchOperations: options.patchOperations ?? [],
      };
    case "query":
      return {
        ...base,
        method: "query",
        queryFilter: "true",
        queryId: null,
        queryExpression: null,
        pageSize: 0,
        pagedResultsOffset: 0,
        pagedResultsCookie: null,
        sortKeys: [],
      };
  }
}

export interface ContextOptions {
  headers?: Record<string, string>;
  scopes?: string[];
  /** Omit the HTTP context entirely — a scheduled/internal caller. */
  internal?: boolean;
}

export function callContext(options: ContextOptions = {}): IdmCallContext {
  const context: IdmCallContext = {
    security: {
      authenticationId: "svc-account",
      authorization: {
        id: "svc-account",
        component: "managed/svcacct",
        roles: ["internal/role/openidm-authorized"],
      },
    },
  };
  if (options.internal !== true) {
    context.http = {
      method: "GET",
      path: "/openidm/endpoint/demo",
      headers: options.headers ?? {},
      parameters: {},
    };
  }
  if (options.scopes !== undefined) {
    context.oauth2 = { scopes: javaSet(options.scopes) };
  }
  return context;
}

type StoredValue = Record<string, unknown> & { _id: string; _rev: string };

/** Everything the double cannot model throws this, so it is never mistaken
 * for a fault the tenant would raise. */
function unsupported(what: string): never {
  throw new Error("managedStore: " + what);
}

/**
 * Apply a `fields` selector the way the tenant does: only the named members
 * come back, and `_id`/`_rev` come back whatever you asked for (verified
 * 2026-08-17, docs/api/10-managed-objects.md).
 */
function projectRecord(
  record: StoredValue,
  fields: readonly string[] | null | undefined
): StoredValue {
  if (fields === null || fields === undefined || fields.indexOf("*") >= 0) {
    return { ...record };
  }
  const out: StoredValue = { _id: record._id, _rev: record._rev };
  for (const field of fields) {
    if (field.indexOf("/") >= 0) {
      // A relationship path (`manager/userName`) makes the tenant return the
      // EXPANSION, and the double holds no relationship graph to expand.
      unsupported(
        "cannot expand the relationship path " +
          field +
          " — give the handler its own double for that read"
      );
    }
    if (Object.prototype.hasOwnProperty.call(record, field)) {
      out[field] = record[field];
    }
  }
  return out;
}

/** `true`, or a single `field eq "value"` term — anything else is refused. */
function matchesFilter(record: StoredValue, filter: unknown): boolean {
  if (filter === undefined || filter === null || filter === "true") {
    return true;
  }
  if (typeof filter !== "string") {
    unsupported("_queryFilter must be a string");
  }
  const term = /^\/?([A-Za-z_][A-Za-z0-9_]*) eq "([^"]*)"$/.exec(filter.trim());
  if (term === null) {
    unsupported(
      'only _queryFilter: true and a single `field eq "value"` term are ' +
        "modelled, not " +
        filter
    );
  }
  return record[term[1] as string] === term[2];
}

/**
 * An in-memory `openidm` binding for endpoint tests.
 *
 * Keys are managed collection paths and values are their records. The double
 * implements the common CRUD/query behavior; tests needing a special action
 * can override that member on the returned object.
 *
 * IT REFUSES WHAT IT CANNOT MODEL, and that is the point. A double more
 * permissive than the tenant turns a live 500 into a green test: this one
 * previously ignored the `fields` selector and the `_queryFilter` outright, so
 * a projection bug and an unfiltered query both passed. Anything unmodelled now
 * throws a `managedStore:` error naming what to do instead.
 *
 * Not modelled, on purpose: relationship expansion, paging, sort keys, patch
 * and action. `openidm.update`/`delete` against a missing id throw here because
 * IDM's own behaviour for that miss is NOT verified (docs/api/10 records the
 * `read` miss and the `create` conflict only) — inventing a shape would be
 * worse than refusing.
 */
export function managedStore(
  initial: Record<string, StoredValue[]>
): typeof openidm {
  const collections: Record<string, StoredValue[]> = {};
  for (const path of Object.keys(initial)) {
    collections[path] = initial[path]?.map((record) => ({ ...record })) ?? [];
  }
  const splitRecordPath = (path: string): [string, string] => {
    const slash = path.lastIndexOf("/");
    return [path.slice(0, slash), path.slice(slash + 1)];
  };
  const binding = {
    read(
      path: string,
      _params?: unknown,
      fields?: readonly string[] | null
    ): StoredValue | null {
      const [collection, id] = splitRecordPath(path);
      const found = collections[collection]?.find(
        (record) => record._id === id
      );
      // A miss is `null`, never a throw (verified 2026-07-17 and 2026-08-17).
      // The copy matters: handing out the stored object let a handler mutate
      // the store through its own result.
      return found === undefined ? null : projectRecord(found, fields);
    },
    query(
      path: string,
      params?: Record<string, unknown> | null,
      fields?: readonly string[] | null
    ) {
      if (params !== undefined && params !== null) {
        for (const key of Object.keys(params)) {
          if (key !== "_queryFilter") {
            unsupported(
              "query parameter " + key + " is not modelled (only _queryFilter)"
            );
          }
        }
      }
      const filter = params === undefined || params === null
        ? undefined
        : params["_queryFilter"];
      const result = (collections[path] ?? [])
        .filter((record) => matchesFilter(record, filter))
        .map((record) => projectRecord(record, fields));
      return {
        result,
        resultCount: result.length,
        pagedResultsCookie: null,
        totalPagedResults: result.length,
        totalPagedResultsPolicy: "EXACT",
      };
    },
    create(
      path: string,
      newResourceId: string | null,
      content: Record<string, unknown>
    ) {
      const rows = (collections[path] ??= []);
      const id = newResourceId ?? "test-" + (rows.length + 1);
      if (rows.some((record) => record._id === id)) {
        // Verified: `openidm.create` NEVER upserts — it throws
        // PreconditionFailedException (docs/api/10-managed-objects.md).
        unsupported("create conflicts with the existing record " + path + "/" + id);
      }
      const created: StoredValue = { ...content, _id: id, _rev: "1" };
      rows.push(created);
      return { ...created };
    },
    update(
      path: string,
      _revision: string | null,
      content: Record<string, unknown>
    ) {
      const [collection, id] = splitRecordPath(path);
      const rows = (collections[collection] ??= []);
      const index = rows.findIndex((record) => record._id === id);
      const existing = rows[index];
      if (index < 0 || existing === undefined) {
        unsupported("update of a record that does not exist: " + path);
      }
      // Fixtures usually carry a numeric-looking `_rev`; a real IDM revision is
      // opaque, so fall back rather than producing `NaN`.
      const revision = Number(existing._rev);
      const updated: StoredValue = {
        ...existing,
        ...content,
        _id: id,
        _rev: String((Number.isFinite(revision) ? revision : 0) + 1),
      };
      rows[index] = updated;
      return { ...updated };
    },
    patch() {
      return unsupported("patch is not modelled");
    },
    delete(path: string) {
      const [collection, id] = splitRecordPath(path);
      const rows = collections[collection] ?? [];
      const index = rows.findIndex((record) => record._id === id);
      if (index < 0) {
        unsupported("delete of a record that does not exist: " + path);
      }
      return rows.splice(index, 1)[0] as StoredValue;
    },
    action() {
      return unsupported("action is not modelled");
    },
  };
  return binding as unknown as typeof openidm;
}

/** Install an `openidm` test binding for exactly one synchronous callback. */
export function withOpenIdm<T>(binding: typeof openidm, run: () => T): T {
  const globals = globalThis as unknown as Record<string, unknown>;
  const hadPrevious = Object.prototype.hasOwnProperty.call(globals, "openidm");
  const previous = globals["openidm"];
  globals["openidm"] = binding;
  try {
    return run();
  } finally {
    if (hadPrevious) {
      globals["openidm"] = previous;
    } else {
      delete globals["openidm"];
    }
  }
}
