// The `managedStore` double's own gate.
//
// WHY THIS FILE EXISTS. A test double that is more permissive than the tenant
// converts a live failure into a green test, and this one was: it ignored the
// `fields` selector and the `_queryFilter` outright, so an endpoint that
// mis-projected a read or forgot to filter a query passed here and 500'd (or
// leaked rows) against IDM. The assertions below pin the two directions that
// matter — what the double reproduces faithfully, and what it REFUSES rather
// than approximating.
//
// Managed file — regenerated by `aic workspace update`.

import assert from "node:assert/strict";
import { test } from "node:test";

import { managedStore, withOpenIdm } from "./harness.ts";

/** Its own managed object, so the file does not lean on a tenant's schema. */
interface HarnessProbe {
  _id?: string;
  _rev?: string;
  userName: string;
  mail: string;
  sn: string;
  manager?: { _ref: string };
}

declare global {
  interface ManagedObjects {
    "managed/__aic_harness_probe": HarnessProbe;
  }
}

const COLLECTION = "managed/__aic_harness_probe";

function store() {
  return managedStore({
    [COLLECTION]: [
      { _id: "a", _rev: "1", userName: "ada", mail: "ada@x.invalid", sn: "L" },
      { _id: "b", _rev: "1", userName: "bob", mail: "bob@x.invalid", sn: "B" },
    ],
  });
}

test("a fields selector projects, and keeps _id/_rev regardless", () => {
  const row = store().read(`${COLLECTION}/a`, null, ["userName"]);
  assert.deepEqual(row, { _id: "a", _rev: "1", userName: "ada" });
});

test("a fields selector of * opts out of projection", () => {
  const row = store().read(`${COLLECTION}/a`, null, ["*"]);
  assert.equal(Object.keys(row ?? {}).length, 5);
});

test("a read miss is null, never a throw", () => {
  assert.equal(store().read(`${COLLECTION}/nope`), null);
});

test("a read result is a copy, so a handler cannot mutate the store", () => {
  const bound = store();
  const row = bound.read(`${COLLECTION}/a`);
  if (row === null) {
    throw new Error("fixture missing");
  }
  row.userName = "MUTATED";
  assert.equal(bound.read(`${COLLECTION}/a`)?.userName, "ada");
});

test("a _queryFilter term actually filters", () => {
  const page = store().query(COLLECTION, {
    _queryFilter: '/userName eq "ada"',
  });
  assert.equal(page.resultCount, 1);
  assert.equal(page.result[0]?.userName, "ada");
});

test("_queryFilter true returns every row, and fields project them", () => {
  const page = store().query(COLLECTION, { _queryFilter: "true" }, ["mail"]);
  assert.deepEqual(page.result, [
    { _id: "a", _rev: "1", mail: "ada@x.invalid" },
    { _id: "b", _rev: "1", mail: "bob@x.invalid" },
  ]);
});

test("create refuses to upsert, the way openidm.create does", () => {
  assert.throws(
    () => store().create(COLLECTION, "a", { userName: "clash" }),
    /managedStore: create conflicts/
  );
});

test("update bumps the revision and merges", () => {
  const updated = store().update(`${COLLECTION}/a`, null, { sn: "Lovelace" });
  assert.equal(updated._rev, "2");
  assert.equal(updated.sn, "Lovelace");
  assert.equal(updated.userName, "ada");
});

// Everything the double will not approximate. Each of these was previously a
// silent wrong answer.
const refusals: readonly (readonly [string, () => unknown, RegExp])[] = [
  [
    "a relationship path, which needs a graph the double has not got",
    () => store().read(`${COLLECTION}/a`, null, ["manager/userName"]),
    /cannot expand the relationship path/,
  ],
  [
    "a query filter beyond a single equality term",
    () => store().query(COLLECTION, { _queryFilter: '/sn sw "L"' }),
    /only _queryFilter: true and a single/,
  ],
  [
    "a query parameter it does not model, rather than ignoring it",
    () => store().query(COLLECTION, { _queryFilter: "true", _pageSize: 1 }),
    /query parameter _pageSize is not modelled/,
  ],
  [
    "update of a record that is not there",
    () => store().update(`${COLLECTION}/nope`, null, {}),
    /update of a record that does not exist/,
  ],
  [
    "delete of a record that is not there",
    () => store().delete(`${COLLECTION}/nope`, null),
    /delete of a record that does not exist/,
  ],
  [
    "patch, which is not modelled at all",
    () => store().patch(`${COLLECTION}/a`, null, []),
    /patch is not modelled/,
  ],
];

for (const [name, call, message] of refusals) {
  test("refuses " + name, () => assert.throws(call, message));
}

test("withOpenIdm installs and then removes the global binding", () => {
  const had = "openidm" in globalThis;
  const seen = withOpenIdm(store(), () => openidm.read(`${COLLECTION}/a`));
  assert.equal(seen?.userName, "ada");
  assert.equal("openidm" in globalThis, had);
});
