// Structured logging + redaction.
// Managed file — regenerated by `aic workspace update`.

import assert from "node:assert/strict";
import { test } from "node:test";

import {
  createRequestLogger,
  describeCaller,
  renderFields,
} from "../framework/index.ts";
import { callContext, recordingLogger } from "./harness.ts";

test("fields render as key=value with the message last", () => {
  assert.equal(
    renderFields({ endpoint: "widgets", count: 3, msg: "listed" }),
    "endpoint=widgets count=3 msg=listed"
  );
});

test("values with spaces or equals signs are quoted", () => {
  assert.equal(renderFields({ msg: "two words" }), 'msg="two words"');
  assert.equal(renderFields({ k: "a=b" }), 'k="a=b"');
});

test("undefined fields are dropped rather than rendered", () => {
  assert.equal(renderFields({ a: 1, b: undefined }), "a=1");
});

test("credential-shaped field names are redacted by name", () => {
  const rendered = renderFields({
    authorization: "Bearer abc",
    sessionToken: "xyz",
    apiSecret: "s3cret",
    userPassword: "hunter2",
    safe: "kept",
  });
  assert.equal(
    rendered,
    "authorization=[redacted] sessionToken=[redacted] apiSecret=[redacted] userPassword=[redacted] safe=kept"
  );
});

test("whole binding structures are refused however deeply they are nested", () => {
  assert.equal(
    renderFields({ context: { anything: 1 } }),
    "context=[redacted]"
  );
  assert.equal(
    renderFields({ outer: { headers: { a: "b" } } }),
    "outer={headers=[redacted]}"
  );
});

test("long strings are clipped so one field cannot flood the log", () => {
  const rendered = renderFields({ blob: "x".repeat(500) });
  assert.ok(rendered.length < 260, rendered.length + " chars");
  assert.ok(rendered.endsWith("…"));
});

test("nesting stops at a fixed depth", () => {
  assert.equal(renderFields({ a: { b: { c: { d: 1 } } } }), "a={b={c={d=1}}}");
  assert.equal(
    renderFields({ a: { b: { c: { d: { e: 1 } } } } }),
    "a={b={c={d=…}}}"
  );
});

test("arrays render inline and are capped", () => {
  assert.equal(renderFields({ tags: ["a", "b"] }), "tags=[a,b]");
  const many = renderFields({
    n: Array.from({ length: 40 }, (_unused, index) => index),
  });
  assert.ok(many.endsWith(",…]"));
});

test("child loggers accumulate base fields", () => {
  const sink = recordingLogger();
  const log = createRequestLogger(sink, { endpoint: "widgets" });
  log
    .child({ cid: "abc" })
    .child({ route: "read /{id}" })
    .info("hello", { n: 1 });
  assert.equal(
    sink.lines[0]?.message,
    'endpoint=widgets cid=abc route="read /{id}" n=1 msg=hello'
  );
  assert.equal(sink.lines[0]?.level, "info");
});

test("each level reaches the matching binding method", () => {
  const sink = recordingLogger();
  const log = createRequestLogger(sink);
  log.debug("d");
  log.info("i");
  log.warn("w");
  log.error("e");
  assert.deepEqual(
    sink.lines.map((line) => line.level),
    ["debug", "info", "warn", "error"]
  );
});

test("describeCaller projects identity without touching credentials", () => {
  const fields = describeCaller(
    callContext({ headers: { authorization: "Bearer secret" }, scopes: ["a"] })
  );
  assert.deepEqual(fields, {
    authId: "svc-account",
    principal: "svc-account",
    component: "managed/svcacct",
    httpMethod: "GET",
    httpPath: "/openidm/endpoint/demo",
  });
  assert.equal(JSON.stringify(fields).includes("secret"), false);
});

test("describeCaller marks a non-HTTP origin instead of dereferencing http", () => {
  const fields = describeCaller(callContext({ internal: true }));
  assert.equal(fields["origin"], "internal");
  assert.equal(fields["httpPath"], undefined);
});
