// The managed-object type generator.
//
// These assertions drive the real generator, not a copy of its rules, and each
// one names the case where a plausible-but-wrong implementation would differ.
//
// Managed file — regenerated by `fo upgrade`.

import assert from "node:assert/strict";
import test from "node:test";

import { generateManagedTypes, typeName } from "../tools/managed-types.mjs";

const FIXTURE = {
  objects: [
    {
      name: "user",
      schema: {
        title: "User",
        required: ["userName", "mail"],
        properties: {
          userName: { type: "string", title: "Username" },
          mail: { type: "string", description: "Email Address" },
          description: { type: "string", title: "Description" },
          enabled: { type: "boolean" },
          loginCount: { type: ["number", "null"] },
          aliasList: { type: "array", items: { type: "string" } },
          roles: { type: "array", items: { type: "relationship" } },
          manager: { type: "relationship" },
          preferences: {
            type: "object",
            properties: { updates: { type: "boolean" } },
          },
          blob: { type: "object" },
          _id: { type: "string" },
          "odd-name": { type: "string" },
          mystery: {},
        },
      },
    },
    { name: "ai-agent", schema: { properties: { id: { type: "string" } } } },
  ],
};

const OUT = generateManagedTypes(FIXTURE);

function line(needle) {
  const found = OUT.split("\n").find((l) => l.trim().startsWith(needle));
  assert.ok(found, `no line starting with ${needle} in:\n${OUT}`);
  return found.trim();
}

test("a required property is neither optional nor nullable", () => {
  assert.equal(line("userName"), "userName: string;");
  assert.equal(line("mail:"), "mail: string;");
});

test("an optional property is nullable, because PingIDM returns JSON null", () => {
  // The whole point. `description?: string` type-checks
  // `if (u.description !== undefined) u.description.indexOf(...)`, which then
  // throws on a cleared property — the exact defect found against a live IDM
  // while writing example-stale-accounts.
  assert.equal(line("description?"), "description?: string | null;");
  assert.equal(line("enabled?"), "enabled?: boolean | null;");
});

test("a schema that already declares null is not double-nulled", () => {
  // `["number","null"]` is already nullable; appending another `| null` would
  // be harmless but says the generator is pattern-matching text rather than
  // reading the schema.
  assert.equal(line("loginCount?"), "loginCount?: number | null;");
});

test("arrays keep their item type", () => {
  assert.equal(line("aliasList?"), "aliasList?: string[] | null;");
  assert.equal(line("roles?"), "roles?: ManagedRelationship[] | null;");
  assert.equal(line("manager?"), "manager?: ManagedRelationship | null;");
});

test("a nested object still gets its own null", () => {
  // Discriminating case for a real bug: an earlier version decided nullability
  // by searching the RENDERED type for "null", so an object whose members were
  // nullable looked like it had already declared null and silently lost its
  // own. `preferences` is exactly that shape.
  assert.match(OUT, /preferences\?: \{[\s\S]*?\n {2}\} \| null;/);
  assert.match(OUT, /updates\?: boolean \| null;/);
});

test("an object with no properties degrades to a record", () => {
  assert.equal(line("blob?"), "blob?: Record<string, unknown> | null;");
});

test("a property with no type at all is unknown, not any", () => {
  assert.equal(line("mystery?"), "mystery?: unknown | null;");
});

test("a property name that is not an identifier is quoted", () => {
  assert.equal(line('"odd-name"'), '"odd-name"?: string | null;');
  assert.equal(line("_id?"), "_id?: string | null;");
});

test("object names become interfaces and a lookup map", () => {
  assert.equal(typeName("user"), "ManagedUser");
  assert.equal(typeName("ai-agent"), "ManagedAiAgent");
  assert.match(OUT, /export interface ManagedUser \{/);
  assert.match(OUT, /export interface ManagedAiAgent \{/);
  // Keyed by COLLECTION PATH inside `declare global`, because that is the
  // seam framework/idm-globals.d.ts declares empty. A plain exported
  // interface, or keys without the `managed/` prefix, both compile and augment
  // nothing - every `openidm.read` then silently falls back to CrestResource.
  assert.match(
    OUT,
    /declare global \{\n {2}\/\*\*[^\n]*\*\/\n {2}interface ManagedObjects \{\n {4}"managed\/user": ManagedUser;\n {4}"managed\/ai-agent": ManagedAiAgent;\n {2}\}\n\}/,
  );
});

test("a managed.json with no objects array is an error, not empty output", () => {
  assert.throws(() => generateManagedTypes({}), /objects/);
});
