// Full OpenAPI 3.1 meta-schema validation of the generated document.
//
// Managed file — regenerated by `fo upgrade`.

import assert from "node:assert/strict";
import { test } from "node:test";

import { validate } from "@hyperjump/json-schema/openapi-3-1";

import { toOpenApi } from "../framework/index.ts";
import hello from "../src/endpoints/hello.ts";

const ENDPOINTS = [hello];

test("the generated document validates against the OpenAPI 3.1 meta-schema", async () => {
  for (const endpoint of ENDPOINTS) {
    const result = await validate(
      "https://spec.openapis.org/oas/3.1/schema",
      toOpenApi(endpoint.definition),
    );
    assert.equal(
      result.valid,
      true,
      endpoint.definition.name + JSON.stringify(result),
    );
  }
});

test("every route declares a success response schema", () => {
  for (const endpoint of ENDPOINTS) {
    for (const route of endpoint.definition.routes) {
      assert.ok(
        route.response !== undefined && Object.keys(route.response).length > 0,
      );
    }
  }
});
