// OpenAPI 3.1 generation, including the CREST `?_action=` wrinkle.
// Managed file — regenerated by `aic workspace update`.

import assert from "node:assert/strict";
import { test } from "node:test";

import {
  defineEndpoint,
  queryResult,
  queryRoute,
  route,
  toOpenApi,
  v,
} from "../framework/index.ts";

const endpoint = defineEndpoint({
  name: "widgets",
  summary: "Widgets",
  version: "2.1.0",
  headers: { "x-request-id": v.optional(v.uuid()) },
  routes: [
    queryRoute({
      path: "/",
      query: { limit: v.withDefault(v.integer({ min: 1, max: 100 }), 20) },
      // Declares one ROW; the generator wraps the paging envelope around it.
      response: v.object({ _id: v.string(), name: v.string() }),
      handler: () => queryResult([]),
    }),
    route({
      method: "create",
      path: "/",
      body: v.object({ name: v.string({ maxLength: 64 }) }),
      handler: () => ({}),
    }),
    route({
      method: "action",
      action: "bulkImport",
      path: "/",
      scopes: ["demo:write"],
      body: v.object({ items: v.list(v.string(), { maxItems: 50 }) }),
      handler: () => ({}),
    }),
    route({
      method: "read",
      path: "/{id}",
      params: { id: v.string({ pattern: /^w-/ }) },
      query: { expand: v.optional(v.csv(v.enumOf(["owner", "history"]))) },
      // The response is the VALIDATOR now; the generator reads `.schema`.
      response: v.object({ _id: v.string() }),
      handler: ({ params }) => ({ _id: params.id }),
    }),
    route({
      method: "action",
      action: "retire",
      path: "/{id}",
      scopes: ["demo:write"],
      params: { id: v.string() },
      body: v.object({ reason: v.string() }),
      handler: () => ({}),
    }),
  ],
});

const document = toOpenApi(endpoint.definition, {
  serverUrl: "https://t.example",
});
const paths = document["paths"] as Record<string, Record<string, unknown>>;
const base = "/openidm/endpoint/widgets";

function operation(key: string, method: string): Record<string, unknown> {
  const value = paths[key]?.[method];
  assert.ok(value !== undefined, "no " + method + " on " + key);
  return value as Record<string, unknown>;
}

function parameter(key: string, method: string, name: string) {
  const parameters = operation(key, method)["parameters"] as
    Record<string, unknown>[] | undefined;
  const value = parameters?.find((candidate) => candidate["name"] === name);
  assert.ok(value !== undefined, "no parameter " + name);
  return value;
}

const rootGet = operation(base, "get");
const rootPost = operation(base, "post");
const itemGet = operation(base + "/{id}", "get");
const retirePost = operation(base + "/{id}:retire", "post");
const bulkAction = parameter(base + ":bulkImport", "post", "_action");
const id = parameter(base + "/{id}", "get", "id");
const expand = parameter(base + "/{id}", "get", "expand");

type ShapeCase = readonly [name: string, actual: unknown, expected: unknown];
const shapeCases: ShapeCase[] = [
  ["document version", document["openapi"], "3.1.0"],
  ["JSON Schema dialect", document["jsonSchemaDialect"], "https://json-schema.org/draft/2020-12/schema"],
  ["server URL", document["servers"], [{ url: "https://t.example" }]],
  ["document info", document["info"], { title: "Widgets", version: "2.1.0" }],
  ["stable RPC path keys", Object.keys(paths).sort(), [base, base + "/{id}", base + "/{id}:retire", base + ":bulkImport"]],
  ["ordinary route is not synthetic", rootGet["x-crest-synthetic-path-key"], undefined],
  ["root POST remains create", rootPost["x-crest-method"], "create"],
  ["synthetic action metadata", [retirePost["x-crest-synthetic-path-key"], retirePost["x-crest-action"], retirePost["x-crest-path"]], [true, "retire", base + "/{id}"]],
  ["action discriminator", [bulkAction["in"], bulkAction["required"], bulkAction["schema"]], ["query", true, { type: "string", enum: ["bulkImport"] }]],
  ["create discriminator", parameter(base, "post", "_action")["schema"], { type: "string", enum: ["create"] }],
  ["query discriminator", parameter(base, "get", "_queryFilter")["required"], true],
  ["path parameter", [id["in"], id["required"]], ["path", true]],
  ["CSV query parameter", [expand["required"], expand["style"], expand["explode"]], [false, "form", false]],
  ["required scopes", [retirePost["x-required-scopes"], retirePost["security"]], [["demo:write"], [{ oauth2: ["demo:write"] }]]],
  ["unscoped route", itemGet["security"], undefined],
  ["declared body schema", rootPost["requestBody"], {
    required: true,
    content: { "application/json": { schema: {
      type: "object",
      properties: { name: { type: "string", maxLength: 64 } },
      additionalProperties: false,
      required: ["name"],
    } } },
  }],
];

for (const [name, actual, expected] of shapeCases) {
  test("OpenAPI shape: " + name, () => assert.deepEqual(actual, expected));
}

test("the endpoint-wide header appears on every operation", () => {
  for (const [key, methods] of Object.entries(paths)) {
    for (const method of Object.keys(methods)) {
      assert.equal(parameter(key, method, "x-request-id")["in"], "header");
    }
  }
});

test("non-empty security scopes only reference an OAuth-capable scheme", () => {
  const components = document["components"] as {
    securitySchemes: Record<string, Record<string, unknown>>;
  };
  for (const methods of Object.values(paths)) {
    for (const value of Object.values(methods)) {
      const security = (value as Record<string, unknown>)["security"] as
        Record<string, string[]>[] | undefined;
      for (const requirement of security ?? []) {
        for (const [name, scopes] of Object.entries(requirement)) {
          if (scopes.length > 0) {
            assert.ok(
              ["oauth2", "openIdConnect"].includes(
                String(components.securitySchemes[name]?.["type"])
              )
            );
          }
        }
      }
    }
  }
  const oauth2 = components.securitySchemes["oauth2"] as {
    flows: { clientCredentials: { scopes: Record<string, string> } };
  };
  assert.deepEqual(oauth2.flows.clientCredentials.scopes, {
    "demo:write": "Required by one or more endpoint routes.",
  });
});

test("every operation documents CREST errors and its success schema", () => {
  const responses = operation(base + "/{id}", "get")["responses"] as Record<
    string,
    { content: { "application/json": { schema: Record<string, unknown> } } }
  >;
  for (const status of ["400", "401", "403", "404", "405", "500"]) {
    assert.equal(
      responses[status]?.content["application/json"].schema["$ref"],
      "#/components/schemas/CrestError"
    );
  }
  // The 200 schema comes off the response VALIDATOR, so it carries the members
  // and `required` the validator would enforce — not a hand-written stand-in
  // that could disagree with the handler.
  assert.deepEqual(responses["200"]?.content["application/json"].schema, {
    type: "object",
    properties: { _id: { type: "string" } },
    required: ["_id"],
    additionalProperties: false,
  });
});

test("a query route's 200 schema is the envelope around its declared row", () => {
  // The route declares ONE ROW; the generator wraps it, so the document and the
  // handler's checked return type come from the same declaration.
  const responses = operation(base, "get")["responses"] as Record<
    string,
    { content: { "application/json": { schema: Record<string, unknown> } } }
  >;
  const schema = responses["200"]?.content["application/json"].schema as {
    properties: Record<string, Record<string, unknown>>;
    required: string[];
  };
  assert.deepEqual(schema.properties["result"], {
    type: "array",
    items: {
      type: "object",
      properties: { _id: { type: "string" }, name: { type: "string" } },
      required: ["_id", "name"],
      additionalProperties: false,
    },
  });
  // Every paging member IDM requires is documented, not just `result`.
  assert.deepEqual(schema.required.sort(), [
    "pagedResultsCookie",
    "remainingPagedResults",
    "result",
    "resultCount",
    "totalPagedResults",
    "totalPagedResultsPolicy",
  ]);
});

test("operation ids are unique and stable", () => {
  const ids = Object.entries(paths).flatMap(([key, methods]) =>
    Object.keys(methods).map(
      (method) => operation(key, method)["operationId"] as string
    )
  );
  assert.equal(new Set(ids).size, ids.length);
  assert.ok(ids.includes("widgets_action_retire_id"));
});
