// Routing and dispatch. Managed file — regenerated by `aic workspace update`.

import assert from "node:assert/strict";
import { test } from "node:test";

import {
  defineEndpoint,
  forwardQuery,
  parsePath,
  queryResult,
  queryRoute,
  route,
  splitResourcePath,
  v,
  type CrestRequest,
  type IdmCallContext,
} from "../framework/index.ts";
import {
  callContext,
  crestErrorFrom,
  crestRequest,
  recordingLogger,
} from "./harness.ts";

const demo = defineEndpoint({
  name: "demo",
  headers: { "x-request-id": v.optional(v.uuid()) },
  routes: [
    queryRoute({
      path: "/",
      query: { limit: v.withDefault(v.integer({ min: 1, max: 10 }), 3) },
      handler: ({ query }) => queryResult([{ _id: String(query.limit) }]),
    }),
    route({
      method: "read",
      path: "/{id}",
      params: { id: v.string({ pattern: /^[a-z]+$/ }) },
      handler: ({ params, correlationId }) => ({
        id: params.id,
        correlationId,
      }),
    }),
    route({
      method: "read",
      path: "/daily/{date}",
      params: { date: v.isoDate() },
      handler: ({ params }) => ({ date: params.date }),
    }),
    route({
      method: "read",
      path: "/widget/{id}/summary",
      params: { id: v.string() },
      handler: ({ params }) => ({ summaryOf: params.id }),
    }),
    route({
      method: "create",
      path: "/",
      body: v.object({ name: v.string({ minLength: 1 }) }),
      handler: ({ body }) => ({ created: body.name }),
    }),
    route({
      method: "patch",
      path: "/{id}",
      params: { id: v.string() },
      patches: v.patchOperations({ minItems: 1 }),
      handler: ({ patchOperations }) => ({ ops: patchOperations.length }),
    }),
    route({
      method: "action",
      action: "retire",
      path: "/{id}",
      scopes: ["demo:write"],
      params: { id: v.string() },
      body: v.object({ reason: v.string({ minLength: 1 }) }),
      handler: ({ params, body }) => ({ retired: params.id, why: body.reason }),
    }),
  ],
});

test("parsePath splits literals and captures", () => {
  assert.deepEqual(parsePath("/"), []);
  assert.deepEqual(parsePath("/{id}"), [{ param: "id" }]);
  assert.deepEqual(parsePath("/widget/{id}/summary"), [
    { literal: "widget" },
    { param: "id" },
    { literal: "summary" },
  ]);
});

test("splitResourcePath decodes each segment and drops empties", () => {
  assert.deepEqual(splitResourcePath(""), []);
  assert.deepEqual(splitResourcePath("a/b/c"), ["a", "b", "c"]);
  assert.deepEqual(splitResourcePath("a%2Fb"), ["a/b"]);
  assert.deepEqual(splitResourcePath("bad%"), ["bad%"]);
});

type RouteCase = readonly [name: string, request: CrestRequest, select: (result: unknown) => unknown, expected: unknown, context?: IdmCallContext];

const routeCases: RouteCase[] = [
  ["root query applies defaults", crestRequest("query"), (x) => (x as { result: unknown }).result, [{ _id: "3" }]],
  ["query input overrides defaults", crestRequest("query", { query: { limit: "7" } }), (x) => (x as { result: unknown }).result, [{ _id: "7" }]],
  ["literal beats a same-length capture", crestRequest("read", { resourcePath: "daily/2026-08-13" }), (x) => (x as { date: string }).date, "2026-08-13"],
  ["capture matches in the middle", crestRequest("read", { resourcePath: "widget/w-abcd/summary" }), (x) => (x as { summaryOf: string }).summaryOf, "w-abcd"],
  [
    "matching action admits its scope",
    crestRequest("action", {
      resourcePath: "abc",
      action: "retire",
      content: { reason: "obsolete" },
    }),
    (x) => x,
    { retired: "abc", why: "obsolete" },
    callContext({ scopes: ["demo:write", "other"] })
  ],
];

for (const [name, request, select, expected, context] of routeCases) {
  test(name, () => {
    const result = demo.dispatch(request, context ?? callContext());
    assert.deepEqual(select(result), expected);
  });
}

test("the object thrown to IDM contains no private framework keys", () => {
  const response = crestErrorFrom(() =>
    demo.dispatch(crestRequest("read", { resourcePath: "not/a/route" }), callContext())
  );
  assert.deepEqual(Object.keys(response).sort(), ["code", "detail", "message"]);
  assert.deepEqual(Object.keys(response).filter((key) => key.startsWith("__")), []);
  assert.equal(Object.prototype.hasOwnProperty.call(response, "reason"), false);
});

interface ErrorCase {
  name: string;
  request: CrestRequest;
  context?: IdmCallContext;
  code: number;
  issuePath?: string;
  detail?: { key: string; value: unknown };
}

function fails(
  name: string,
  request: CrestRequest,
  code: number,
  expected: Pick<ErrorCase, "context" | "issuePath" | "detail"> = {}
): ErrorCase {
  return { name, request, code, ...expected };
}

function actionRequest(action: string, reason: string): CrestRequest {
  return crestRequest("action", { resourcePath: "abc", action, content: { reason } });
}

const errorCases: ErrorCase[] = [
  fails("unmatched path is a 404", crestRequest("read", { resourcePath: "a/b/c/d" }), 404),
  fails("known path under another method is a 405", crestRequest("update", { resourcePath: "abc", content: {} }), 405, {
    detail: { key: "allowed", value: ["read", "patch", "action"] },
  }),
  fails("unknown action is a 404", actionRequest("explode", ""), 404, {
    context: callContext({ scopes: ["demo:write"] }),
    detail: { key: "supported", value: ["retire"] },
  }),
  fails("invalid path parameter is a 400", crestRequest("read", { resourcePath: "ABC" }), 400, { issuePath: "path.id" }),
  fails("out-of-range query parameter is a 400", crestRequest("query", { query: { limit: "99" } }), 400, { issuePath: "query.limit" }),
  fails("malformed body is a 400", crestRequest("create", { content: { name: "" } }), 400),
  fails("missing body is a 400", crestRequest("create"), 400, { issuePath: "body" }),
  // The invalid body deliberately proves authorization happens before schema disclosure.
  fails("missing scope is a 403 before body validation", actionRequest("retire", ""), 403, {
    context: callContext({ scopes: ["something:else"] }),
    detail: { key: "missing", value: ["demo:write"] },
  }),
  fails("missing OAuth context is a 403", actionRequest("retire", "obsolete"), 403),
  fails("malformed correlation header is a 400", crestRequest("read", { resourcePath: "abc" }), 400, {
    context: callContext({ headers: { "x-request-id": "nope" } }),
    issuePath: "header.x-request-id",
  }),
];

for (const row of errorCases) {
  test(row.name, () => {
    const response = crestErrorFrom(() =>
      demo.dispatch(row.request, row.context ?? callContext())
    );
    assert.equal(response.code, row.code);
    if (row.issuePath !== undefined) {
      const detail = response.detail as { issues: { path: string }[] };
      assert.equal(detail.issues[0]?.path, row.issuePath);
    }
    if (row.detail !== undefined) {
      assert.deepEqual(
        (response.detail as Record<string, unknown>)[row.detail.key],
        row.detail.value
      );
    }
  });
}

test("patch operations are validated before the handler sees them", () => {
  const ok = demo.dispatch(
    crestRequest("patch", {
      resourcePath: "abc",
      patchOperations: [{ operation: "replace", field: "/name", value: "n" }],
    }),
    callContext()
  ) as { ops: number };
  assert.equal(ok.ops, 1);

  const fault = crestErrorFrom(() =>
    demo.dispatch(
      crestRequest("patch", { resourcePath: "abc", patchOperations: [] }),
      callContext()
    )
  );
  assert.equal(fault.code, 400);
});

test("the x-request-id header becomes the correlation id, case-insensitively", () => {
  const id = "3f1a2b4c-5d6e-4f70-8a9b-0c1d2e3f4a5b";
  const result = demo.dispatch(
    crestRequest("read", { resourcePath: "abc" }),
    callContext({ headers: { "X-Request-Id": id } })
  ) as { correlationId: string };
  assert.equal(result.correlationId, id);
});

test("a request without the header still gets a correlation id", () => {
  const result = demo.dispatch(
    crestRequest("read", { resourcePath: "abc" }),
    callContext()
  ) as { correlationId: string };
  assert.match(result.correlationId, /^aic-/);
});

test("dispatch works when there is no HTTP context at all", () => {
  const result = demo.dispatch(
    crestRequest("read", { resourcePath: "abc" }),
    callContext({ internal: true })
  ) as { id: string };
  assert.equal(result.id, "abc");
});

test("an unexpected throw becomes an opaque 500 and is logged", () => {
  const logger = recordingLogger();
  const exploding = defineEndpoint({
    name: "boom",
    routes: [
      route({
        method: "read",
        path: "/",
        handler: () => {
          throw new Error("connection string postgres://user:hunter2@db");
        },
      }),
    ],
  });
  const fault = crestErrorFrom(() =>
    exploding.dispatch(crestRequest("read"), callContext(), logger)
  );
  assert.equal(fault.code, 500);
  assert.equal(fault.message, "Internal error");
  assert.equal(fault.detail, undefined);
  const logged = logger.lines.filter((line) => line.level === "error");
  assert.equal(logged.length, 1);
  assert.match(String(logged[0]?.message), /unhandled failure/);
});

test("a bare PUT arrives as a create carrying the client-supplied id", () => {
  // CREST turns `PUT /endpoint/x/w-1` (no If-Match) into a create at the root
  // with `newResourceId: "w-1"` — probed live 2026-08-13.
  const result = demo.dispatch(
    crestRequest("create", { newResourceId: "w-1", content: { name: "n" } }),
    callContext()
  ) as { created: string };
  assert.equal(result.created, "n");
});

const invalidRouteCases = [
  ["capture without validator", () => route({ method: "read", path: "/{id}", handler: () => ({}) }), /has no validator/],
  ["validator without capture", () => route({ method: "read", path: "/", params: { id: v.string() }, handler: () => ({}) }), /is not in the path/],
  ["action without a name", () => route({ method: "action", path: "/", handler: () => ({}) }), /requires an action name/],
  ["non-action with an action name", () => route({ method: "read", path: "/", action: "retire", handler: () => ({}) }), /only an action route/],
] as const;

for (const [name, build, error] of invalidRouteCases) {
  test("route refuses " + name, () => assert.throws(build, error));
}

test("the endpoint definition survives to build time", () => {
  assert.equal(demo.definition.name, "demo");
  assert.equal(demo.definition.routes.length, 7);
  assert.equal(demo.definition.correlationHeader, "x-request-id");
});

test("ambiguous routes are rejected instead of silently shadowing", () => {
  const first = route({
    method: "read",
    path: "/a/{id}",
    params: { id: v.string() },
    handler: () => ({}),
  });
  const second = route({
    method: "read",
    path: "/{kind}/b",
    params: { kind: v.string() },
    handler: () => ({}),
  });
  assert.throws(
    () => defineEndpoint({ name: "ambiguous", routes: [first, second] }),
    /ambiguous routes/
  );
});

test("a more-specific route may intentionally overlap a parameter route", () => {
  assert.doesNotThrow(() =>
    defineEndpoint({
      name: "specific",
      routes: [
        route({ method: "read", path: "/fixed", handler: () => ({}) }),
        route({
          method: "read",
          path: "/{id}",
          params: { id: v.string() },
          handler: () => ({}),
        }),
      ],
    })
  );
});

test("optional runtime response validation catches dynamic result drift", () => {
  const endpoint = defineEndpoint({
    name: "checked",
    validateResponses: true,
    routes: [
      route({
        method: "read",
        path: "/",
        response: v.object({ count: v.integer() }),
        handler: () => ({ count: "not-an-integer" }) as never,
      }),
    ],
  });
  const fault = crestErrorFrom(() =>
    endpoint.dispatch(crestRequest("read"), callContext())
  );
  assert.equal(fault.code, 500);
  assert.equal(fault.message, "Internal error");
});

test("runtime response validation is off unless explicitly requested", () => {
  const endpoint = defineEndpoint({
    name: "unchecked",
    routes: [
      route({
        method: "read",
        path: "/",
        response: v.object({ count: v.integer() }),
        handler: () => ({ count: "dynamic" }) as never,
      }),
    ],
  });
  assert.deepEqual(
    endpoint.dispatch(crestRequest("read"), callContext()),
    { count: "dynamic" }
  );
  // …and a test can demand the check without the endpoint shipping it on.
  const fault = crestErrorFrom(() =>
    endpoint.dispatch(crestRequest("read"), callContext(), undefined, {
      validateResponses: true,
    })
  );
  assert.equal(fault.code, 500);
});

test("a per-call override can also turn response validation OFF", () => {
  const endpoint = defineEndpoint({
    name: "checked-off",
    validateResponses: true,
    routes: [
      route({
        method: "read",
        path: "/",
        response: v.object({ count: v.integer() }),
        handler: () => ({ count: "dynamic" }) as never,
      }),
    ],
  });
  assert.deepEqual(
    endpoint.dispatch(crestRequest("read"), callContext(), undefined, {
      validateResponses: false,
    }),
    { count: "dynamic" }
  );
});

test("forwardQuery keeps the store's paging, not the row count", () => {
  // What `openidm.query` hands back: no `remainingPagedResults`, and a cursor
  // plus a total that a mapped row set must not overwrite.
  const page = {
    result: [{ _id: "a" }, { _id: "b" }],
    resultCount: 2,
    pagedResultsCookie: "cursor-2",
    totalPagedResults: 57,
    totalPagedResultsPolicy: "EXACT",
  };
  assert.deepEqual(forwardQuery(page, [{ id: "a" }]), {
    result: [{ id: "a" }],
    resultCount: 2,
    pagedResultsCookie: "cursor-2",
    totalPagedResults: 57,
    remainingPagedResults: 0,
    totalPagedResultsPolicy: "EXACT",
  });
  // One argument forwards the page's own rows.
  assert.deepEqual(forwardQuery(page).result, page.result);
});

test("forwardQuery fills the envelope IDM requires from a bare page", () => {
  assert.deepEqual(forwardQuery({ result: [{ _id: "a" }] }), {
    result: [{ _id: "a" }],
    resultCount: 1,
    pagedResultsCookie: null,
    totalPagedResults: 1,
    remainingPagedResults: 0,
    totalPagedResultsPolicy: "EXACT",
  });
});

test("a forwarded page satisfies a query route's declared response", () => {
  const endpoint = defineEndpoint({
    name: "forwarded",
    validateResponses: true,
    routes: [
      queryRoute({
        path: "/",
        response: v.object({ _id: v.string() }),
        handler: () =>
          forwardQuery({
            result: [{ _id: "a" }],
            pagedResultsCookie: "next",
            totalPagedResults: 9,
          }),
      }),
    ],
  });
  const page = endpoint.dispatch(crestRequest("query"), callContext()) as {
    totalPagedResults: number;
    pagedResultsCookie: string;
  };
  assert.equal(page.totalPagedResults, 9);
  assert.equal(page.pagedResultsCookie, "next");
});

test("a nullable response member accepts the null IDM actually returns", () => {
  const endpoint = defineEndpoint({
    name: "nulls",
    validateResponses: true,
    routes: [
      route({
        method: "read",
        path: "/",
        // `manager` is an unset single-valued relationship: IDM sends `null`,
        // and a plain `optional()` would reject it under strict validation.
        response: v.object({
          userName: v.string(),
          managerRef: v.nullable(v.string()),
        }),
        handler: () => ({ userName: "ada", managerRef: null }),
      }),
    ],
  });
  assert.deepEqual(endpoint.dispatch(crestRequest("read"), callContext()), {
    userName: "ada",
    managerRef: null,
  });
});
