// The generated-bundle linter. These three constructs make an endpoint fail to
// REGISTER on IDM (an un-routable 404), so the build must refuse to emit them.
//
// Managed file — regenerated by `aic workspace update`.

import assert from "node:assert/strict";
import { test } from "node:test";

import { findRuntimeBanViolations } from "../tools/idm-runtime-bans.mjs";

const rules = (code) => findRuntimeBanViolations(code).map((v) => v.rule);

test("clean ES5 output passes", () => {
  assert.deepEqual(
    rules("var a = 1; function f(b) { return b + a; } f(2);"),
    []
  );
});

test("a default parameter is caught in every function form", () => {
  assert.deepEqual(rules("function f(a = 1) {}"), ["no-default-params"]);
  assert.deepEqual(rules("var f = function (a = 1) {};"), [
    "no-default-params",
  ]);
  assert.deepEqual(rules("var o = { m(a = 1) {} };"), ["no-default-params"]);
});

test("a destructuring default inside the body is not a default parameter", () => {
  assert.deepEqual(rules("function f(o) { var a = o.a || 1; return a; }"), []);
});

test("const in a loop initializer is caught for for, for-in and for-of", () => {
  assert.deepEqual(rules("for (const i of xs) { g(i); }"), [
    "no-const-loop-init",
  ]);
  assert.deepEqual(rules("for (const k in o) { g(k); }"), [
    "no-const-loop-init",
  ]);
  assert.deepEqual(rules("for (const i = 0; i < 1; ) { g(i); }"), [
    "no-const-loop-init",
  ]);
  assert.deepEqual(rules("for (let i = 0; i < 1; i++) { g(i); }"), []);
});

test("a trailing comma in a parameter list is caught, in an argument list is not", () => {
  assert.deepEqual(rules("function f(a, b,) {}"), ["no-trailing-param-comma"]);
  assert.deepEqual(rules("f(1, 2,);"), []);
  assert.deepEqual(rules("var o = { a: 1, };"), []);
  assert.deepEqual(rules("var xs = [1, 2, ];"), []);
});

test("violations are reported with their line numbers, in order", () => {
  const code = ["function a(x, y,) {}", "", "function b(z = 1) {}"].join("\n");
  assert.deepEqual(
    findRuntimeBanViolations(code).map((v) => [v.line, v.rule]),
    [
      [1, "no-trailing-param-comma"],
      [3, "no-default-params"],
    ]
  );
});

test("bare Reflect and Proxy references are rejected", () => {
  assert.deepEqual(rules("Reflect.get(target, key);"), [
    "no-unsupported-global",
  ]);
  assert.deepEqual(rules("new Proxy(target, handler);"), [
    "no-unsupported-global",
  ]);
  assert.deepEqual(rules("helpers.Reflect.get(target, key);"), []);
});
