// Validation combinators. Managed file — regenerated by `aic workspace update`.

import assert from "node:assert/strict";
import { test } from "node:test";

import { v, type Issue, type Validator } from "../framework/index.ts";

function run<T>(validator: Validator<T>, input: unknown, mode: "strict" | "coerce" = "strict") {
  const issues: Issue[] = [];
  const value = validator.parse(input, "x", issues, mode);
  return { value, issues };
}

const boundedString = v.string({
  minLength: 2,
  maxLength: 4,
  pattern: /^[a-z]+$/,
});
const boundedInteger = v.integer({ min: 1, max: 100 });
const bool = v.boolean();
const optionalString = v.optional(v.string());
const defaultInteger = v.withDefault(v.integer({ min: 0 }), 20);
const commaList = v.csv(v.string({ minLength: 1 }));
const boundedList = v.list(v.string(), { minItems: 1, maxItems: 2 });
const fixedObject = v.object({
  name: v.string({ minLength: 1 }),
  note: v.optional(v.string()),
});

type Expected = { value?: unknown; messages?: string[]; paths?: string[] };
type ParseCase = readonly [name: string, validator: Validator<unknown>, input: unknown, expected: Expected];

function accepted(
  name: string,
  validator: Validator<unknown>,
  input: unknown,
  value: unknown
): ParseCase {
  return [name, validator, input, { value }];
}

function rejected(
  name: string,
  validator: Validator<unknown>,
  input: unknown,
  message: string,
  path?: string
): ParseCase {
  return [name, validator, input, {
    messages: [message],
    ...(path === undefined ? {} : { paths: [path] }),
  }];
}

const describedPattern = v.string({
  pattern: /^w-/,
  patternDescription: "start with w-",
});
const csvEnum = v.csv(v.enumOf(["owner", "history"]));
const nullableString = v.nullable(v.string());
const maybeString = v.optional(v.nullable(v.string()));
const shortRecord = v.record(v.string({ maxLength: 2 }));
const INTEGER = "expected an integer";
/** An absent optional is ABSENT in the parsed value, not a key holding `undefined`. */
const PARSED_OBJECT = { name: "a" };
const EXPLICIT_UNDEFINED = { name: "a", note: undefined };

const parseCases: ParseCase[] = [
  accepted("string: valid", boundedString, "abc", "abc"),
  rejected("string: minimum", boundedString, "a", "must be at least 2 characters"),
  rejected("string: maximum", boundedString, "abcde", "must be at most 4 characters"),
  rejected("string: pattern", boundedString, "AB", "must match /^[a-z]+$/"),
  rejected("string: wrong type", boundedString, 7, "expected a string"),
  rejected("string: described pattern", describedPattern, "nope", "must start with w-"),
  rejected("integer: strict string", boundedInteger, "42", INTEGER),
  accepted("integer: native number", boundedInteger, 42, 42),
  rejected("integer: fraction", boundedInteger, 1.5, INTEGER),
  rejected("integer: blank", boundedInteger, "", INTEGER),
  rejected("integer: non-numeric", boundedInteger, "nope", INTEGER),
  rejected("integer: minimum", boundedInteger, 0, "must be at least 1"),
  rejected("integer: maximum", boundedInteger, 101, "must be at most 100"),
  accepted("number: fraction", v.number(), 1.5, 1.5),
  rejected("boolean: true string", bool, "true", "expected true or false"),
  rejected("boolean: false string", bool, "false", "expected true or false"),
  accepted("boolean: native", bool, true, true),
  rejected("boolean: invalid string", bool, "yes", "expected true or false"),
  accepted("optional: undefined", optionalString, undefined, undefined),
  rejected("optional: null", optionalString, null, "expected a string"),
  accepted("optional: empty string is a value", optionalString, "", ""),
  accepted("optional: present", optionalString, "x", "x"),
  accepted("nullable: explicit null", nullableString, null, null),
  accepted("nullable: present", nullableString, "x", "x"),
  rejected("nullable: wrong type", nullableString, 7, "expected a string"),
  accepted("nullable+optional: absent", maybeString, undefined, undefined),
  accepted("nullable+optional: null", maybeString, null, null),
  accepted("default: absent", defaultInteger, undefined, 20),
  accepted("default: present", defaultInteger, 3, 3),
  accepted("csv: array", commaList, ["a", "b"], ["a", "b"]),
  rejected("csv: strict string", csvEnum, "owner,nope", "expected a comma-separated list"),
  rejected("list: minimum", boundedList, [], "must have at least 1 items"),
  rejected("list: maximum", boundedList, ["a", "b", "c"], "must have at most 2 items"),
  rejected("list: wrong type", boundedList, "a", "expected an array"),
  accepted("object: declared fields", fixedObject, { name: "a" }, PARSED_OBJECT),
  accepted(
    "object: an explicit undefined is still absent",
    fixedObject,
    EXPLICIT_UNDEFINED,
    PARSED_OBJECT
  ),
  accepted(
    "object: a nullable member keeps its null",
    v.object({ note: v.nullable(v.string()) }),
    { note: null },
    { note: null }
  ),
  accepted(
    "object: a defaulted member is present even when absent",
    v.object({ limit: v.withDefault(v.integer(), 20) }),
    {},
    { limit: 20 }
  ),
  rejected("object: required field", fixedObject, {}, "is required", "x.name"),
  rejected("object: unknown field", fixedObject, { name: "a", extra: 1 }, "is not a known field"),
  rejected("object: wrong type", fixedObject, [], "expected an object"),
  rejected("record: value path", shortRecord, { a: "xyz" }, "must be at most 2 characters", "x.a"),
  rejected("patch: operation name", v.patchOperations(), [{ operation: "frobnicate", field: "/x" }], "must be one of: add, remove, replace, increment, move, copy, transform"),
  rejected("UUID: pattern", v.uuid(), "not-a-uuid", "must be a UUID"),
  rejected("ISO date: pattern", v.isoDate(), "2026-13", "must be a date in YYYY-MM-DD form"),
  rejected("ISO date: calendar", v.isoDate(), "2026-02-29", "must be a date in YYYY-MM-DD form"),
  accepted("ISO date: leap year", v.isoDate(), "2028-02-29", "2028-02-29"),
];

for (const [name, validator, input, expected] of parseCases) {
  test(name, () => {
    const parsed = run(validator, input);
    if ("value" in expected) {
      assert.deepEqual(parsed.value, expected.value);
    }
    if (expected.messages !== undefined) {
      assert.deepEqual(
        parsed.issues.map((issue) => issue.message),
        expected.messages
      );
    }
    if (expected.paths !== undefined) {
      assert.deepEqual(
        parsed.issues.map((issue) => issue.path),
        expected.paths
      );
    }
    if (expected.messages === undefined && expected.paths === undefined) {
      assert.deepEqual(parsed.issues, []);
    }
  });
}

test("enumOf preserves its literal union", () => {
  const validator = v.enumOf(["active", "retired", "draft"]);
  const parsed = run(validator, "retired");
  const narrowed: "active" | "retired" | "draft" = parsed.value;
  assert.equal(narrowed, "retired");
});

test("coercion remains available for URL and header-shaped inputs", () => {
  assert.deepEqual(run(boundedInteger, "42", "coerce"), {
    value: 42,
    issues: [],
  });
  assert.deepEqual(run(bool, "true", "coerce"), { value: true, issues: [] });
  assert.deepEqual(run(optionalString, "", "coerce"), {
    value: undefined,
    issues: [],
  });
  assert.deepEqual(run(commaList, "a, b ,,c", "coerce"), {
    value: ["a", "b", "c"],
    issues: [],
  });
});

test("stateful regular expressions give stable results across requests", () => {
  const validator = v.string({ pattern: /^a+$/g });
  assert.deepEqual(run(validator, "aaa").issues, []);
  assert.deepEqual(run(validator, "aaa").issues, []);
  assert.equal(run(validator, "bbb").issues.length, 1);
  assert.deepEqual(run(validator, "aaa").issues, []);
});

test("an absent optional does not become a key", () => {
  const parsed = run(fixedObject, { name: "a" }).value as Record<
    string,
    unknown
  >;
  assert.equal("note" in parsed, false);
  assert.deepEqual(Object.keys(parsed), ["name"]);
});

test("object collects every failure", () => {
  const validator = v.object({
    name: v.string({ minLength: 3 }),
    count: v.integer({ min: 1 }),
  });
  assert.equal(run(validator, { name: "a", count: 0 }).issues.length, 2);
});

test("record returns every valid member", () => {
  assert.deepEqual(run(v.record(v.string()), { a: "x", b: "y" }).value, {
    a: "x",
    b: "y",
  });
});

test("patch operations accept IDM's index-keyed Java-list mirror", () => {
  const parsed = run(v.patchOperations({ minItems: 1 }), {
    "0": { operation: "replace", field: "/name", value: "n" },
    "1": { operation: "remove", field: "/tags" },
  });
  assert.deepEqual(parsed.issues, []);
  assert.deepEqual(
    parsed.value.map(({ operation, field }) => ({ operation, field })),
    [
      { operation: "replace", field: "/name" },
      { operation: "remove", field: "/tags" },
    ]
  );
});

const schemaCases: readonly (readonly [string, unknown, unknown])[] = [
  ["enum schema lists its alternatives", v.enumOf(["a", "b"]).schema["enum"], ["a", "b"]],
  ["optional marks itself optional", optionalString.isOptional, true],
  ["default reaches JSON Schema", defaultInteger.schema["default"], 20],
  ["object schema lists only required members", v.object({
      name: v.string(),
      note: optionalString,
      limit: defaultInteger,
    }).schema["required"], ["name"]],
  ["object schema rejects extra members", fixedObject.schema["additionalProperties"], false],
  ["UUID schema carries a pattern", typeof v.uuid().schema["pattern"], "string"],
  // OpenAPI 3.1 is JSON Schema 2020-12: a union `type`, not `nullable: true`.
  ["nullable widens the schema type", nullableString.schema["type"], ["string", "null"]],
  ["nullable widens an enum too", v.nullable(v.enumOf(["a"])).schema["enum"], ["a", null]],
  ["nullable is about the value, not presence", nullableString.isOptional, false],
  ["nullable inside optional stays optional", maybeString.isOptional, true],
];

for (const [name, actual, expected] of schemaCases) {
  test(name, () => assert.deepEqual(actual, expected));
}

test("parseShape locates a missing required member", () => {
  const issues: Issue[] = [];
  const parsed = v.parseShape(
    { limit: v.integer(), cursor: v.optional(v.string()) },
    "query",
    (key) => ({ cursor: "abc" })[key as "cursor"],
    issues
  );
  assert.equal(issues[0]?.path, "query.limit");
  assert.equal(parsed.cursor, "abc");
});
